/** @license
Copyright The Closure Library Authors.
SPDX-License-Identifier: Apache-2.0
*/
(function() {'use strict';var m;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var p=ca(this);function r(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
r("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=p[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function t(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
r("Promise",function(a){function b(g){this.g=0;this.i=void 0;this.h=[];this.s=!1;var h=this.j();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(null==this.g){this.g=[];var h=this;this.i(function(){h.l()})}this.g.push(g)};var e=p.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(l){this.j(l)}}}this.g=null};c.prototype.j=function(g){this.i(function(){throw g;})};b.prototype.j=function(){function g(l){return function(n){k||(k=!0,l.call(h,n))}}var h=this,k=!1;return{resolve:g(this.A),reject:g(this.l)}};b.prototype.A=function(g){if(g===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.D(g);else{a:switch(typeof g){case "object":var h=null!=g;break a;case "function":h=!0;break a;default:h=!1}h?this.v(g):this.m(g)}};
b.prototype.v=function(g){var h=void 0;try{h=g.then}catch(k){this.l(k);return}"function"==typeof h?this.F(h,g):this.m(g)};b.prototype.l=function(g){this.o(2,g)};b.prototype.m=function(g){this.o(1,g)};b.prototype.o=function(g,h){if(0!=this.g)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.g);this.g=g;this.i=h;2===this.g&&this.B();this.u()};b.prototype.B=function(){var g=this;e(function(){if(g.C()){var h=p.console;"undefined"!==typeof h&&h.error(g.i)}},1)};b.prototype.C=
function(){if(this.s)return!1;var g=p.CustomEvent,h=p.Event,k=p.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof g?g=new g("unhandledrejection",{cancelable:!0}):"function"===typeof h?g=new h("unhandledrejection",{cancelable:!0}):(g=p.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return k(g)};b.prototype.u=function(){if(null!=this.h){for(var g=0;g<this.h.length;++g)f.h(this.h[g]);this.h=null}};var f=new c;b.prototype.D=
function(g){var h=this.j();g.ia(h.resolve,h.reject)};b.prototype.F=function(g,h){var k=this.j();try{g.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(g,h){function k(B,E){return"function"==typeof B?function(L){try{l(B(L))}catch(T){n(T)}}:E}var l,n,q=new b(function(B,E){l=B;n=E});this.ia(k(g,l),k(h,n));return q};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.ia=function(g,h){function k(){switch(l.g){case 1:g(l.i);break;case 2:h(l.i);break;default:throw Error("Unexpected state: "+
l.g);}}var l=this;null==this.h?f.h(k):this.h.push(k);this.s=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var l=t(g),n=l.next();!n.done;n=l.next())d(n.value).ia(h,k)})};b.all=function(g){var h=t(g),k=h.next();return k.done?d([]):new b(function(l,n){function q(L){return function(T){B[L]=T;E--;0==E&&l(B)}}var B=[],E=0;do B.push(void 0),E++,d(k.value).ia(q(B.length-1),n),k=h.next();while(!k.done)})};return b});
function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
r("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=t(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function e(k){if(!u(k,g)){var l=new c;ba(k,g,{value:l})}}function f(k){var l=Object[k];l&&(Object[k]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return l(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
n=new a([[k,2],[l,3]]);if(2!=n.get(k)||3!=n.get(l))return!1;n.delete(k);n.set(l,4);return!n.has(k)&&4==n.get(l)}catch(q){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,g))throw Error("WeakMap key fail: "+k);k[g][this.g]=l;return this};b.prototype.get=function(k){return d(k)&&u(k,g)?k[g][this.g]:void 0};b.prototype.has=function(k){return d(k)&&u(k,
g)&&u(k[g],this.g)};b.prototype.delete=function(k){return d(k)&&u(k,g)&&u(k[g],this.g)?delete k[g][this.g]:!1};return b});
r("Map",function(a){function b(){var h={};return h.T=h.next=h.head=h}function c(h,k){var l=h[1];return da(function(){if(l){for(;l.head!=h[1];)l=l.T;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(h,k){var l=k&&typeof k;"object"==l||"function"==l?f.has(k)?l=f.get(k):(l=""+ ++g,f.set(k,l)):l="p_"+k;var n=h[0][l];if(n&&u(h[0],l))for(h=0;h<n.length;h++){var q=n[h];if(k!==k&&q.key!==q.key||k===q.key)return{id:l,list:n,index:h,K:q}}return{id:l,
list:n,index:-1,K:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=t(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),k=new a(t([[h,"s"]]));if("s"!=k.get(h)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),n=l.next();if(n.done||n.value[0]!=h||"s"!=n.value[1])return!1;n=l.next();return n.done||4!=n.value[0].x||
"t"!=n.value[1]||!l.next().done?!1:!0}catch(q){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=0===h?0:h;var l=d(this,h);l.list||(l.list=this[0][l.id]=[]);l.K?l.K.value=k:(l.K={next:this[1],T:this[1].T,head:this[1],key:h,value:k},l.list.push(l.K),this[1].T.next=l.K,this[1].T=l.K,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.K&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],h.K.T.next=h.K.next,h.K.next.T=h.K.T,h.K.head=null,
this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].T=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).K};e.prototype.get=function(h){return(h=d(this,h).K)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,k){for(var l=this.entries(),n;!(n=l.next()).done;)n=
n.value,h.call(k,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});r("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});
function la(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}r("Array.prototype.keys",function(a){return a?a:function(){return la(this,function(b){return b})}});
r("Set",function(a){function b(c){this.g=new Map;if(c){c=t(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(t([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||4!=f.value[0].x||
f.value[1]!=f.value[0]?!1:e.next().done}catch(g){return!1}}())return a;b.prototype.add=function(c){c=0===c?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.g.forEach(function(f){return c.call(d,f,f,e)})};return b});r("Array.prototype.entries",function(a){return a?a:function(){return la(this,function(b,c){return[b,c]})}});r("Array.prototype.values",function(a){return a?a:function(){return la(this,function(b,c){return c})}});
r("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});/** @license

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ma=ma||{},v=this||self;function na(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length}function w(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function oa(a,b,c){return a.call.apply(a.bind,arguments)}
function pa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function x(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?oa:pa;return x.apply(null,arguments)}
function qa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}function y(a,b){function c(){}c.prototype=b.prototype;a.Y=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.bc=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};var ra=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};function sa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function ta(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(na(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}};function ua(a,b){this.i=a;this.j=b;this.h=0;this.g=null}ua.prototype.get=function(){if(0<this.h){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.i();return a};var va,wa;a:{for(var xa=["CLOSURE_FLAGS"],ya=v,za=0;za<xa.length;za++)if(ya=ya[xa[za]],null==ya){wa=null;break a}wa=ya}var Aa=wa&&wa[610401301];va=null!=Aa?Aa:!1;function z(a){return/^[\s\xa0]*$/.test(a)};function Ba(){var a=v.navigator;return a&&(a=a.userAgent)?a:""}var Ca,Da=v.navigator;Ca=Da?Da.userAgentData||null:null;function A(a){return-1!=Ba().indexOf(a)};function Ea(a){Ea[" "](a);return a}Ea[" "]=function(){};var Fa=va&&Ca&&0<Ca.brands.length?!1:A("Opera"),C=va&&Ca&&0<Ca.brands.length?!1:A("Trident")||A("MSIE"),Ga=A("Edge"),Ha=Ga||C,Ia=A("Gecko")&&!(-1!=Ba().toLowerCase().indexOf("webkit")&&!A("Edge"))&&!(A("Trident")||A("MSIE"))&&!A("Edge"),Ja=-1!=Ba().toLowerCase().indexOf("webkit")&&!A("Edge");function Ka(){var a=v.document;return a?a.documentMode:void 0}var La;
a:{var Ma="",Na=function(){var a=Ba();if(Ia)return/rv:([^\);]+)(\)|;)/.exec(a);if(Ga)return/Edge\/([\d\.]+)/.exec(a);if(C)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ja)return/WebKit\/(\S+)/.exec(a);if(Fa)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Na&&(Ma=Na?Na[1]:"");if(C){var Oa=Ka();if(null!=Oa&&Oa>parseFloat(Ma)){La=String(Oa);break a}}La=Ma}var Pa=La,Qa;if(v.document&&C){var Ra=Ka();Qa=Ra?Ra:parseInt(Pa,10)||void 0}else Qa=void 0;var Sa=Qa;function Ta(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ua(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function Va(a){var b={},c;for(c in a)b[c]=a[c];return b}var Wa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Xa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Wa.length;f++)c=Wa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Ya(a){var b=1;a=a.split(":");for(var c=[];0<b&&a.length;)c.push(a.shift()),b--;a.length&&c.push(a.join(":"));return c};function Za(a){v.setTimeout(function(){throw a;},0)};function $a(){this.h=this.g=null}$a.prototype.add=function(a,b){var c=ab.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c};function bb(){var a=cb,b=null;a.g&&(b=a.g,a.g=a.g.next,a.g||(a.h=null),b.next=null);return b}var ab=new ua(function(){return new db},function(a){return a.reset()});function db(){this.next=this.g=this.h=null}db.prototype.set=function(a,b){this.h=a;this.g=b;this.next=null};db.prototype.reset=function(){this.next=this.g=this.h=null};var eb,fb=!1,cb=new $a;function gb(a,b){eb||hb();fb||(eb(),fb=!0);cb.add(a,b)}function hb(){var a=v.Promise.resolve(void 0);eb=function(){a.then(ib)}}function ib(){for(var a;a=bb();){try{a.h.call(a.g)}catch(c){Za(c)}var b=ab;b.j(a);100>b.h&&(b.h++,a.next=b.g,b.g=a)}fb=!1};function D(){this.s=this.s;this.C=this.C}D.prototype.s=!1;D.prototype.sa=function(){this.s||(this.s=!0,this.N())};D.prototype.N=function(){if(this.C)for(;this.C.length;)this.C.shift()()};function F(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1}F.prototype.h=function(){this.defaultPrevented=!0};var jb=function(){if(!v.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};v.addEventListener("test",c,b);v.removeEventListener("test",c,b)}catch(d){}return a}();function kb(a,b){F.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.i=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;if(b=a.relatedTarget){if(Ia){a:{try{Ea(b.nodeName);var e=!0;break a}catch(f){}e=
!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=
a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:lb[a.pointerType]||"";this.state=a.state;this.i=a;a.defaultPrevented&&kb.Y.h.call(this)}}y(kb,F);var lb={2:"touch",3:"pen",4:"mouse"};kb.prototype.h=function(){kb.Y.h.call(this);var a=this.i;a.preventDefault?a.preventDefault():a.returnValue=!1};var mb="closure_listenable_"+(1E6*Math.random()|0);var nb=0;function ob(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.la=e;this.key=++nb;this.ea=this.ha=!1}function pb(a){a.ea=!0;a.listener=null;a.proxy=null;a.src=null;a.la=null};function qb(a){this.src=a;this.g={};this.h=0}qb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);var g=rb(a,b,d,e);-1<g?(b=a[g],c||(b.ha=!1)):(b=new ob(b,this.src,f,!!d,e),b.ha=c,a.push(b));return b};function sb(a,b){var c=b.type;if(c in a.g){var d=a.g[c],e=ra(d,b),f;(f=0<=e)&&Array.prototype.splice.call(d,e,1);f&&(pb(b),0==a.g[c].length&&(delete a.g[c],a.h--))}}
function rb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.ea&&f.listener==b&&f.capture==!!c&&f.la==d)return e}return-1};var tb="closure_lm_"+(1E6*Math.random()|0),ub={},vb=0;function wb(a,b,c,d,e){if(d&&d.once)return xb(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)wb(a,b[f],c,d,e);return null}c=yb(c);return a&&a[mb]?a.O(b,c,w(d)?!!d.capture:!!d,e):zb(a,b,c,!1,d,e)}
function zb(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=w(e)?!!e.capture:!!e,h=Ab(a);h||(a[tb]=h=new qb(a));c=h.add(b,c,d,g,f);if(c.proxy)return c;d=Bb();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)jb||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Cb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");vb++;return c}
function Bb(){function a(c){return b.call(a.src,a.listener,c)}var b=Db;return a}function xb(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)xb(a,b[f],c,d,e);return null}c=yb(c);return a&&a[mb]?a.P(b,c,w(d)?!!d.capture:!!d,e):zb(a,b,c,!0,d,e)}
function Eb(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Eb(a,b[f],c,d,e);else(d=w(d)?!!d.capture:!!d,c=yb(c),a&&a[mb])?(a=a.i,b=String(b).toString(),b in a.g&&(f=a.g[b],c=rb(f,c,d,e),-1<c&&(pb(f[c]),Array.prototype.splice.call(f,c,1),0==f.length&&(delete a.g[b],a.h--)))):a&&(a=Ab(a))&&(b=a.g[b.toString()],a=-1,b&&(a=rb(b,c,d,e)),(c=-1<a?b[a]:null)&&Fb(c))}
function Fb(a){if("number"!==typeof a&&a&&!a.ea){var b=a.src;if(b&&b[mb])sb(b.i,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Cb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);vb--;(c=Ab(b))?(sb(c,a),0==c.h&&(c.src=null,b[tb]=null)):pb(a)}}}function Cb(a){return a in ub?ub[a]:ub[a]="on"+a}function Db(a,b){if(a.ea)a=!0;else{b=new kb(b,this);var c=a.listener,d=a.la||a.src;a.ha&&Fb(a);a=c.call(d,b)}return a}
function Ab(a){a=a[tb];return a instanceof qb?a:null}var Gb="__closure_events_fn_"+(1E9*Math.random()>>>0);function yb(a){if("function"===typeof a)return a;a[Gb]||(a[Gb]=function(b){return a.handleEvent(b)});return a[Gb]};function G(){D.call(this);this.i=new qb(this);this.R=this;this.I=null}y(G,D);G.prototype[mb]=!0;G.prototype.removeEventListener=function(a,b,c,d){Eb(this,a,b,c,d)};
function H(a,b){var c,d=a.I;if(d)for(c=[];d;d=d.I)c.push(d);a=a.R;d=b.type||b;if("string"===typeof b)b=new F(b,a);else if(b instanceof F)b.target=b.target||a;else{var e=b;b=new F(d,a);Xa(b,e)}e=!0;if(c)for(var f=c.length-1;0<=f;f--){var g=b.g=c[f];e=Hb(g,d,!0,b)&&e}g=b.g=a;e=Hb(g,d,!0,b)&&e;e=Hb(g,d,!1,b)&&e;if(c)for(f=0;f<c.length;f++)g=b.g=c[f],e=Hb(g,d,!1,b)&&e}
G.prototype.N=function(){G.Y.N.call(this);if(this.i){var a=this.i,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,pb(d[e]);delete a.g[c];a.h--}}this.I=null};G.prototype.O=function(a,b,c,d){return this.i.add(String(a),b,!1,c,d)};G.prototype.P=function(a,b,c,d){return this.i.add(String(a),b,!0,c,d)};
function Hb(a,b,c,d){b=a.i.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.ea&&g.capture==c){var h=g.listener,k=g.la||g.src;g.ha&&sb(a.i,g);e=!1!==h.call(k,d)&&e}}return e&&!d.defaultPrevented};function Ib(a,b){G.call(this);this.h=a||1;this.g=b||v;this.j=x(this.qb,this);this.l=Date.now()}y(Ib,G);m=Ib.prototype;m.fa=!1;m.S=null;m.qb=function(){if(this.fa){var a=Date.now()-this.l;0<a&&a<.8*this.h?this.S=this.g.setTimeout(this.j,this.h-a):(this.S&&(this.g.clearTimeout(this.S),this.S=null),H(this,"tick"),this.fa&&(Jb(this),this.start()))}};m.start=function(){this.fa=!0;this.S||(this.S=this.g.setTimeout(this.j,this.h),this.l=Date.now())};
function Jb(a){a.fa=!1;a.S&&(a.g.clearTimeout(a.S),a.S=null)}m.N=function(){Ib.Y.N.call(this);Jb(this);delete this.g};function Kb(a,b,c){if("function"===typeof a)c&&(a=x(a,c));else if(a&&"function"==typeof a.handleEvent)a=x(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:v.setTimeout(a,b||0)};function I(a,b,c){D.call(this);this.m=null!=c?a.bind(c):a;this.j=b;this.h=null;this.i=!1;this.g=null}I.prototype=ea(D.prototype);I.prototype.constructor=I;if(ka)ka(I,D);else for(var Lb in D)if("prototype"!=Lb)if(Object.defineProperties){var Mb=Object.getOwnPropertyDescriptor(D,Lb);Mb&&Object.defineProperty(I,Lb,Mb)}else I[Lb]=D[Lb];I.Y=D.prototype;I.prototype.l=function(a){this.h=arguments;this.g?this.i=!0:Nb(this)};
I.prototype.N=function(){D.prototype.N.call(this);this.g&&(v.clearTimeout(this.g),this.g=null,this.i=!1,this.h=null)};function Nb(a){a.g=Kb(function(){a.g=null;a.i&&(a.i=!1,Nb(a))},a.j);var b=a.h;a.h=null;a.m.apply(null,b)};function Ob(a){D.call(this);this.h=a;this.g={}}y(Ob,D);var Pb=[];function Qb(a,b,c,d){Array.isArray(c)||(c&&(Pb[0]=c.toString()),c=Pb);for(var e=0;e<c.length;e++){var f=wb(b,c[e],d||a.handleEvent,!1,a.h||a);if(!f)break;a.g[f.key]=f}}function Rb(a){Ta(a.g,function(b,c){this.g.hasOwnProperty(c)&&Fb(b)},a);a.g={}}Ob.prototype.N=function(){Ob.Y.N.call(this);Rb(this)};Ob.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Sb(a){try{return v.JSON.parse(a)}catch(b){}a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);}function Tb(a){var b=[];Ub(new Vb,a,b);return b.join("")}function Vb(){}
function Ub(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(Array.isArray(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Ub(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),Wb(d,c),c.push(":"),Ub(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":Wb(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}}var Xb={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\v":"\\u000b"},Yb=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;
function Wb(a,b){b.push('"',a.replace(Yb,function(c){var d=Xb[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).slice(1),Xb[c]=d);return d}),'"')};function Zb(){}Zb.prototype.stringify=function(a){return v.JSON.stringify(a,void 0)};Zb.prototype.parse=function(a){return v.JSON.parse(a,void 0)};function $b(){}$b.prototype.h=null;function ac(a){return a.h||(a.h=a.j())};function bc(){}var cc={OPEN:"a",vb:"b",Qa:"c",Hb:"d"};function dc(){F.call(this,"d")}y(dc,F);function ec(){F.call(this,"c")}y(ec,F);var J={},fc=null;function gc(){return fc=fc||new G}J.Sa="serverreachability";function hc(a){F.call(this,J.Sa,a)}y(hc,F);function ic(a){var b=gc();H(b,new hc(b,a))}J.STAT_EVENT="statevent";function jc(a,b){F.call(this,J.STAT_EVENT,a);this.stat=b}y(jc,F);function K(a){var b=gc();H(b,new jc(b,a))}J.Ta="timingevent";function kc(a,b){F.call(this,J.Ta,a);this.size=b}y(kc,F);
function lc(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");return v.setTimeout(function(){a()},b)};function mc(){this.g=!0}mc.prototype.Da=function(){this.g=!1};function nc(a,b,c,d,e,f){a.info(function(){if(a.g)if(f){var g="";for(var h=f.split("&"),k=0;k<h.length;k++){var l=h[k].split("=");if(1<l.length){var n=l[0];l=l[1];var q=n.split("_");g=2<=q.length&&"type"==q[1]?g+(n+"="+l+"&"):g+(n+"=redacted&")}}}else g=null;else g=f;return"XMLHTTP REQ ("+d+") [attempt "+e+"]: "+b+"\n"+c+"\n"+g})}
function oc(a,b,c,d,e,f,g){a.info(function(){return"XMLHTTP RESP ("+d+") [ attempt "+e+"]: "+b+"\n"+c+"\n"+f+" "+g})}function M(a,b,c,d){a.info(function(){return"XMLHTTP TEXT ("+b+"): "+pc(a,c)+(d?" "+d:"")})}function qc(a,b){a.info(function(){return"TIMEOUT: "+b})}mc.prototype.info=function(){};
function pc(a,b){if(!a.g)return b;if(!b)return null;try{var c=JSON.parse(b);if(c)for(a=0;a<c.length;a++)if(Array.isArray(c[a])){var d=c[a];if(!(2>d.length)){var e=d[1];if(Array.isArray(e)&&!(1>e.length)){var f=e[0];if("noop"!=f&&"stop"!=f&&"close"!=f)for(var g=1;g<e.length;g++)e[g]=""}}}return Tb(c)}catch(h){return b}};var rc={NO_ERROR:0,rb:1,Eb:2,Db:3,yb:4,Cb:5,Fb:6,Pa:7,TIMEOUT:8,Ib:9};var sc={wb:"complete",Sb:"success",Qa:"error",Pa:"abort",Kb:"ready",Lb:"readystatechange",TIMEOUT:"timeout",Gb:"incrementaldata",Jb:"progress",zb:"downloadprogress",ac:"uploadprogress"};var tc;function uc(){}y(uc,$b);uc.prototype.g=function(){var a=vc(this);return a?new ActiveXObject(a):new XMLHttpRequest};uc.prototype.j=function(){var a={};vc(this)&&(a[0]=!0,a[1]=!0);return a};
function vc(a){if(!a.i&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.i=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.i}tc=new uc;function wc(a,b,c,d){this.l=a;this.j=b;this.m=c;this.W=d||1;this.U=new Ob(this);this.P=45E3;a=Ha?125:void 0;this.V=new Ib(a);this.H=null;this.i=!1;this.u=this.A=this.v=this.L=this.F=this.X=this.B=null;this.D=[];this.g=null;this.s=0;this.o=this.C=null;this.ca=-1;this.I=!1;this.O=0;this.M=null;this.ba=this.J=this.aa=this.R=!1;this.h=new xc}function xc(){this.i=null;this.g="";this.h=!1}var yc={},zc={};m=wc.prototype;m.setTimeout=function(a){this.P=a};
function Ac(a,b,c){a.L=1;a.v=Bc(N(b));a.u=c;a.R=!0;Cc(a,null)}function Cc(a,b){a.F=Date.now();Dc(a);a.A=N(a.v);var c=a.A,d=a.W;Array.isArray(d)||(d=[String(d)]);Ec(c.i,"t",d);a.s=0;c=a.l.J;a.h=new xc;a.g=Fc(a.l,c?b:null,!a.u);0<a.O&&(a.M=new I(x(a.Oa,a,a.g),a.O));Qb(a.U,a.g,"readystatechange",a.nb);b=a.H?Va(a.H):{};a.u?(a.C||(a.C="POST"),b["Content-Type"]="application/x-www-form-urlencoded",a.g.ga(a.A,a.C,a.u,b)):(a.C="GET",a.g.ga(a.A,a.C,null,b));ic(1);nc(a.j,a.C,a.A,a.m,a.W,a.u)}
m.nb=function(a){a=a.target;var b=this.M;b&&3==O(a)?b.l():this.Oa(a)};
m.Oa=function(a){try{if(a==this.g)a:{var b=O(this.g),c=this.g.Ha(),d=this.g.da();if(!(3>b)&&(3!=b||Ha||this.g&&(this.h.h||this.g.ja()||Gc(this.g)))){this.I||4!=b||7==c||(8==c||0>=d?ic(3):ic(2));Hc(this);var e=this.g.da();this.ca=e;b:if(Ic(this)){var f=Gc(this.g);a="";var g=f.length,h=4==O(this.g);if(!this.h.i){if("undefined"===typeof TextDecoder){P(this);Kc(this);var k="";break b}this.h.i=new v.TextDecoder}for(c=0;c<g;c++)this.h.h=!0,a+=this.h.i.decode(f[c],{stream:h&&c==g-1});f.length=0;this.h.g+=
a;this.s=0;k=this.h.g}else k=this.g.ja();this.i=200==e;oc(this.j,this.C,this.A,this.m,this.W,b,e);if(this.i){if(this.aa&&!this.J){b:{if(this.g){var l,n=this.g;if((l=n.g?n.g.getResponseHeader("X-HTTP-Initial-Response"):null)&&!z(l)){var q=l;break b}}q=null}if(e=q)M(this.j,this.m,e,"Initial handshake response via X-HTTP-Initial-Response"),this.J=!0,Lc(this,e);else{this.i=!1;this.o=3;K(12);P(this);Kc(this);break a}}this.R?(Mc(this,b,k),Ha&&this.i&&3==b&&(Qb(this.U,this.V,"tick",this.mb),this.V.start())):
(M(this.j,this.m,k,null),Lc(this,k));4==b&&P(this);this.i&&!this.I&&(4==b?Nc(this.l,this):(this.i=!1,Dc(this)))}else Oc(this.g),400==e&&0<k.indexOf("Unknown SID")?(this.o=3,K(12)):(this.o=0,K(13)),P(this),Kc(this)}}}catch(B){}finally{}};function Ic(a){return a.g?"GET"==a.C&&2!=a.L&&a.l.Ia:!1}
function Mc(a,b,c){for(var d=!0,e;!a.I&&a.s<c.length;)if(e=Pc(a,c),e==zc){4==b&&(a.o=4,K(14),d=!1);M(a.j,a.m,null,"[Incomplete Response]");break}else if(e==yc){a.o=4;K(15);M(a.j,a.m,c,"[Invalid Chunk]");d=!1;break}else M(a.j,a.m,e,null),Lc(a,e);Ic(a)&&0!=a.s&&(a.h.g=a.h.g.slice(a.s),a.s=0);4!=b||0!=c.length||a.h.h||(a.o=1,K(16),d=!1);a.i=a.i&&d;d?0<c.length&&!a.ba&&(a.ba=!0,b=a.l,b.g==a&&b.ma&&!b.O&&(b.j.info("Great, no buffering proxy detected. Bytes received: "+c.length),Qc(b),b.O=!0,K(11))):(M(a.j,
a.m,c,"[Invalid Chunked Response]"),P(a),Kc(a))}m.mb=function(){if(this.g){var a=O(this.g),b=this.g.ja();this.s<b.length&&(Hc(this),Mc(this,a,b),this.i&&4!=a&&Dc(this))}};function Pc(a,b){var c=a.s,d=b.indexOf("\n",c);if(-1==d)return zc;c=Number(b.substring(c,d));if(isNaN(c))return yc;d+=1;if(d+c>b.length)return zc;b=b.slice(d,d+c);a.s=d+c;return b}m.cancel=function(){this.I=!0;P(this)};function Dc(a){a.X=Date.now()+a.P;Rc(a,a.P)}
function Rc(a,b){if(null!=a.B)throw Error("WatchDog timer not null");a.B=lc(x(a.kb,a),b)}function Hc(a){a.B&&(v.clearTimeout(a.B),a.B=null)}m.kb=function(){this.B=null;var a=Date.now();0<=a-this.X?(qc(this.j,this.A),2!=this.L&&(ic(3),K(17)),P(this),this.o=2,Kc(this)):Rc(this,this.X-a)};function Kc(a){0==a.l.G||a.I||Nc(a.l,a)}function P(a){Hc(a);var b=a.M;b&&"function"==typeof b.sa&&b.sa();a.M=null;Jb(a.V);Rb(a.U);a.g&&(b=a.g,a.g=null,b.abort(),b.sa())}
function Lc(a,b){try{var c=a.l;if(0!=c.G&&(c.g==a||Sc(c.h,a)))if(!a.J&&Sc(c.h,a)&&3==c.G){try{var d=c.Ja.g.parse(b)}catch(Jc){d=null}if(Array.isArray(d)&&3==d.length){var e=d;if(0==e[0])a:{if(!c.u){if(c.g)if(c.g.F+3E3<a.F)Tc(c),Uc(c);else break a;Vc(c);K(18)}}else c.Fa=e[1],0<c.Fa-c.W&&37500>e[2]&&c.F&&0==c.v&&!c.C&&(c.C=lc(x(c.hb,c),6E3));if(1>=Wc(c.h)&&c.na){try{c.na()}catch(Jc){}c.na=void 0}}else Q(c,11)}else if((a.J||c.g==a)&&Tc(c),!z(b))for(e=c.Ja.g.parse(b),b=0;b<e.length;b++){var f=e[b];c.W=
f[0];f=f[1];if(2==c.G)if("c"==f[0]){c.L=f[1];c.oa=f[2];var g=f[3];null!=g&&(c.ra=g,c.j.info("VER="+c.ra));var h=f[4];null!=h&&(c.Ga=h,c.j.info("SVER="+c.Ga));var k=f[5];null!=k&&"number"===typeof k&&0<k&&(d=1.5*k,c.M=d,c.j.info("backChannelRequestTimeoutMs_="+d));d=c;var l=a.g;if(l){var n=l.g?l.g.getResponseHeader("X-Client-Wire-Protocol"):null;if(n){var q=d.h;q.g||-1==n.indexOf("spdy")&&-1==n.indexOf("quic")&&-1==n.indexOf("h2")||(q.j=q.l,q.g=new Set,q.h&&(Xc(q,q.h),q.h=null))}if(d.D){var B=l.g?
l.g.getResponseHeader("X-HTTP-Session-Id"):null;B&&(d.Ea=B,R(d.I,d.D,B))}}c.G=3;c.l&&c.l.Aa();c.ma&&(c.U=Date.now()-a.F,c.j.info("Handshake RTT: "+c.U+"ms"));d=c;var E=a;d.wa=Yc(d,d.J?d.oa:null,d.aa);if(E.J){Zc(d.h,E);var L=E,T=d.M;T&&L.setTimeout(T);L.B&&(Hc(L),Dc(L));d.g=E}else $c(d);0<c.i.length&&ad(c)}else"stop"!=f[0]&&"close"!=f[0]||Q(c,7);else 3==c.G&&("stop"==f[0]||"close"==f[0]?"stop"==f[0]?Q(c,7):bd(c):"noop"!=f[0]&&c.l&&c.l.za(f),c.v=0)}ic(4)}catch(Jc){}};function cd(a,b){this.g=a;this.map=b};function dd(a){this.l=a||10;v.PerformanceNavigationTiming?(a=v.performance.getEntriesByType("navigation"),a=0<a.length&&("hq"==a[0].nextHopProtocol||"h2"==a[0].nextHopProtocol)):a=!!(v.chrome&&v.chrome.loadTimes&&v.chrome.loadTimes()&&v.chrome.loadTimes().wasFetchedViaSpdy);this.j=a?this.l:1;this.g=null;1<this.j&&(this.g=new Set);this.h=null;this.i=[]}function ed(a){return a.h?!0:a.g?a.g.size>=a.j:!1}function Wc(a){return a.h?1:a.g?a.g.size:0}function Sc(a,b){return a.h?a.h==b:a.g?a.g.has(b):!1}
function Xc(a,b){a.g?a.g.add(b):a.h=b}function Zc(a,b){a.h&&a.h==b?a.h=null:a.g&&a.g.has(b)&&a.g.delete(b)}dd.prototype.cancel=function(){this.i=fd(this);if(this.h)this.h.cancel(),this.h=null;else if(this.g&&0!==this.g.size){for(var a=t(this.g.values()),b=a.next();!b.done;b=a.next())b.value.cancel();this.g.clear()}};
function fd(a){if(null!=a.h)return a.i.concat(a.h.D);if(null!=a.g&&0!==a.g.size){var b=a.i;a=t(a.g.values());for(var c=a.next();!c.done;c=a.next())b=b.concat(c.value.D);return b}return sa(a.i)};function gd(a){if(a.Z&&"function"==typeof a.Z)return a.Z();if("undefined"!==typeof Map&&a instanceof Map||"undefined"!==typeof Set&&a instanceof Set)return Array.from(a.values());if("string"===typeof a)return a.split("");if(na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function hd(a){if(a.ta&&"function"==typeof a.ta)return a.ta();if(!a.Z||"function"!=typeof a.Z){if("undefined"!==typeof Map&&a instanceof Map)return Array.from(a.keys());if(!("undefined"!==typeof Set&&a instanceof Set)){if(na(a)||"string"===typeof a){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}b=[];c=0;for(var d in a)b[c++]=d;return b}}}
function id(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(na(a)||"string"===typeof a)Array.prototype.forEach.call(a,b,void 0);else for(var c=hd(a),d=gd(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)};var jd=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function kd(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function S(a){this.g=this.o=this.j="";this.s=null;this.m=this.h="";this.l=!1;var b;a instanceof S?(this.l=a.l,ld(this,a.j),this.o=a.o,this.g=a.g,md(this,a.s),this.h=a.h,nd(this,od(a.i)),this.m=a.m):a&&(b=String(a).match(jd))?(this.l=!1,ld(this,b[1]||"",!0),this.o=pd(b[2]||""),this.g=pd(b[3]||"",!0),md(this,b[4]),this.h=pd(b[5]||"",!0),nd(this,b[6]||"",!0),this.m=pd(b[7]||"")):(this.l=!1,this.i=new qd(null,this.l))}
S.prototype.toString=function(){var a=[],b=this.j;b&&a.push(rd(b,sd,!0),":");var c=this.g;if(c||"file"==b)a.push("//"),(b=this.o)&&a.push(rd(b,sd,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.s,null!=c&&a.push(":",String(c));if(c=this.h)this.g&&"/"!=c.charAt(0)&&a.push("/"),a.push(rd(c,"/"==c.charAt(0)?td:ud,!0));(c=this.i.toString())&&a.push("?",c);(c=this.m)&&a.push("#",rd(c,vd));return a.join("")};
S.prototype.resolve=function(a){var b=N(this),c=!!a.j;c?ld(b,a.j):c=!!a.o;c?b.o=a.o:c=!!a.g;c?b.g=a.g:c=null!=a.s;var d=a.h;if(c)md(b,a.s);else if(c=!!a.h){if("/"!=d.charAt(0))if(this.g&&!this.h)d="/"+d;else{var e=b.h.lastIndexOf("/");-1!=e&&(d=b.h.slice(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],g=0;g<e.length;){var h=e[g++];"."==h?d&&g==e.length&&f.push(""):".."==h?((1<f.length||1==f.length&&""!=f[0])&&
f.pop(),d&&g==e.length&&f.push("")):(f.push(h),d=!0)}d=f.join("/")}else d=e}c?b.h=d:c=""!==a.i.toString();c?nd(b,od(a.i)):c=!!a.m;c&&(b.m=a.m);return b};function N(a){return new S(a)}function ld(a,b,c){a.j=c?pd(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))}function md(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.s=b}else a.s=null}function nd(a,b,c){b instanceof qd?(a.i=b,wd(a.i,a.l)):(c||(b=rd(b,xd)),a.i=new qd(b,a.l))}function R(a,b,c){a.i.set(b,c)}
function Bc(a){R(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Date.now()).toString(36));return a}function pd(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function rd(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,yd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function yd(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}
var sd=/[#\/\?@]/g,ud=/[#\?:]/g,td=/[#\?]/g,xd=/[#\?@]/g,vd=/#/g;function qd(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b}function U(a){a.g||(a.g=new Map,a.h=0,a.i&&kd(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}m=qd.prototype;m.add=function(a,b){U(this);this.i=null;a=V(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};function zd(a,b){U(a);b=V(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a.g.delete(b))}
function Ad(a,b){U(a);b=V(a,b);return a.g.has(b)}m.forEach=function(a,b){U(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};m.ta=function(){U(this);for(var a=Array.from(this.g.values()),b=Array.from(this.g.keys()),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
m.Z=function(a){U(this);var b=[];if("string"===typeof a)Ad(this,a)&&(b=b.concat(this.g.get(V(this,a))));else{a=Array.from(this.g.values());for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};m.set=function(a,b){U(this);this.i=null;a=V(this,a);Ad(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};m.get=function(a,b){if(!a)return b;a=this.Z(a);return 0<a.length?String(a[0]):b};function Ec(a,b,c){zd(a,b);0<c.length&&(a.i=null,a.g.set(V(a,b),sa(c)),a.h+=c.length)}
m.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.Z(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.i=a.join("&")};function od(a){var b=new qd;b.i=a.i;a.g&&(b.g=new Map(a.g),b.h=a.h);return b}function V(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b}
function wd(a,b){b&&!a.j&&(U(a),a.i=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(zd(this,d),Ec(this,e,c))},a));a.j=b};function Bd(a,b){var c=new mc;if(v.Image){var d=new Image;d.onload=qa(W,c,"TestLoadImage: loaded",!0,b,d);d.onerror=qa(W,c,"TestLoadImage: error",!1,b,d);d.onabort=qa(W,c,"TestLoadImage: abort",!1,b,d);d.ontimeout=qa(W,c,"TestLoadImage: timeout",!1,b,d);v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},1E4);d.src=a}else b(!1)}
function Cd(a,b){var c=new mc,d=new AbortController,e=setTimeout(function(){d.abort();W(c,"TestPingServer: timeout",!1,b)},1E4);fetch(a,{signal:d.signal}).then(function(f){clearTimeout(e);f.ok?W(c,"TestPingServer: ok",!0,b):W(c,"TestPingServer: server error",!1,b)}).catch(function(){clearTimeout(e);W(c,"TestPingServer: error",!1,b)})}function W(a,b,c,d,e){try{e&&(e.onload=null,e.onerror=null,e.onabort=null,e.ontimeout=null),d(c)}catch(f){}};function Dd(){this.g=new Zb}function Ed(a,b,c){var d=c||"";try{id(a,function(e,f){var g=e;w(e)&&(g=Tb(e));b.push(d+f+"="+encodeURIComponent(g))})}catch(e){throw b.push(d+"type="+encodeURIComponent("_badmap")),e;}};function Fd(a){this.l=a.fc||null;this.i=a.ob||!1}y(Fd,$b);Fd.prototype.g=function(){return new Gd(this.l,this.i)};Fd.prototype.j=function(a){return function(){return a}}({});function Gd(a,b){G.call(this);this.D=a;this.o=b;this.m=void 0;this.status=this.readyState=0;this.responseType=this.responseText=this.response=this.statusText="";this.onreadystatechange=null;this.u=new Headers;this.h=null;this.B="GET";this.A="";this.g=!1;this.v=this.j=this.l=null}y(Gd,G);m=Gd.prototype;
m.open=function(a,b){if(0!=this.readyState)throw this.abort(),Error("Error reopening a connection");this.B=a;this.A=b;this.readyState=1;Hd(this)};m.send=function(a){if(1!=this.readyState)throw this.abort(),Error("need to call open() first. ");this.g=!0;var b={headers:this.u,method:this.B,credentials:this.m,cache:void 0};a&&(b.body=a);(this.D||v).fetch(new Request(this.A,b)).then(this.Za.bind(this),this.ka.bind(this))};
m.abort=function(){this.response=this.responseText="";this.u=new Headers;this.status=0;this.j&&this.j.cancel("Request was aborted.").catch(function(){});1<=this.readyState&&this.g&&4!=this.readyState&&(this.g=!1,Id(this));this.readyState=0};
m.Za=function(a){if(this.g&&(this.l=a,this.h||(this.status=this.l.status,this.statusText=this.l.statusText,this.h=a.headers,this.readyState=2,Hd(this)),this.g&&(this.readyState=3,Hd(this),this.g)))if("arraybuffer"===this.responseType)a.arrayBuffer().then(this.Xa.bind(this),this.ka.bind(this));else if("undefined"!==typeof v.ReadableStream&&"body"in a){this.j=a.body.getReader();if(this.o){if(this.responseType)throw Error('responseType must be empty for "streamBinaryChunks" mode responses.');this.response=
[]}else this.response=this.responseText="",this.v=new TextDecoder;Jd(this)}else a.text().then(this.Ya.bind(this),this.ka.bind(this))};function Jd(a){a.j.read().then(a.Wa.bind(a)).catch(a.ka.bind(a))}m.Wa=function(a){if(this.g){if(this.o&&a.value)this.response.push(a.value);else if(!this.o){var b=a.value?a.value:new Uint8Array(0);if(b=this.v.decode(b,{stream:!a.done}))this.response=this.responseText+=b}a.done?Id(this):Hd(this);3==this.readyState&&Jd(this)}};
m.Ya=function(a){this.g&&(this.response=this.responseText=a,Id(this))};m.Xa=function(a){this.g&&(this.response=a,Id(this))};m.ka=function(){this.g&&Id(this)};function Id(a){a.readyState=4;a.l=null;a.j=null;a.v=null;Hd(a)}m.setRequestHeader=function(a,b){this.u.append(a,b)};m.getResponseHeader=function(a){return this.h?this.h.get(a.toLowerCase())||"":""};
m.getAllResponseHeaders=function(){if(!this.h)return"";for(var a=[],b=this.h.entries(),c=b.next();!c.done;)c=c.value,a.push(c[0]+": "+c[1]),c=b.next();return a.join("\r\n")};function Hd(a){a.onreadystatechange&&a.onreadystatechange.call(a)}Object.defineProperty(Gd.prototype,"withCredentials",{get:function(){return"include"===this.m},set:function(a){this.m=a?"include":"same-origin"}});function Kd(a){var b="";Ta(a,function(c,d){b+=d;b+=":";b+=c;b+="\r\n"});return b}function Ld(a,b,c){a:{for(d in c){var d=!1;break a}d=!0}d||(c=Kd(c),"string"===typeof a?(encodeURIComponent(String(b)),null!=c&&encodeURIComponent(String(c))):R(a,b,c))};function X(a){G.call(this);this.headers=new Map;this.o=a||null;this.h=!1;this.B=this.g=null;this.H="";this.m=0;this.j="";this.l=this.F=this.u=this.D=!1;this.A=0;this.v=null;this.J="";this.L=this.M=!1}y(X,G);var Md=/^https?$/i,Nd=["POST","PUT"];m=X.prototype;m.Na=function(a){this.M=a};
m.ga=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.j="";this.m=0;this.D=!1;this.h=!0;this.g=this.o?this.o.g():tc.g();this.B=this.o?ac(this.o):ac(tc);this.g.onreadystatechange=x(this.Ka,this);try{this.F=!0,this.g.open(b,String(a),!0),this.F=!1}catch(g){Od(this,g);return}a=c||"";c=new Map(this.headers);if(d)if(Object.getPrototypeOf(d)===Object.prototype)for(var e in d)c.set(e,d[e]);else if("function"===
typeof d.keys&&"function"===typeof d.get){e=t(d.keys());for(var f=e.next();!f.done;f=e.next())f=f.value,c.set(f,d.get(f))}else throw Error("Unknown input type for opt_headers: "+String(d));d=Array.from(c.keys()).find(function(g){return"content-type"==g.toLowerCase()});e=v.FormData&&a instanceof v.FormData;!(0<=ra(Nd,b))||d||e||c.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b=t(c);for(d=b.next();!d.done;d=b.next())c=t(d.value),d=c.next().value,c=c.next().value,this.g.setRequestHeader(d,
c);this.J&&(this.g.responseType=this.J);"withCredentials"in this.g&&this.g.withCredentials!==this.M&&(this.g.withCredentials=this.M);try{Pd(this),0<this.A&&((this.L=Qd(this.g))?(this.g.timeout=this.A,this.g.ontimeout=x(this.ua,this)):this.v=Kb(this.ua,this.A,this)),this.u=!0,this.g.send(a),this.u=!1}catch(g){Od(this,g)}};function Qd(a){return C&&"number"===typeof a.timeout&&void 0!==a.ontimeout}
m.ua=function(){"undefined"!=typeof ma&&this.g&&(this.j="Timed out after "+this.A+"ms, aborting",this.m=8,H(this,"timeout"),this.abort(8))};function Od(a,b){a.h=!1;a.g&&(a.l=!0,a.g.abort(),a.l=!1);a.j=b;a.m=5;Rd(a);Sd(a)}function Rd(a){a.D||(a.D=!0,H(a,"complete"),H(a,"error"))}m.abort=function(a){this.g&&this.h&&(this.h=!1,this.l=!0,this.g.abort(),this.l=!1,this.m=a||7,H(this,"complete"),H(this,"abort"),Sd(this))};
m.N=function(){this.g&&(this.h&&(this.h=!1,this.l=!0,this.g.abort(),this.l=!1),Sd(this,!0));X.Y.N.call(this)};m.Ka=function(){this.s||(this.F||this.u||this.l?Td(this):this.jb())};m.jb=function(){Td(this)};
function Td(a){if(a.h&&"undefined"!=typeof ma&&(!a.B[1]||4!=O(a)||2!=a.da()))if(a.u&&4==O(a))Kb(a.Ka,0,a);else if(H(a,"readystatechange"),4==O(a)){a.h=!1;try{var b=a.da();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=String(a.H).match(jd)[1]||null;!f&&v.self&&v.self.location&&(f=v.self.location.protocol.slice(0,-1));e=!Md.test(f?f.toLowerCase():"")}d=e}if(d)H(a,"complete"),H(a,"success");else{a.m=
6;try{var g=2<O(a)?a.g.statusText:""}catch(h){g=""}a.j=g+" ["+a.da()+"]";Rd(a)}}finally{Sd(a)}}}function Sd(a,b){if(a.g){Pd(a);var c=a.g,d=a.B[0]?function(){}:null;a.g=null;a.B=null;b||H(a,"ready");try{c.onreadystatechange=d}catch(e){}}}function Pd(a){a.g&&a.L&&(a.g.ontimeout=null);a.v&&(v.clearTimeout(a.v),a.v=null)}m.isActive=function(){return!!this.g};function O(a){return a.g?a.g.readyState:0}m.da=function(){try{return 2<O(this)?this.g.status:-1}catch(a){return-1}};
m.ja=function(){try{return this.g?this.g.responseText:""}catch(a){return""}};m.Va=function(a){if(this.g){var b=this.g.responseText;a&&0==b.indexOf(a)&&(b=b.substring(a.length));a:{a=b;if(v.JSON)try{var c=v.JSON.parse(a);break a}catch(d){}c=Sb(a)}return c}};
function Gc(a){try{if(!a.g)return null;if("response"in a.g)return a.g.response;switch(a.J){case "":case "text":return a.g.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in a.g)return a.g.mozResponseArrayBuffer}return null}catch(b){return null}}
function Oc(a){var b={};a=(a.g&&2<=O(a)?a.g.getAllResponseHeaders()||"":"").split("\r\n");for(var c=0;c<a.length;c++)if(!z(a[c])){var d=Ya(a[c]),e=d[0];d=d[1];if("string"===typeof d){d=d.trim();var f=b[e]||[];b[e]=f;f.push(d)}}Ua(b,function(g){return g.join(", ")})}m.Ha=function(){return this.m};m.Ra=function(){return"string"===typeof this.j?this.j:String(this.j)};function Ud(a,b,c){return c&&c.internalChannelParams?c.internalChannelParams[a]||b:b}
function Vd(a){this.Ga=0;this.i=[];this.j=new mc;this.oa=this.wa=this.I=this.aa=this.g=this.Ea=this.D=this.H=this.s=this.V=this.o=null;this.gb=this.X=0;this.cb=Ud("failFast",!1,a);this.F=this.C=this.u=this.m=this.l=null;this.ba=!0;this.Fa=this.W=-1;this.ca=this.v=this.B=0;this.ab=Ud("baseRetryDelayMs",5E3,a);this.lb=Ud("retryDelaySeedMs",1E4,a);this.eb=Ud("forwardChannelMaxRetries",2,a);this.Ca=Ud("forwardChannelRequestTimeoutMs",2E4,a);this.va=a&&a.xmlHttpFactory||void 0;this.fb=a&&a.ec||void 0;
this.Ia=a&&a.useFetchStreams||!1;this.M=void 0;this.J=a&&a.supportsCrossDomainXhr||!1;this.L="";this.h=new dd(a&&a.concurrentRequestLimit);this.Ja=new Dd;this.R=a&&a.fastHandshake||!1;this.P=a&&a.encodeInitMessageHeaders||!1;this.R&&this.P&&(this.P=!1);this.bb=a&&a.cc||!1;a&&a.Da&&this.j.Da();a&&a.forceLongPolling&&(this.ba=!1);this.ma=!this.R&&this.ba&&a&&a.detectBufferingProxy||!1;this.pa=void 0;a&&a.longPollingTimeout&&0<a.longPollingTimeout&&(this.pa=a.longPollingTimeout);this.na=void 0;this.U=
0;this.O=!1;this.qa=this.A=null}m=Vd.prototype;m.ra=8;m.G=1;m.connect=function(a,b,c,d){K(0);this.aa=a;this.H=b||{};c&&void 0!==d&&(this.H.OSID=c,this.H.OAID=d);this.F=this.ba;this.I=Yc(this,null,this.aa);ad(this)};
function bd(a){Wd(a);if(3==a.G){var b=a.X++,c=N(a.I);R(c,"SID",a.L);R(c,"RID",b);R(c,"TYPE","terminate");Xd(a,c);b=new wc(a,a.j,b);b.L=2;b.v=Bc(N(c));c=!1;if(v.navigator&&v.navigator.sendBeacon)try{c=v.navigator.sendBeacon(b.v.toString(),"")}catch(d){}!c&&v.Image&&((new Image).src=b.v,c=!0);c||(b.g=Fc(b.l,null),b.g.ga(b.v));b.F=Date.now();Dc(b)}Yd(a)}function Uc(a){a.g&&(Qc(a),a.g.cancel(),a.g=null)}
function Wd(a){Uc(a);a.u&&(v.clearTimeout(a.u),a.u=null);Tc(a);a.h.cancel();a.m&&("number"===typeof a.m&&v.clearTimeout(a.m),a.m=null)}function ad(a){ed(a.h)||a.m||(a.m=!0,gb(a.Ma,a),a.B=0)}function Zd(a,b){if(Wc(a.h)>=a.h.j-(a.m?1:0))return!1;if(a.m)return a.i=b.D.concat(a.i),!0;if(1==a.G||2==a.G||a.B>=(a.cb?0:a.eb))return!1;a.m=lc(x(a.Ma,a,b),$d(a,a.B));a.B++;return!0}
m.Ma=function(a){if(this.m)if(this.m=null,1==this.G){if(!a){this.X=Math.floor(1E5*Math.random());a=this.X++;var b=new wc(this,this.j,a),c=this.o;this.V&&(c?(c=Va(c),Xa(c,this.V)):c=this.V);null!==this.s||this.P||(b.H=c,c=null);var d;if(this.R)a:{for(var e=d=0;e<this.i.length;e++){b:{var f=this.i[e];if("__data__"in f.map&&(f=f.map.__data__,"string"===typeof f)){f=f.length;break b}f=void 0}if(void 0===f)break;d+=f;if(4096<d){d=e;break a}if(4096===d||e===this.i.length-1){d=e+1;break a}}d=1E3}else d=
1E3;d=ae(this,b,d);e=N(this.I);R(e,"RID",a);R(e,"CVER",22);this.D&&R(e,"X-HTTP-Session-Id",this.D);Xd(this,e);c&&(this.P?d="headers="+encodeURIComponent(String(Kd(c)))+"&"+d:this.s&&Ld(e,this.s,c));Xc(this.h,b);this.bb&&R(e,"TYPE","init");this.R?(R(e,"$req",d),R(e,"SID","null"),b.aa=!0,Ac(b,e,null)):Ac(b,e,d);this.G=2}}else 3==this.G&&(a?be(this,a):0==this.i.length||ed(this.h)||be(this))};
function be(a,b){var c;b?c=b.m:c=a.X++;var d=N(a.I);R(d,"SID",a.L);R(d,"RID",c);R(d,"AID",a.W);Xd(a,d);a.s&&a.o&&Ld(d,a.s,a.o);c=new wc(a,a.j,c,a.B+1);null===a.s&&(c.H=a.o);b&&(a.i=b.D.concat(a.i));b=ae(a,c,1E3);c.setTimeout(Math.round(.5*a.Ca)+Math.round(.5*a.Ca*Math.random()));Xc(a.h,c);Ac(c,d,b)}function Xd(a,b){a.H&&Ta(a.H,function(c,d){R(b,d,c)});a.l&&id({},function(c,d){R(b,d,c)})}
function ae(a,b,c){c=Math.min(a.i.length,c);var d=a.l?x(a.l.Ua,a.l,a):null;a:for(var e=a.i,f=-1;;){var g=["count="+c];-1==f?0<c?(f=e[0].g,g.push("ofs="+f)):f=0:g.push("ofs="+f);for(var h=!0,k=0;k<c;k++){var l=e[k].g,n=e[k].map;l-=f;if(0>l)f=Math.max(0,e[k].g-100),h=!1;else try{Ed(n,g,"req"+l+"_")}catch(q){d&&d(n)}}if(h){d=g.join("&");break a}}a=a.i.splice(0,c);b.D=a;return d}function $c(a){a.g||a.u||(a.ca=1,gb(a.La,a),a.v=0)}
function Vc(a){if(a.g||a.u||3<=a.v)return!1;a.ca++;a.u=lc(x(a.La,a),$d(a,a.v));a.v++;return!0}m.La=function(){this.u=null;ce(this);if(this.ma&&!(this.O||null==this.g||0>=this.U)){var a=2*this.U;this.j.info("BP detection timer enabled: "+a);this.A=lc(x(this.ib,this),a)}};m.ib=function(){this.A&&(this.A=null,this.j.info("BP detection timeout reached."),this.j.info("Buffering proxy detected and switch to long-polling!"),this.F=!1,this.O=!0,K(10),Uc(this),ce(this))};
function Qc(a){null!=a.A&&(v.clearTimeout(a.A),a.A=null)}function ce(a){a.g=new wc(a,a.j,"rpc",a.ca);null===a.s&&(a.g.H=a.o);a.g.O=0;var b=N(a.wa);R(b,"RID","rpc");R(b,"SID",a.L);R(b,"AID",a.W);R(b,"CI",a.F?"0":"1");!a.F&&a.pa&&R(b,"TO",a.pa);R(b,"TYPE","xmlhttp");Xd(a,b);a.s&&a.o&&Ld(b,a.s,a.o);a.M&&a.g.setTimeout(a.M);var c=a.g;a=a.oa;c.L=1;c.v=Bc(N(b));c.u=null;c.R=!0;Cc(c,a)}m.hb=function(){null!=this.C&&(this.C=null,Uc(this),Vc(this),K(19))};
function Tc(a){null!=a.C&&(v.clearTimeout(a.C),a.C=null)}function Nc(a,b){var c=null;if(a.g==b){Tc(a);Qc(a);a.g=null;var d=2}else if(Sc(a.h,b))c=b.D,Zc(a.h,b),d=1;else return;if(0!=a.G)if(b.i)if(1==d){c=b.u?b.u.length:0;b=Date.now()-b.F;var e=a.B;d=gc();H(d,new kc(d,c,b,e));ad(a)}else $c(a);else if(e=b.o,3==e||0==e&&0<b.ca||!(1==d&&Zd(a,b)||2==d&&Vc(a)))switch(c&&0<c.length&&(b=a.h,b.i=b.i.concat(c)),e){case 1:Q(a,5);break;case 4:Q(a,10);break;case 3:Q(a,6);break;default:Q(a,2)}}
function $d(a,b){var c=a.ab+Math.floor(Math.random()*a.lb);a.isActive()||(c*=2);return c*b}function Q(a,b){a.j.info("Error code "+b);if(2==b){var c=x(a.pb,a),d=a.fb,e=!d;d=new S(d||"//www.google.com/images/cleardot.gif");v.location&&"http"==v.location.protocol||ld(d,"https");Bc(d);e?Bd(d.toString(),c):Cd(d.toString(),c)}else K(2);a.G=0;a.l&&a.l.ya(b);Yd(a);Wd(a)}m.pb=function(a){a?(this.j.info("Successfully pinged google.com"),K(2)):(this.j.info("Failed to ping google.com"),K(1))};
function Yd(a){a.G=0;a.qa=[];if(a.l){var b=fd(a.h);if(0!=b.length||0!=a.i.length)ta(a.qa,b),ta(a.qa,a.i),a.h.i.length=0,sa(a.i),a.i.length=0;a.l.xa()}}function Yc(a,b,c){var d=c instanceof S?N(c):new S(c);if(""!=d.g)b&&(d.g=b+"."+d.g),md(d,d.s);else{var e=v.location;d=e.protocol;b=b?b+"."+e.hostname:e.hostname;e=+e.port;var f=new S(null);d&&ld(f,d);b&&(f.g=b);e&&md(f,e);c&&(f.h=c);d=f}c=a.D;b=a.Ea;c&&b&&R(d,c,b);R(d,"VER",a.ra);Xd(a,d);return d}
function Fc(a,b,c){if(b&&!a.J)throw Error("Can't create secondary domain capable XhrIo object.");b=a.Ia&&!a.va?new X(new Fd({ob:c})):new X(a.va);b.Na(a.J);return b}m.isActive=function(){return!!this.l&&this.l.isActive(this)};function de(){}m=de.prototype;m.Aa=function(){};m.za=function(){};m.ya=function(){};m.xa=function(){};m.isActive=function(){return!0};m.Ua=function(){};function ee(){if(C&&!(10<=Number(Sa)))throw Error("Environmental error: no available transport.");}ee.prototype.g=function(a,b){return new Y(a,b)};
function Y(a,b){G.call(this);this.g=new Vd(b);this.l=a;this.h=b&&b.messageUrlParams||null;a=b&&b.messageHeaders||null;b&&b.clientProtocolHeaderRequired&&(a?a["X-Client-Protocol"]="webchannel":a={"X-Client-Protocol":"webchannel"});this.g.o=a;a=b&&b.initMessageHeaders||null;b&&b.messageContentType&&(a?a["X-WebChannel-Content-Type"]=b.messageContentType:a={"X-WebChannel-Content-Type":b.messageContentType});b&&b.Ba&&(a?a["X-WebChannel-Client-Profile"]=b.Ba:a={"X-WebChannel-Client-Profile":b.Ba});this.g.V=
a;(a=b&&b.dc)&&!z(a)&&(this.g.s=a);this.v=b&&b.supportsCrossDomainXhr||!1;this.u=b&&b.sendRawJson||!1;(b=b&&b.httpSessionIdParam)&&!z(b)&&(this.g.D=b,a=this.h,null!==a&&b in a&&(a=this.h,b in a&&delete a[b]));this.j=new Z(this)}y(Y,G);Y.prototype.m=function(){this.g.l=this.j;this.v&&(this.g.J=!0);this.g.connect(this.l,this.h||void 0)};Y.prototype.close=function(){bd(this.g)};
Y.prototype.o=function(a){var b=this.g;if("string"===typeof a){var c={};c.__data__=a;a=c}else this.u&&(c={},c.__data__=Tb(a),a=c);b.i.push(new cd(b.gb++,a));3==b.G&&ad(b)};Y.prototype.N=function(){this.g.l=null;delete this.j;bd(this.g);delete this.g;Y.Y.N.call(this)};
function fe(a){dc.call(this);a.__headers__&&(this.headers=a.__headers__,this.statusCode=a.__status__,delete a.__headers__,delete a.__status__);var b=a.__sm__;if(b){a:{for(var c in b){a=c;break a}a=void 0}if(this.i=a)a=this.i,b=null!==b&&a in b?b[a]:void 0;this.data=b}else this.data=a}y(fe,dc);function ge(){ec.call(this);this.status=1}y(ge,ec);function Z(a){this.g=a}y(Z,de);Z.prototype.Aa=function(){H(this.g,"a")};Z.prototype.za=function(a){H(this.g,new fe(a))};
Z.prototype.ya=function(a){H(this.g,new ge(a))};Z.prototype.xa=function(){H(this.g,"b")};ee.prototype.createWebChannel=ee.prototype.g;Y.prototype.send=Y.prototype.o;Y.prototype.open=Y.prototype.m;Y.prototype.close=Y.prototype.close;module.exports.createWebChannelTransport=function(){return new ee};module.exports.getStatEventTarget=function(){return gc()};module.exports.Event=J;module.exports.Stat={xb:0,Ab:1,Bb:2,Ub:3,Zb:4,Wb:5,Xb:6,Vb:7,Tb:8,Yb:9,PROXY:10,NOPROXY:11,Rb:12,Nb:13,Ob:14,Mb:15,Pb:16,Qb:17,tb:18,sb:19,ub:20};rc.NO_ERROR=0;rc.TIMEOUT=8;rc.HTTP_ERROR=6;
module.exports.ErrorCode=rc;sc.COMPLETE="complete";module.exports.EventType=sc;bc.EventType=cc;cc.OPEN="a";cc.CLOSE="b";cc.ERROR="c";cc.MESSAGE="d";G.prototype.listen=G.prototype.O;module.exports.WebChannel=bc;module.exports.FetchXmlHttpFactory=Fd;X.prototype.listenOnce=X.prototype.P;X.prototype.getLastError=X.prototype.Ra;X.prototype.getLastErrorCode=X.prototype.Ha;X.prototype.getStatus=X.prototype.da;X.prototype.getResponseJson=X.prototype.Va;X.prototype.getResponseText=X.prototype.ja;
X.prototype.send=X.prototype.ga;X.prototype.setWithCredentials=X.prototype.Na;module.exports.XhrIo=X;}).apply( typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self  : typeof window !== 'undefined' ? window  : {});
