/** @license
Copyright The Closure Library Authors.
SPDX-License-Identifier: Apache-2.0
*/
(function() {'use strict';var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var p=ca(this);function q(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
q("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=p[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
var ea=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;if(typeof Object.setPrototypeOf=="function")fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function t(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}
q("Promise",function(a){function b(g){this.g=0;this.i=void 0;this.h=[];this.s=!1;var h=this.j();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(this.g==null){this.g=[];var h=this;this.i(function(){h.l()})}this.g.push(g)};var e=p.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(l){this.j(l)}}}this.g=null};c.prototype.j=function(g){this.i(function(){throw g;})};b.prototype.j=function(){function g(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:g(this.A),reject:g(this.l)}};b.prototype.A=function(g){if(g===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.F(g);else{a:switch(typeof g){case "object":var h=g!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.v(g):this.m(g)}};
b.prototype.v=function(g){var h=void 0;try{h=g.then}catch(k){this.l(k);return}typeof h=="function"?this.D(h,g):this.m(g)};b.prototype.l=function(g){this.o(2,g)};b.prototype.m=function(g){this.o(1,g)};b.prototype.o=function(g,h){if(this.g!=0)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.g);this.g=g;this.i=h;this.g===2&&this.B();this.u()};b.prototype.B=function(){var g=this;e(function(){if(g.C()){var h=p.console;typeof h!=="undefined"&&h.error(g.i)}},1)};b.prototype.C=
function(){if(this.s)return!1;var g=p.CustomEvent,h=p.Event,k=p.dispatchEvent;if(typeof k==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof h==="function"?g=new h("unhandledrejection",{cancelable:!0}):(g=p.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return k(g)};b.prototype.u=function(){if(this.h!=null){for(var g=0;g<this.h.length;++g)f.h(this.h[g]);this.h=null}};var f=new c;b.prototype.F=
function(g){var h=this.j();g.ia(h.resolve,h.reject)};b.prototype.D=function(g,h){var k=this.j();try{g.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(g,h){function k(A,E){return typeof A=="function"?function(J){try{l(A(J))}catch(T){m(T)}}:E}var l,m,r=new b(function(A,E){l=A;m=E});this.ia(k(g,l),k(h,m));return r};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.ia=function(g,h){function k(){switch(l.g){case 1:g(l.i);break;case 2:h(l.i);break;default:throw Error("Unexpected state: "+
l.g);}}var l=this;this.h==null?f.h(k):this.h.push(k);this.s=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var l=t(g),m=l.next();!m.done;m=l.next())d(m.value).ia(h,k)})};b.all=function(g){var h=t(g),k=h.next();return k.done?d([]):new b(function(l,m){function r(J){return function(T){A[J]=T;E--;E==0&&l(A)}}var A=[],E=0;do A.push(void 0),E++,d(k.value).ia(r(A.length-1),m),k=h.next();while(!k.done)})};return b});
function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}q("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});
q("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=t(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return l==="object"&&k!==null||l==="function"}function e(k){if(!u(k,g)){var l=new c;ba(k,g,{value:l})}}function f(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(m.get(k)!=2||m.get(l)!=3)return!1;m.delete(k);m.set(l,4);return!m.has(k)&&m.get(l)==4}catch(r){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,g))throw Error("WeakMap key fail: "+k);k[g][this.g]=l;return this};b.prototype.get=function(k){return d(k)&&u(k,g)?k[g][this.g]:void 0};b.prototype.has=function(k){return d(k)&&u(k,
g)&&u(k[g],this.g)};b.prototype.delete=function(k){return d(k)&&u(k,g)&&u(k[g],this.g)?delete k[g][this.g]:!1};return b});
q("Map",function(a){function b(){var h={};return h.P=h.next=h.head=h}function c(h,k){var l=h[1];return da(function(){if(l){for(;l.head!=h[1];)l=l.P;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(h,k){var l=k&&typeof k;l=="object"||l=="function"?f.has(k)?l=f.get(k):(l=""+ ++g,f.set(k,l)):l="p_"+k;var m=h[0][l];if(m&&u(h[0],l))for(h=0;h<m.length;h++){var r=m[h];if(k!==k&&r.key!==r.key||k===r.key)return{id:l,list:m,index:h,I:r}}return{id:l,
list:m,index:-1,I:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=t(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(t([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=h||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(r){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var l=d(this,h);l.list||(l.list=this[0][l.id]=[]);l.I?l.I.value=k:(l.I={next:this[1],P:this[1].P,head:this[1],key:h,value:k},l.list.push(l.I),this[1].P.next=l.I,this[1].P=l.I,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.I&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],h.I.P.next=h.I.next,h.I.next.P=h.I.P,h.I.head=
null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].P=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).I};e.prototype.get=function(h){return(h=d(this,h).I)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=
m.value,h.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
q("Set",function(a){function b(c){this.g=new Map;if(c){c=t(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var c=Object.seal({x:4}),d=new a(t([c]));if(!d.has(c)||d.size!=1||d.add(c)!=d||d.size!=1||d.add({x:4})!=d||d.size!=2)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||f.value[0].x!=4||
f.value[1]!=f.value[0]?!1:e.next().done}catch(g){return!1}}())return a;b.prototype.add=function(c){c=c===0?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.g.forEach(function(f){return c.call(d,f,f,e)})};return b});q("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});
function la(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}q("Array.prototype.values",function(a){return a?a:function(){return la(this,function(b,c){return c})}});q("Array.prototype.keys",function(a){return a?a:function(){return la(this,function(b){return b})}});
q("Array.prototype.entries",function(a){return a?a:function(){return la(this,function(b,c){return[b,c]})}});q("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});/** @license

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ma=ma||{},v=this||self;function na(a){var b=typeof a;b=b!="object"?b:a?Array.isArray(a)?"array":b:"null";return b=="array"||b=="object"&&typeof a.length=="number"}function w(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}function oa(a,b,c){return a.call.apply(a.bind,arguments)}
function pa(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function x(a,b,c){x=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?oa:pa;return x.apply(null,arguments)}
function qa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}function y(a,b){function c(){}c.prototype=b.prototype;a.Y=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Sb=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};var ra=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};var sa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};function ta(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function ua(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(na(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}};function va(a,b){this.i=a;this.j=b;this.h=0;this.g=null}va.prototype.get=function(){if(this.h>0){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.i();return a};function wa(a){v.setTimeout(function(){throw a;},0)};function xa(){this.h=this.g=null}xa.prototype.add=function(a,b){var c=ya.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c};function za(){var a=Aa,b=null;a.g&&(b=a.g,a.g=a.g.next,a.g||(a.h=null),b.next=null);return b}var ya=new va(function(){return new Ba},function(a){return a.reset()});function Ba(){this.next=this.g=this.h=null}Ba.prototype.set=function(a,b){this.h=a;this.g=b;this.next=null};Ba.prototype.reset=function(){this.next=this.g=this.h=null};var Ca,Da=!1,Aa=new xa;function Ea(a,b){Ca||Fa();Da||(Ca(),Da=!0);Aa.add(a,b)}function Fa(){var a=Promise.resolve(void 0);Ca=function(){a.then(Ga)}}function Ga(){for(var a;a=za();){try{a.h.call(a.g)}catch(c){wa(c)}var b=ya;b.j(a);b.h<100&&(b.h++,a.next=b.g,b.g=a)}Da=!1};function z(){this.s=this.s;this.C=this.C}z.prototype.s=!1;z.prototype.dispose=function(){this.s||(this.s=!0,this.N())};z.prototype[Symbol.dispose]=function(){this.dispose()};z.prototype.N=function(){if(this.C)for(;this.C.length;)this.C.shift()()};function B(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1}B.prototype.h=function(){this.defaultPrevented=!0};var Ha=function(){if(!v.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};v.addEventListener("test",c,b);v.removeEventListener("test",c,b)}catch(d){}return a}();function Ia(a){return/^[\s\xa0]*$/.test(a)};function C(a,b){B.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.i=null;a&&this.init(a,b)}y(C,B);
C.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;b=a.relatedTarget;b||(c=="mouseover"?b=a.fromElement:c=="mouseout"&&(b=a.toElement));this.relatedTarget=b;d?(this.clientX=d.clientX!==void 0?d.clientX:d.pageX,this.clientY=d.clientY!==void 0?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=a.clientX!==void 0?a.clientX:a.pageX,this.clientY=a.clientY!==
void 0?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=a.pointerType;this.state=a.state;this.i=a;a.defaultPrevented&&C.Y.h.call(this)};C.prototype.h=function(){C.Y.h.call(this);var a=this.i;a.preventDefault?a.preventDefault():a.returnValue=!1};var Ja="closure_listenable_"+(Math.random()*1E6|0);var Ka=0;function La(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.ka=e;this.key=++Ka;this.fa=this.ha=!1}function Ma(a){a.fa=!0;a.listener=null;a.proxy=null;a.src=null;a.ka=null};function Na(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Oa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function Pa(a){var b={},c;for(c in a)b[c]=a[c];return b}var Qa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ra(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Qa.length;f++)c=Qa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Sa(a){this.src=a;this.g={};this.h=0}Sa.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);var g=Ta(a,b,d,e);g>-1?(b=a[g],c||(b.ha=!1)):(b=new La(b,this.src,f,!!d,e),b.ha=c,a.push(b));return b};function Ua(a,b){var c=b.type;if(c in a.g){var d=a.g[c],e=sa(d,b),f;(f=e>=0)&&Array.prototype.splice.call(d,e,1);f&&(Ma(b),a.g[c].length==0&&(delete a.g[c],a.h--))}}
function Ta(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.fa&&f.listener==b&&f.capture==!!c&&f.ka==d)return e}return-1};var Va="closure_lm_"+(Math.random()*1E6|0),Wa={},Xa=0;function Ya(a,b,c,d,e){if(d&&d.once)return Za(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)Ya(a,b[f],c,d,e);return null}c=$a(c);return a&&a[Ja]?a.J(b,c,w(d)?!!d.capture:!!d,e):ab(a,b,c,!1,d,e)}
function ab(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=w(e)?!!e.capture:!!e,h=bb(a);h||(a[Va]=h=new Sa(a));c=h.add(b,c,d,g,f);if(c.proxy)return c;d=cb();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)Ha||(e=g),e===void 0&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(db(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Xa++;return c}
function cb(){function a(c){return b.call(a.src,a.listener,c)}var b=eb;return a}function Za(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)Za(a,b[f],c,d,e);return null}c=$a(c);return a&&a[Ja]?a.K(b,c,w(d)?!!d.capture:!!d,e):ab(a,b,c,!0,d,e)}
function fb(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)fb(a,b[f],c,d,e);else(d=w(d)?!!d.capture:!!d,c=$a(c),a&&a[Ja])?(a=a.i,b=String(b).toString(),b in a.g&&(f=a.g[b],c=Ta(f,c,d,e),c>-1&&(Ma(f[c]),Array.prototype.splice.call(f,c,1),f.length==0&&(delete a.g[b],a.h--)))):a&&(a=bb(a))&&(b=a.g[b.toString()],a=-1,b&&(a=Ta(b,c,d,e)),(c=a>-1?b[a]:null)&&gb(c))}
function gb(a){if(typeof a!=="number"&&a&&!a.fa){var b=a.src;if(b&&b[Ja])Ua(b.i,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(db(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Xa--;(c=bb(b))?(Ua(c,a),c.h==0&&(c.src=null,b[Va]=null)):Ma(a)}}}function db(a){return a in Wa?Wa[a]:Wa[a]="on"+a}function eb(a,b){if(a.fa)a=!0;else{b=new C(b,this);var c=a.listener,d=a.ka||a.src;a.ha&&gb(a);a=c.call(d,b)}return a}
function bb(a){a=a[Va];return a instanceof Sa?a:null}var hb="__closure_events_fn_"+(Math.random()*1E9>>>0);function $a(a){if(typeof a==="function")return a;a[hb]||(a[hb]=function(b){return a.handleEvent(b)});return a[hb]};function D(){z.call(this);this.i=new Sa(this);this.M=this;this.F=null}y(D,z);D.prototype[Ja]=!0;D.prototype.removeEventListener=function(a,b,c,d){fb(this,a,b,c,d)};
function F(a,b){var c,d=a.F;if(d)for(c=[];d;d=d.F)c.push(d);a=a.M;d=b.type||b;if(typeof b==="string")b=new B(b,a);else if(b instanceof B)b.target=b.target||a;else{var e=b;b=new B(d,a);Ra(b,e)}e=!0;var f;if(c)for(f=c.length-1;f>=0;f--){var g=b.g=c[f];e=ib(g,d,!0,b)&&e}g=b.g=a;e=ib(g,d,!0,b)&&e;e=ib(g,d,!1,b)&&e;if(c)for(f=0;f<c.length;f++)g=b.g=c[f],e=ib(g,d,!1,b)&&e}
D.prototype.N=function(){D.Y.N.call(this);if(this.i){var a=this.i,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,Ma(d[e]);delete a.g[c];a.h--}}this.F=null};D.prototype.J=function(a,b,c,d){return this.i.add(String(a),b,!1,c,d)};D.prototype.K=function(a,b,c,d){return this.i.add(String(a),b,!0,c,d)};
function ib(a,b,c,d){b=a.i.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.fa&&g.capture==c){var h=g.listener,k=g.ka||g.src;g.ha&&Ua(a.i,g);e=h.call(k,d)!==!1&&e}}return e&&!d.defaultPrevented};function jb(a,b){if(typeof a!=="function")if(a&&typeof a.handleEvent=="function")a=x(a.handleEvent,a);else throw Error("Invalid listener argument");return Number(b)>2147483647?-1:v.setTimeout(a,b||0)};function G(a,b,c){z.call(this);this.m=c!=null?a.bind(c):a;this.l=b;this.h=null;this.i=!1;this.g=null}G.prototype=ea(z.prototype);G.prototype.constructor=G;if(ka)ka(G,z);else for(var kb in z)if(kb!="prototype")if(Object.defineProperties){var lb=Object.getOwnPropertyDescriptor(z,kb);lb&&Object.defineProperty(G,kb,lb)}else G[kb]=z[kb];G.Y=z.prototype;G.prototype.j=function(a){this.h=arguments;this.g?this.i=!0:mb(this)};
G.prototype.N=function(){z.prototype.N.call(this);this.g&&(v.clearTimeout(this.g),this.g=null,this.i=!1,this.h=null)};function mb(a){a.g=jb(function(){a.g=null;a.i&&(a.i=!1,mb(a))},a.l);var b=a.h;a.h=null;a.m.apply(null,b)};function nb(a){z.call(this);this.h=a;this.g={}}y(nb,z);var ob=[];function pb(a){Na(a.g,function(b,c){this.g.hasOwnProperty(c)&&gb(b)},a);a.g={}}nb.prototype.N=function(){nb.Y.N.call(this);pb(this)};nb.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var qb=v.JSON.stringify;var rb=v.JSON.parse;function sb(){}sb.prototype.stringify=function(a){return v.JSON.stringify(a,void 0)};sb.prototype.parse=function(a){return v.JSON.parse(a,void 0)};function tb(){};function ub(){}var vb={OPEN:"a",mb:"b",La:"c",yb:"d"};function wb(){B.call(this,"d")}y(wb,B);function xb(){B.call(this,"c")}y(xb,B);var H={},yb=null;function zb(){return yb=yb||new D}H.Na="serverreachability";function Ab(a){B.call(this,H.Na,a)}y(Ab,B);function Bb(a){var b=zb();F(b,new Ab(b,a))}H.STAT_EVENT="statevent";function Cb(a,b){B.call(this,H.STAT_EVENT,a);this.stat=b}y(Cb,B);function I(a){var b=zb();F(b,new Cb(b,a))}H.Oa="timingevent";function Db(a,b){B.call(this,H.Oa,a);this.size=b}y(Db,B);
function Eb(a,b){if(typeof a!=="function")throw Error("Fn must not be null and must be a function");return v.setTimeout(function(){a()},b)};function Fb(){this.g=!0}Fb.prototype.za=function(){this.g=!1};function Gb(a,b,c,d,e,f){a.info(function(){if(a.g)if(f){var g="";for(var h=f.split("&"),k=0;k<h.length;k++){var l=h[k].split("=");if(l.length>1){var m=l[0];l=l[1];var r=m.split("_");g=r.length>=2&&r[1]=="type"?g+(m+"="+l+"&"):g+(m+"=redacted&")}}}else g=null;else g=f;return"XMLHTTP REQ ("+d+") [attempt "+e+"]: "+b+"\n"+c+"\n"+g})}
function Hb(a,b,c,d,e,f,g){a.info(function(){return"XMLHTTP RESP ("+d+") [ attempt "+e+"]: "+b+"\n"+c+"\n"+f+" "+g})}function K(a,b,c,d){a.info(function(){return"XMLHTTP TEXT ("+b+"): "+Ib(a,c)+(d?" "+d:"")})}function Jb(a,b){a.info(function(){return"TIMEOUT: "+b})}Fb.prototype.info=function(){};
function Ib(a,b){if(!a.g)return b;if(!b)return null;try{var c=JSON.parse(b);if(c)for(a=0;a<c.length;a++)if(Array.isArray(c[a])){var d=c[a];if(!(d.length<2)){var e=d[1];if(Array.isArray(e)&&!(e.length<1)){var f=e[0];if(f!="noop"&&f!="stop"&&f!="close")for(var g=1;g<e.length;g++)e[g]=""}}}return qb(c)}catch(h){return b}};var Kb={NO_ERROR:0,ib:1,vb:2,ub:3,pb:4,tb:5,wb:6,Ka:7,TIMEOUT:8,zb:9};var Lb={nb:"complete",Jb:"success",La:"error",Ka:"abort",Bb:"ready",Cb:"readystatechange",TIMEOUT:"timeout",xb:"incrementaldata",Ab:"progress",qb:"downloadprogress",Rb:"uploadprogress"};var Mb;function Nb(){}y(Nb,tb);Nb.prototype.g=function(){return new XMLHttpRequest};Mb=new Nb;function L(a){return encodeURIComponent(String(a))}function Ob(a){var b=1;a=a.split(":");for(var c=[];b>0&&a.length;)c.push(a.shift()),b--;a.length&&c.push(a.join(":"));return c};function M(a,b,c,d){this.j=a;this.i=b;this.l=c;this.T=d||1;this.W=new nb(this);this.H=45E3;this.J=null;this.o=!1;this.s=this.A=this.v=this.M=this.D=this.U=this.B=null;this.F=[];this.g=null;this.C=0;this.m=this.u=null;this.aa=-1;this.K=!1;this.R=0;this.O=null;this.Z=this.L=this.V=this.S=!1;this.h=new Pb}function Pb(){this.i=null;this.g="";this.h=!1}var Qb={},Rb={};function Sb(a,b,c){a.M=1;a.v=Tb(N(b));a.s=c;a.S=!0;Ub(a,null)}
function Ub(a,b){a.D=Date.now();Vb(a);a.A=N(a.v);var c=a.A,d=a.T;Array.isArray(d)||(d=[String(d)]);Wb(c.i,"t",d);a.C=0;c=a.j.K;a.h=new Pb;a.g=Xb(a.j,c?b:null,!a.s);a.R>0&&(a.O=new G(x(a.ba,a,a.g),a.R));b=a.W;c=a.g;d=a.da;var e="readystatechange";Array.isArray(e)||(e&&(ob[0]=e.toString()),e=ob);for(var f=0;f<e.length;f++){var g=Ya(c,e[f],d||b.handleEvent,!1,b.h||b);if(!g)break;b.g[g.key]=g}b=a.J?Pa(a.J):{};a.s?(a.u||(a.u="POST"),b["Content-Type"]="application/x-www-form-urlencoded",a.g.ga(a.A,a.u,
a.s,b)):(a.u="GET",a.g.ga(a.A,a.u,null,b));Bb(1);Gb(a.i,a.u,a.A,a.l,a.T,a.s)}M.prototype.da=function(a){a=a.target;var b=this.O;b&&O(a)==3?b.j():this.ba(a)};
M.prototype.ba=function(a){try{if(a==this.g)a:{var b=O(this.g),c=this.g.Da(),d=this.g.ea();if(!(b<3)&&(b!=3||this.g&&(this.h.h||this.g.qa()||Yb(this.g)))){this.K||b!=4||c==7||(c==8||d<=0?Bb(3):Bb(2));Zb(this);var e=this.g.ea();this.aa=e;var f=$b(this);this.o=e==200;Hb(this.i,this.u,this.A,this.l,this.T,b,e);if(this.o){if(this.V&&!this.L){b:{if(this.g){var g,h=this.g;if((g=h.g?h.g.getResponseHeader("X-HTTP-Initial-Response"):null)&&!Ia(g)){var k=g;break b}}k=null}if(a=k)K(this.i,this.l,a,"Initial handshake response via X-HTTP-Initial-Response"),
this.L=!0,ac(this,a);else{this.o=!1;this.m=3;I(12);P(this);bc(this);break a}}if(this.S){a=!0;for(var l;!this.K&&this.C<f.length;)if(l=cc(this,f),l==Rb){b==4&&(this.m=4,I(14),a=!1);K(this.i,this.l,null,"[Incomplete Response]");break}else if(l==Qb){this.m=4;I(15);K(this.i,this.l,f,"[Invalid Chunk]");a=!1;break}else K(this.i,this.l,l,null),ac(this,l);dc(this)&&this.C!=0&&(this.h.g=this.h.g.slice(this.C),this.C=0);b!=4||f.length!=0||this.h.h||(this.m=1,I(16),a=!1);this.o=this.o&&a;if(!a)K(this.i,this.l,
f,"[Invalid Chunked Response]"),P(this),bc(this);else if(f.length>0&&!this.Z){this.Z=!0;var m=this.j;m.g==this&&m.ca&&!m.O&&(m.j.info("Great, no buffering proxy detected. Bytes received: "+f.length),fc(m),m.O=!0,I(11))}}else K(this.i,this.l,f,null),ac(this,f);b==4&&P(this);this.o&&!this.K&&(b==4?gc(this.j,this):(this.o=!1,Vb(this)))}else hc(this.g),e==400&&f.indexOf("Unknown SID")>0?(this.m=3,I(12)):(this.m=0,I(13)),P(this),bc(this)}}}catch(r){}finally{}};
function $b(a){if(!dc(a))return a.g.qa();var b=Yb(a.g);if(b==="")return"";var c="",d=b.length,e=O(a.g)==4;if(!a.h.i){if(typeof TextDecoder==="undefined")return P(a),bc(a),"";a.h.i=new v.TextDecoder}for(var f=0;f<d;f++)a.h.h=!0,c+=a.h.i.decode(b[f],{stream:!(e&&f==d-1)});b.length=0;a.h.g+=c;a.C=0;return a.h.g}function dc(a){return a.g?a.u=="GET"&&a.M!=2&&a.j.Ea:!1}
function cc(a,b){var c=a.C,d=b.indexOf("\n",c);if(d==-1)return Rb;c=Number(b.substring(c,d));if(isNaN(c))return Qb;d+=1;if(d+c>b.length)return Rb;b=b.slice(d,d+c);a.C=d+c;return b}M.prototype.cancel=function(){this.K=!0;P(this)};function Vb(a){a.U=Date.now()+a.H;ic(a,a.H)}function ic(a,b){if(a.B!=null)throw Error("WatchDog timer not null");a.B=Eb(x(a.ca,a),b)}function Zb(a){a.B&&(v.clearTimeout(a.B),a.B=null)}
M.prototype.ca=function(){this.B=null;var a=Date.now();a-this.U>=0?(Jb(this.i,this.A),this.M!=2&&(Bb(3),I(17)),P(this),this.m=2,bc(this)):ic(this,this.U-a)};function bc(a){a.j.G==0||a.K||gc(a.j,a)}function P(a){Zb(a);var b=a.O;b&&typeof b.dispose=="function"&&b.dispose();a.O=null;pb(a.W);a.g&&(b=a.g,a.g=null,b.abort(),b.dispose())}
function ac(a,b){try{var c=a.j;if(c.G!=0&&(c.g==a||jc(c.h,a)))if(!a.L&&jc(c.h,a)&&c.G==3){try{var d=c.Fa.g.parse(b)}catch(ec){d=null}if(Array.isArray(d)&&d.length==3){var e=d;if(e[0]==0)a:{if(!c.u){if(c.g)if(c.g.D+3E3<a.D)kc(c),lc(c);else break a;mc(c);I(18)}}else c.Ba=e[1],0<c.Ba-c.V&&e[2]<37500&&c.D&&c.v==0&&!c.C&&(c.C=Eb(x(c.bb,c),6E3));if(nc(c.h)<=1&&c.da){try{c.da()}catch(ec){}c.da=void 0}}else Q(c,11)}else if((a.L||c.g==a)&&kc(c),!Ia(b))for(e=c.Fa.g.parse(b),b=0;b<e.length;b++){var f=e[b];c.V=
f[0];f=f[1];if(c.G==2)if(f[0]=="c"){c.L=f[1];c.la=f[2];var g=f[3];g!=null&&(c.oa=g,c.j.info("VER="+c.oa));var h=f[4];h!=null&&(c.Ca=h,c.j.info("SVER="+c.Ca));var k=f[5];k!=null&&typeof k==="number"&&k>0&&(d=1.5*k,c.M=d,c.j.info("backChannelRequestTimeoutMs_="+d));d=c;var l=a.g;if(l){var m=l.g?l.g.getResponseHeader("X-Client-Wire-Protocol"):null;if(m){var r=d.h;r.g||m.indexOf("spdy")==-1&&m.indexOf("quic")==-1&&m.indexOf("h2")==-1||(r.j=r.l,r.g=new Set,r.h&&(oc(r,r.h),r.h=null))}if(d.F){var A=l.g?
l.g.getResponseHeader("X-HTTP-Session-Id"):null;A&&(d.Aa=A,R(d.J,d.F,A))}}c.G=3;c.l&&c.l.wa();c.ca&&(c.T=Date.now()-a.D,c.j.info("Handshake RTT: "+c.T+"ms"));d=c;var E=a;d.sa=pc(d,d.K?d.la:null,d.Z);if(E.L){qc(d.h,E);var J=E,T=d.M;T&&(J.H=T);J.B&&(Zb(J),Vb(J));d.g=E}else rc(d);c.i.length>0&&sc(c)}else f[0]!="stop"&&f[0]!="close"||Q(c,7);else c.G==3&&(f[0]=="stop"||f[0]=="close"?f[0]=="stop"?Q(c,7):tc(c):f[0]!="noop"&&c.l&&c.l.va(f),c.v=0)}Bb(4)}catch(ec){}};function uc(a,b){this.g=a;this.map=b};function vc(a){this.l=a||10;v.PerformanceNavigationTiming?(a=v.performance.getEntriesByType("navigation"),a=a.length>0&&(a[0].nextHopProtocol=="hq"||a[0].nextHopProtocol=="h2")):a=!!(v.chrome&&v.chrome.loadTimes&&v.chrome.loadTimes()&&v.chrome.loadTimes().wasFetchedViaSpdy);this.j=a?this.l:1;this.g=null;this.j>1&&(this.g=new Set);this.h=null;this.i=[]}function wc(a){return a.h?!0:a.g?a.g.size>=a.j:!1}function nc(a){return a.h?1:a.g?a.g.size:0}function jc(a,b){return a.h?a.h==b:a.g?a.g.has(b):!1}
function oc(a,b){a.g?a.g.add(b):a.h=b}function qc(a,b){a.h&&a.h==b?a.h=null:a.g&&a.g.has(b)&&a.g.delete(b)}vc.prototype.cancel=function(){this.i=xc(this);if(this.h)this.h.cancel(),this.h=null;else if(this.g&&this.g.size!==0){for(var a=t(this.g.values()),b=a.next();!b.done;b=a.next())b.value.cancel();this.g.clear()}};
function xc(a){if(a.h!=null)return a.i.concat(a.h.F);if(a.g!=null&&a.g.size!==0){var b=a.i;a=t(a.g.values());for(var c=a.next();!c.done;c=a.next())b=b.concat(c.value.F);return b}return ta(a.i)};function yc(a){if(a.X&&typeof a.X=="function")return a.X();if(typeof Map!=="undefined"&&a instanceof Map||typeof Set!=="undefined"&&a instanceof Set)return Array.from(a.values());if(typeof a==="string")return a.split("");if(na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function zc(a){if(a.pa&&typeof a.pa=="function")return a.pa();if(!a.X||typeof a.X!="function"){if(typeof Map!=="undefined"&&a instanceof Map)return Array.from(a.keys());if(!(typeof Set!=="undefined"&&a instanceof Set)){if(na(a)||typeof a==="string"){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}b=[];c=0;for(var d in a)b[c++]=d;return b}}}
function Ac(a,b){if(a.forEach&&typeof a.forEach=="function")a.forEach(b,void 0);else if(na(a)||typeof a==="string")Array.prototype.forEach.call(a,b,void 0);else for(var c=zc(a),d=yc(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)};var Bc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Cc(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(d>=0){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function S(a){this.g=this.o=this.j="";this.s=null;this.m=this.h="";this.l=!1;var b;a instanceof S?(this.l=a.l,Dc(this,a.j),this.o=a.o,this.g=a.g,Ec(this,a.s),this.h=a.h,Fc(this,Gc(a.i)),this.m=a.m):a&&(b=String(a).match(Bc))?(this.l=!1,Dc(this,b[1]||"",!0),this.o=Hc(b[2]||""),this.g=Hc(b[3]||"",!0),Ec(this,b[4]),this.h=Hc(b[5]||"",!0),Fc(this,b[6]||"",!0),this.m=Hc(b[7]||"")):(this.l=!1,this.i=new Ic(null,this.l))}
S.prototype.toString=function(){var a=[],b=this.j;b&&a.push(Jc(b,Kc,!0),":");var c=this.g;if(c||b=="file")a.push("//"),(b=this.o)&&a.push(Jc(b,Kc,!0),"@"),a.push(Lc(L(c))),c=this.s,c!=null&&a.push(":",String(c));if(c=this.h)this.g&&c.charAt(0)!="/"&&a.push("/"),a.push(Jc(c,c.charAt(0)=="/"?Mc:Nc,!0));(c=this.i.toString())&&a.push("?",c);(c=this.m)&&a.push("#",Jc(c,Oc));return a.join("")};
S.prototype.resolve=function(a){var b=N(this),c=!!a.j;c?Dc(b,a.j):c=!!a.o;c?b.o=a.o:c=!!a.g;c?b.g=a.g:c=a.s!=null;var d=a.h;if(c)Ec(b,a.s);else if(c=!!a.h){if(d.charAt(0)!="/")if(this.g&&!this.h)d="/"+d;else{var e=b.h.lastIndexOf("/");e!=-1&&(d=b.h.slice(0,e+1)+d)}e=d;if(e==".."||e==".")d="";else if(e.indexOf("./")!=-1||e.indexOf("/.")!=-1){d=e.lastIndexOf("/",0)==0;e=e.split("/");for(var f=[],g=0;g<e.length;){var h=e[g++];h=="."?d&&g==e.length&&f.push(""):h==".."?((f.length>1||f.length==1&&f[0]!=
"")&&f.pop(),d&&g==e.length&&f.push("")):(f.push(h),d=!0)}d=f.join("/")}else d=e}c?b.h=d:c=a.i.toString()!=="";c?Fc(b,Gc(a.i)):c=!!a.m;c&&(b.m=a.m);return b};function N(a){return new S(a)}function Dc(a,b,c){a.j=c?Hc(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))}function Ec(a,b){if(b){b=Number(b);if(isNaN(b)||b<0)throw Error("Bad port number "+b);a.s=b}else a.s=null}function Fc(a,b,c){b instanceof Ic?(a.i=b,Pc(a.i,a.l)):(c||(b=Jc(b,Qc)),a.i=new Ic(b,a.l))}function R(a,b,c){a.i.set(b,c)}
function Tb(a){R(a,"zx",Math.floor(Math.random()*2147483648).toString(36)+Math.abs(Math.floor(Math.random()*2147483648)^Date.now()).toString(36));return a}function Hc(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function Jc(a,b,c){return typeof a==="string"?(a=encodeURI(a).replace(b,Rc),c&&(a=Lc(a)),a):null}function Rc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}function Lc(a){return a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")}
var Kc=/[#\/\?@]/g,Nc=/[#\?:]/g,Mc=/[#\?]/g,Qc=/[#\?@]/g,Oc=/#/g;function Ic(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b}function U(a){a.g||(a.g=new Map,a.h=0,a.i&&Cc(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}n=Ic.prototype;n.add=function(a,b){U(this);this.i=null;a=V(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};function Sc(a,b){U(a);b=V(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a.g.delete(b))}
function Tc(a,b){U(a);b=V(a,b);return a.g.has(b)}n.forEach=function(a,b){U(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};n.pa=function(){U(this);for(var a=Array.from(this.g.values()),b=Array.from(this.g.keys()),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
n.X=function(a){U(this);var b=[];if(typeof a==="string")Tc(this,a)&&(b=b.concat(this.g.get(V(this,a))));else{a=Array.from(this.g.values());for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};n.set=function(a,b){U(this);this.i=null;a=V(this,a);Tc(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};n.get=function(a,b){if(!a)return b;a=this.X(a);return a.length>0?String(a[0]):b};function Wb(a,b,c){Sc(a,b);c.length>0&&(a.i=null,a.g.set(V(a,b),ta(c)),a.h+=c.length)}
n.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=L(d);d=this.X(d);for(var f=0;f<d.length;f++){var g=e;d[f]!==""&&(g+="="+L(d[f]));a.push(g)}}return this.i=a.join("&")};function Gc(a){var b=new Ic;b.i=a.i;a.g&&(b.g=new Map(a.g),b.h=a.h);return b}function V(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b}
function Pc(a,b){b&&!a.j&&(U(a),a.i=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Sc(this,d),Wb(this,e,c))},a));a.j=b};function Uc(a,b){var c=new Fb;if(v.Image){var d=new Image;d.onload=qa(W,c,"TestLoadImage: loaded",!0,b,d);d.onerror=qa(W,c,"TestLoadImage: error",!1,b,d);d.onabort=qa(W,c,"TestLoadImage: abort",!1,b,d);d.ontimeout=qa(W,c,"TestLoadImage: timeout",!1,b,d);v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},1E4);d.src=a}else b(!1)}
function Vc(a,b){var c=new Fb,d=new AbortController,e=setTimeout(function(){d.abort();W(c,"TestPingServer: timeout",!1,b)},1E4);fetch(a,{signal:d.signal}).then(function(f){clearTimeout(e);f.ok?W(c,"TestPingServer: ok",!0,b):W(c,"TestPingServer: server error",!1,b)}).catch(function(){clearTimeout(e);W(c,"TestPingServer: error",!1,b)})}function W(a,b,c,d,e){try{e&&(e.onload=null,e.onerror=null,e.onabort=null,e.ontimeout=null),d(c)}catch(f){}};function Wc(){this.g=new sb}function Xc(a,b,c){var d=c||"";try{Ac(a,function(e,f){var g=e;w(e)&&(g=qb(e));b.push(d+f+"="+encodeURIComponent(g))})}catch(e){throw b.push(d+"type="+encodeURIComponent("_badmap")),e;}};function Yc(a){this.i=a.Wb||null;this.h=a.gb||!1}y(Yc,tb);Yc.prototype.g=function(){return new Zc(this.i,this.h)};function Zc(a,b){D.call(this);this.D=a;this.o=b;this.m=void 0;this.status=this.readyState=0;this.responseType=this.responseText=this.response=this.statusText="";this.onreadystatechange=null;this.u=new Headers;this.h=null;this.B="GET";this.A="";this.g=!1;this.v=this.j=this.l=null}y(Zc,D);n=Zc.prototype;
n.open=function(a,b){if(this.readyState!=0)throw this.abort(),Error("Error reopening a connection");this.B=a;this.A=b;this.readyState=1;$c(this)};n.send=function(a){if(this.readyState!=1)throw this.abort(),Error("need to call open() first. ");this.g=!0;var b={headers:this.u,method:this.B,credentials:this.m,cache:void 0};a&&(b.body=a);(this.D||v).fetch(new Request(this.A,b)).then(this.Ua.bind(this),this.ja.bind(this))};
n.abort=function(){this.response=this.responseText="";this.u=new Headers;this.status=0;this.j&&this.j.cancel("Request was aborted.").catch(function(){});this.readyState>=1&&this.g&&this.readyState!=4&&(this.g=!1,ad(this));this.readyState=0};
n.Ua=function(a){if(this.g&&(this.l=a,this.h||(this.status=this.l.status,this.statusText=this.l.statusText,this.h=a.headers,this.readyState=2,$c(this)),this.g&&(this.readyState=3,$c(this),this.g)))if(this.responseType==="arraybuffer")a.arrayBuffer().then(this.Sa.bind(this),this.ja.bind(this));else if(typeof v.ReadableStream!=="undefined"&&"body"in a){this.j=a.body.getReader();if(this.o){if(this.responseType)throw Error('responseType must be empty for "streamBinaryChunks" mode responses.');this.response=
[]}else this.response=this.responseText="",this.v=new TextDecoder;bd(this)}else a.text().then(this.Ta.bind(this),this.ja.bind(this))};function bd(a){a.j.read().then(a.Ra.bind(a)).catch(a.ja.bind(a))}n.Ra=function(a){if(this.g){if(this.o&&a.value)this.response.push(a.value);else if(!this.o){var b=a.value?a.value:new Uint8Array(0);if(b=this.v.decode(b,{stream:!a.done}))this.response=this.responseText+=b}a.done?ad(this):$c(this);this.readyState==3&&bd(this)}};
n.Ta=function(a){this.g&&(this.response=this.responseText=a,ad(this))};n.Sa=function(a){this.g&&(this.response=a,ad(this))};n.ja=function(){this.g&&ad(this)};function ad(a){a.readyState=4;a.l=null;a.j=null;a.v=null;$c(a)}n.setRequestHeader=function(a,b){this.u.append(a,b)};n.getResponseHeader=function(a){return this.h?this.h.get(a.toLowerCase())||"":""};
n.getAllResponseHeaders=function(){if(!this.h)return"";for(var a=[],b=this.h.entries(),c=b.next();!c.done;)c=c.value,a.push(c[0]+": "+c[1]),c=b.next();return a.join("\r\n")};function $c(a){a.onreadystatechange&&a.onreadystatechange.call(a)}Object.defineProperty(Zc.prototype,"withCredentials",{get:function(){return this.m==="include"},set:function(a){this.m=a?"include":"same-origin"}});function cd(a){var b="";Na(a,function(c,d){b+=d;b+=":";b+=c;b+="\r\n"});return b}function dd(a,b,c){a:{for(d in c){var d=!1;break a}d=!0}d||(c=cd(c),typeof a==="string"?(L(b),c!=null&&L(c)):R(a,b,c))};function X(a){D.call(this);this.headers=new Map;this.L=a||null;this.h=!1;this.g=null;this.B="";this.o=0;this.l="";this.j=this.A=this.u=this.v=!1;this.m=null;this.D="";this.H=!1}y(X,D);var ed=/^https?$/i,fd=["POST","PUT"];n=X.prototype;n.Ja=function(a){this.H=a};
n.ga=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.B+"; newUri="+a);b=b?b.toUpperCase():"GET";this.B=a;this.l="";this.o=0;this.v=!1;this.h=!0;this.g=this.L?this.L.g():Mb.g();this.g.onreadystatechange=ra(x(this.Ga,this));try{this.A=!0,this.g.open(b,String(a),!0),this.A=!1}catch(g){gd(this,g);return}a=c||"";c=new Map(this.headers);if(d)if(Object.getPrototypeOf(d)===Object.prototype)for(var e in d)c.set(e,d[e]);else if(typeof d.keys==="function"&&
typeof d.get==="function"){e=t(d.keys());for(var f=e.next();!f.done;f=e.next())f=f.value,c.set(f,d.get(f))}else throw Error("Unknown input type for opt_headers: "+String(d));d=Array.from(c.keys()).find(function(g){return"content-type"==g.toLowerCase()});e=v.FormData&&a instanceof v.FormData;!(sa(fd,b)>=0)||d||e||c.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b=t(c);for(d=b.next();!d.done;d=b.next())c=t(d.value),d=c.next().value,c=c.next().value,this.g.setRequestHeader(d,c);
this.D&&(this.g.responseType=this.D);"withCredentials"in this.g&&this.g.withCredentials!==this.H&&(this.g.withCredentials=this.H);try{this.m&&(clearTimeout(this.m),this.m=null),this.u=!0,this.g.send(a),this.u=!1}catch(g){gd(this,g)}};function gd(a,b){a.h=!1;a.g&&(a.j=!0,a.g.abort(),a.j=!1);a.l=b;a.o=5;hd(a);id(a)}function hd(a){a.v||(a.v=!0,F(a,"complete"),F(a,"error"))}
n.abort=function(a){this.g&&this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1,this.o=a||7,F(this,"complete"),F(this,"abort"),id(this))};n.N=function(){this.g&&(this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1),id(this,!0));X.Y.N.call(this)};n.Ga=function(){this.s||(this.A||this.u||this.j?jd(this):this.eb())};n.eb=function(){jd(this)};
function jd(a){if(a.h&&typeof ma!="undefined")if(a.u&&O(a)==4)setTimeout(a.Ga.bind(a),0);else if(F(a,"readystatechange"),O(a)==4){a.h=!1;try{var b=a.ea();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=b===0){var f=String(a.B).match(Bc)[1]||null;!f&&v.self&&v.self.location&&(f=v.self.location.protocol.slice(0,-1));e=!ed.test(f?f.toLowerCase():"")}d=e}if(d)F(a,"complete"),F(a,"success");else{a.o=6;try{var g=O(a)>
2?a.g.statusText:""}catch(h){g=""}a.l=g+" ["+a.ea()+"]";hd(a)}}finally{id(a)}}}function id(a,b){if(a.g){a.m&&(clearTimeout(a.m),a.m=null);var c=a.g;a.g=null;b||F(a,"ready");try{c.onreadystatechange=null}catch(d){}}}n.isActive=function(){return!!this.g};function O(a){return a.g?a.g.readyState:0}n.ea=function(){try{return O(this)>2?this.g.status:-1}catch(a){return-1}};n.qa=function(){try{return this.g?this.g.responseText:""}catch(a){return""}};
n.Qa=function(a){if(this.g){var b=this.g.responseText;a&&b.indexOf(a)==0&&(b=b.substring(a.length));return rb(b)}};function Yb(a){try{if(!a.g)return null;if("response"in a.g)return a.g.response;switch(a.D){case "":case "text":return a.g.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in a.g)return a.g.mozResponseArrayBuffer}return null}catch(b){return null}}
function hc(a){var b={};a=(a.g&&O(a)>=2?a.g.getAllResponseHeaders()||"":"").split("\r\n");for(var c=0;c<a.length;c++)if(!Ia(a[c])){var d=Ob(a[c]),e=d[0];d=d[1];if(typeof d==="string"){d=d.trim();var f=b[e]||[];b[e]=f;f.push(d)}}Oa(b,function(g){return g.join(", ")})}n.Da=function(){return this.o};n.Ma=function(){return typeof this.l==="string"?this.l:String(this.l)};function kd(a,b,c){return c&&c.internalChannelParams?c.internalChannelParams[a]||b:b}
function ld(a){this.Ca=0;this.i=[];this.j=new Fb;this.la=this.sa=this.J=this.Z=this.g=this.Aa=this.F=this.H=this.s=this.U=this.o=null;this.ab=this.W=0;this.Xa=kd("failFast",!1,a);this.D=this.C=this.u=this.m=this.l=null;this.aa=!0;this.Ba=this.V=-1;this.ba=this.v=this.B=0;this.Va=kd("baseRetryDelayMs",5E3,a);this.fb=kd("retryDelaySeedMs",1E4,a);this.Ya=kd("forwardChannelMaxRetries",2,a);this.ya=kd("forwardChannelRequestTimeoutMs",2E4,a);this.ra=a&&a.xmlHttpFactory||void 0;this.Za=a&&a.Vb||void 0;this.Ea=
a&&a.useFetchStreams||!1;this.M=void 0;this.K=a&&a.supportsCrossDomainXhr||!1;this.L="";this.h=new vc(a&&a.concurrentRequestLimit);this.Fa=new Wc;this.S=a&&a.fastHandshake||!1;this.R=a&&a.encodeInitMessageHeaders||!1;this.S&&this.R&&(this.R=!1);this.Wa=a&&a.Tb||!1;a&&a.za&&this.j.za();a&&a.forceLongPolling&&(this.aa=!1);this.ca=!this.S&&this.aa&&a&&a.detectBufferingProxy||!1;this.ma=void 0;a&&a.longPollingTimeout&&a.longPollingTimeout>0&&(this.ma=a.longPollingTimeout);this.da=void 0;this.T=0;this.O=
!1;this.na=this.A=null}n=ld.prototype;n.oa=8;n.G=1;n.connect=function(a,b,c,d){I(0);this.Z=a;this.H=b||{};c&&d!==void 0&&(this.H.OSID=c,this.H.OAID=d);this.D=this.aa;this.J=pc(this,null,this.Z);sc(this)};
function tc(a){md(a);if(a.G==3){var b=a.W++,c=N(a.J);R(c,"SID",a.L);R(c,"RID",b);R(c,"TYPE","terminate");nd(a,c);b=new M(a,a.j,b);b.M=2;b.v=Tb(N(c));c=!1;if(v.navigator&&v.navigator.sendBeacon)try{c=v.navigator.sendBeacon(b.v.toString(),"")}catch(d){}!c&&v.Image&&((new Image).src=b.v,c=!0);c||(b.g=Xb(b.j,null),b.g.ga(b.v));b.D=Date.now();Vb(b)}od(a)}function lc(a){a.g&&(fc(a),a.g.cancel(),a.g=null)}
function md(a){lc(a);a.u&&(v.clearTimeout(a.u),a.u=null);kc(a);a.h.cancel();a.m&&(typeof a.m==="number"&&v.clearTimeout(a.m),a.m=null)}function sc(a){wc(a.h)||a.m||(a.m=!0,Ea(a.Ia,a),a.B=0)}function pd(a,b){if(nc(a.h)>=a.h.j-(a.m?1:0))return!1;if(a.m)return a.i=b.F.concat(a.i),!0;if(a.G==1||a.G==2||a.B>=(a.Xa?0:a.Ya))return!1;a.m=Eb(x(a.Ia,a,b),qd(a,a.B));a.B++;return!0}
n.Ia=function(a){if(this.m)if(this.m=null,this.G==1){if(!a){this.W=Math.floor(Math.random()*1E5);a=this.W++;var b=new M(this,this.j,a),c=this.o;this.U&&(c?(c=Pa(c),Ra(c,this.U)):c=this.U);this.s!==null||this.R||(b.J=c,c=null);var d;if(this.S)a:{for(var e=d=0;e<this.i.length;e++){b:{var f=this.i[e];if("__data__"in f.map&&(f=f.map.__data__,typeof f==="string")){f=f.length;break b}f=void 0}if(f===void 0)break;d+=f;if(d>4096){d=e;break a}if(d===4096||e===this.i.length-1){d=e+1;break a}}d=1E3}else d=1E3;
d=rd(this,b,d);e=N(this.J);R(e,"RID",a);R(e,"CVER",22);this.F&&R(e,"X-HTTP-Session-Id",this.F);nd(this,e);c&&(this.R?d="headers="+L(cd(c))+"&"+d:this.s&&dd(e,this.s,c));oc(this.h,b);this.Wa&&R(e,"TYPE","init");this.S?(R(e,"$req",d),R(e,"SID","null"),b.V=!0,Sb(b,e,null)):Sb(b,e,d);this.G=2}}else this.G==3&&(a?sd(this,a):this.i.length==0||wc(this.h)||sd(this))};
function sd(a,b){var c;b?c=b.l:c=a.W++;var d=N(a.J);R(d,"SID",a.L);R(d,"RID",c);R(d,"AID",a.V);nd(a,d);a.s&&a.o&&dd(d,a.s,a.o);c=new M(a,a.j,c,a.B+1);a.s===null&&(c.J=a.o);b&&(a.i=b.F.concat(a.i));b=rd(a,c,1E3);c.H=Math.round(a.ya*.5)+Math.round(a.ya*.5*Math.random());oc(a.h,c);Sb(c,d,b)}function nd(a,b){a.H&&Na(a.H,function(c,d){R(b,d,c)});a.l&&Ac({},function(c,d){R(b,d,c)})}
function rd(a,b,c){c=Math.min(a.i.length,c);var d=a.l?x(a.l.Pa,a.l,a):null;a:{for(var e=a.i,f=-1;;){var g=["count="+c];f==-1?c>0?(f=e[0].g,g.push("ofs="+f)):f=0:g.push("ofs="+f);for(var h=!0,k=0;k<c;k++){var l=e[k].g,m=e[k].map;l-=f;if(l<0)f=Math.max(0,e[k].g-100),h=!1;else try{Xc(m,g,"req"+l+"_")}catch(r){d&&d(m)}}if(h){d=g.join("&");break a}}d=void 0}a=a.i.splice(0,c);b.F=a;return d}function rc(a){a.g||a.u||(a.ba=1,Ea(a.Ha,a),a.v=0)}
function mc(a){if(a.g||a.u||a.v>=3)return!1;a.ba++;a.u=Eb(x(a.Ha,a),qd(a,a.v));a.v++;return!0}n.Ha=function(){this.u=null;td(this);if(this.ca&&!(this.O||this.g==null||this.T<=0)){var a=2*this.T;this.j.info("BP detection timer enabled: "+a);this.A=Eb(x(this.cb,this),a)}};n.cb=function(){this.A&&(this.A=null,this.j.info("BP detection timeout reached."),this.j.info("Buffering proxy detected and switch to long-polling!"),this.D=!1,this.O=!0,I(10),lc(this),td(this))};
function fc(a){a.A!=null&&(v.clearTimeout(a.A),a.A=null)}function td(a){a.g=new M(a,a.j,"rpc",a.ba);a.s===null&&(a.g.J=a.o);a.g.R=0;var b=N(a.sa);R(b,"RID","rpc");R(b,"SID",a.L);R(b,"AID",a.V);R(b,"CI",a.D?"0":"1");!a.D&&a.ma&&R(b,"TO",a.ma);R(b,"TYPE","xmlhttp");nd(a,b);a.s&&a.o&&dd(b,a.s,a.o);a.M&&(a.g.H=a.M);var c=a.g;a=a.la;c.M=1;c.v=Tb(N(b));c.s=null;c.S=!0;Ub(c,a)}n.bb=function(){this.C!=null&&(this.C=null,lc(this),mc(this),I(19))};function kc(a){a.C!=null&&(v.clearTimeout(a.C),a.C=null)}
function gc(a,b){var c=null;if(a.g==b){kc(a);fc(a);a.g=null;var d=2}else if(jc(a.h,b))c=b.F,qc(a.h,b),d=1;else return;if(a.G!=0)if(b.o)if(d==1){c=b.s?b.s.length:0;b=Date.now()-b.D;var e=a.B;d=zb();F(d,new Db(d,c,b,e));sc(a)}else rc(a);else if(e=b.m,e==3||e==0&&b.aa>0||!(d==1&&pd(a,b)||d==2&&mc(a)))switch(c&&c.length>0&&(b=a.h,b.i=b.i.concat(c)),e){case 1:Q(a,5);break;case 4:Q(a,10);break;case 3:Q(a,6);break;default:Q(a,2)}}
function qd(a,b){var c=a.Va+Math.floor(Math.random()*a.fb);a.isActive()||(c*=2);return c*b}function Q(a,b){a.j.info("Error code "+b);if(b==2){var c=x(a.hb,a),d=a.Za,e=!d;d=new S(d||"//www.google.com/images/cleardot.gif");v.location&&v.location.protocol=="http"||Dc(d,"https");Tb(d);e?Uc(d.toString(),c):Vc(d.toString(),c)}else I(2);a.G=0;a.l&&a.l.ua(b);od(a);md(a)}n.hb=function(a){a?(this.j.info("Successfully pinged google.com"),I(2)):(this.j.info("Failed to ping google.com"),I(1))};
function od(a){a.G=0;a.na=[];if(a.l){var b=xc(a.h);if(b.length!=0||a.i.length!=0)ua(a.na,b),ua(a.na,a.i),a.h.i.length=0,ta(a.i),a.i.length=0;a.l.ta()}}function pc(a,b,c){var d=c instanceof S?N(c):new S(c);if(d.g!="")b&&(d.g=b+"."+d.g),Ec(d,d.s);else{var e=v.location;d=e.protocol;b=b?b+"."+e.hostname:e.hostname;e=+e.port;var f=new S(null);d&&Dc(f,d);b&&(f.g=b);e&&Ec(f,e);c&&(f.h=c);d=f}c=a.F;b=a.Aa;c&&b&&R(d,c,b);R(d,"VER",a.oa);nd(a,d);return d}
function Xb(a,b,c){if(b&&!a.K)throw Error("Can't create secondary domain capable XhrIo object.");b=a.Ea&&!a.ra?new X(new Yc({gb:c})):new X(a.ra);b.Ja(a.K);return b}n.isActive=function(){return!!this.l&&this.l.isActive(this)};function ud(){}n=ud.prototype;n.wa=function(){};n.va=function(){};n.ua=function(){};n.ta=function(){};n.isActive=function(){return!0};n.Pa=function(){};function vd(){}vd.prototype.g=function(a,b){return new Y(a,b)};
function Y(a,b){D.call(this);this.g=new ld(b);this.l=a;this.h=b&&b.messageUrlParams||null;a=b&&b.messageHeaders||null;b&&b.clientProtocolHeaderRequired&&(a?a["X-Client-Protocol"]="webchannel":a={"X-Client-Protocol":"webchannel"});this.g.o=a;a=b&&b.initMessageHeaders||null;b&&b.messageContentType&&(a?a["X-WebChannel-Content-Type"]=b.messageContentType:a={"X-WebChannel-Content-Type":b.messageContentType});b&&b.xa&&(a?a["X-WebChannel-Client-Profile"]=b.xa:a={"X-WebChannel-Client-Profile":b.xa});this.g.U=
a;(a=b&&b.Ub)&&!Ia(a)&&(this.g.s=a);this.v=b&&b.supportsCrossDomainXhr||!1;this.u=b&&b.sendRawJson||!1;(b=b&&b.httpSessionIdParam)&&!Ia(b)&&(this.g.F=b,a=this.h,a!==null&&b in a&&(a=this.h,b in a&&delete a[b]));this.j=new Z(this)}y(Y,D);Y.prototype.m=function(){this.g.l=this.j;this.v&&(this.g.K=!0);this.g.connect(this.l,this.h||void 0)};Y.prototype.close=function(){tc(this.g)};
Y.prototype.o=function(a){var b=this.g;if(typeof a==="string"){var c={};c.__data__=a;a=c}else this.u&&(c={},c.__data__=qb(a),a=c);b.i.push(new uc(b.ab++,a));b.G==3&&sc(b)};Y.prototype.N=function(){this.g.l=null;delete this.j;tc(this.g);delete this.g;Y.Y.N.call(this)};
function wd(a){wb.call(this);a.__headers__&&(this.headers=a.__headers__,this.statusCode=a.__status__,delete a.__headers__,delete a.__status__);var b=a.__sm__;if(b){a:{for(var c in b){a=c;break a}a=void 0}if(this.i=a)a=this.i,b=b!==null&&a in b?b[a]:void 0;this.data=b}else this.data=a}y(wd,wb);function xd(){xb.call(this);this.status=1}y(xd,xb);function Z(a){this.g=a}y(Z,ud);Z.prototype.wa=function(){F(this.g,"a")};Z.prototype.va=function(a){F(this.g,new wd(a))};
Z.prototype.ua=function(a){F(this.g,new xd(a))};Z.prototype.ta=function(){F(this.g,"b")};vd.prototype.createWebChannel=vd.prototype.g;Y.prototype.send=Y.prototype.o;Y.prototype.open=Y.prototype.m;Y.prototype.close=Y.prototype.close;module.exports.createWebChannelTransport=function(){return new vd};module.exports.getStatEventTarget=function(){return zb()};module.exports.Event=H;module.exports.Stat={ob:0,rb:1,sb:2,Lb:3,Qb:4,Nb:5,Ob:6,Mb:7,Kb:8,Pb:9,PROXY:10,NOPROXY:11,Ib:12,Eb:13,Fb:14,Db:15,Gb:16,Hb:17,kb:18,jb:19,lb:20};Kb.NO_ERROR=0;Kb.TIMEOUT=8;Kb.HTTP_ERROR=6;
module.exports.ErrorCode=Kb;Lb.COMPLETE="complete";module.exports.EventType=Lb;ub.EventType=vb;vb.OPEN="a";vb.CLOSE="b";vb.ERROR="c";vb.MESSAGE="d";D.prototype.listen=D.prototype.J;module.exports.WebChannel=ub;module.exports.FetchXmlHttpFactory=Yc;X.prototype.listenOnce=X.prototype.K;X.prototype.getLastError=X.prototype.Ma;X.prototype.getLastErrorCode=X.prototype.Da;X.prototype.getStatus=X.prototype.ea;X.prototype.getResponseJson=X.prototype.Qa;X.prototype.getResponseText=X.prototype.qa;
X.prototype.send=X.prototype.ga;X.prototype.setWithCredentials=X.prototype.Ja;module.exports.XhrIo=X;}).apply( typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self  : typeof window !== 'undefined' ? window  : {});
