/** @license
Copyright The Closure Library Authors.
SPDX-License-Identifier: Apache-2.0
*/
(function() {'use strict';var h,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this);
function da(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}function fa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}
da("Array.prototype.values",function(a){return a?a:function(){return fa(this,function(b,c){return c})}});/** @license

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ha=ha||{},k=this||self;function ia(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length}function n(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ja(a,b,c){return a.call.apply(a.bind,arguments)}
function ka(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function p(a,b,c){p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ja:ka;return p.apply(null,arguments)}
function la(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}function r(a,b){function c(){}c.prototype=b.prototype;a.X=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Yb=function(d,e,f){for(var g=Array(arguments.length-2),m=2;m<arguments.length;m++)g[m-2]=arguments[m];return b.prototype[e].apply(d,g)}};function ma(a){const b=a.length;if(0<b){const c=Array(b);for(let d=0;d<b;d++)c[d]=a[d];return c}return[]}function na(a,b){for(let c=1;c<arguments.length;c++){const d=arguments[c];if(ia(d)){const e=a.length||0,f=d.length||0;a.length=e+f;for(let g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}};class oa{constructor(a,b){this.i=a;this.j=b;this.h=0;this.g=null}get(){let a;0<this.h?(this.h--,a=this.g,this.g=a.next,a.next=null):a=this.i();return a}};var pa,qa;a:{for(var ra=["CLOSURE_FLAGS"],sa=k,ta=0;ta<ra.length;ta++)if(sa=sa[ra[ta]],null==sa){qa=null;break a}qa=sa}var ua=qa&&qa[610401301];pa=null!=ua?ua:!1;function t(a){return/^[\s\xa0]*$/.test(a)};function va(){var a=k.navigator;return a&&(a=a.userAgent)?a:""}var u;const wa=k.navigator;u=wa?wa.userAgentData||null:null;function w(a){return-1!=va().indexOf(a)};function xa(a){xa[" "](a);return a}xa[" "]=function(){};var ya=pa&&u&&0<u.brands.length?!1:w("Opera"),x=pa&&u&&0<u.brands.length?!1:w("Trident")||w("MSIE"),za=w("Edge"),Aa=za||x,Ba=w("Gecko")&&!(-1!=va().toLowerCase().indexOf("webkit")&&!w("Edge"))&&!(w("Trident")||w("MSIE"))&&!w("Edge"),Ca=-1!=va().toLowerCase().indexOf("webkit")&&!w("Edge");function Da(){var a=k.document;return a?a.documentMode:void 0}var Ga;
a:{var Ha="",Ia=function(){var a=va();if(Ba)return/rv:([^\);]+)(\)|;)/.exec(a);if(za)return/Edge\/([\d\.]+)/.exec(a);if(x)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ca)return/WebKit\/(\S+)/.exec(a);if(ya)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ia&&(Ha=Ia?Ia[1]:"");if(x){var Ja=Da();if(null!=Ja&&Ja>parseFloat(Ha)){Ga=String(Ja);break a}}Ga=Ha}var Ka=Ga,La;if(k.document&&x){var Ma=Da();La=Ma?Ma:parseInt(Ka,10)||void 0}else La=void 0;var Na=La;function Oa(a,b,c){for(const d in a)b.call(c,a[d],d,a)}function Pa(a,b){for(const c in a)b.call(void 0,a[c],c,a)}function Qa(a){const b={};for(const c in a)b[c]=a[c];return b}const Ra="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Sa(a,b){let c,d;for(let e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(let f=0;f<Ra.length;f++)c=Ra[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Ta(a){var b=1;a=a.split(":");const c=[];for(;0<b&&a.length;)c.push(a.shift()),b--;a.length&&c.push(a.join(":"));return c};function Ua(a){k.setTimeout(()=>{throw a;},0)};function Va(){var a=Wa;let b=null;a.g&&(b=a.g,a.g=a.g.next,a.g||(a.h=null),b.next=null);return b}class Xa{constructor(){this.h=this.g=null}add(a,b){const c=Ya.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c}}var Ya=new oa(()=>new Za,a=>a.reset());class Za{constructor(){this.next=this.g=this.h=null}set(a,b){this.h=a;this.g=b;this.next=null}reset(){this.next=this.g=this.h=null}};let y,z=!1,Wa=new Xa,ab=()=>{const a=k.Promise.resolve(void 0);y=()=>{a.then($a)}};var $a=()=>{for(var a;a=Va();){try{a.h.call(a.g)}catch(c){Ua(c)}var b=Ya;b.j(a);100>b.h&&(b.h++,a.next=b.g,b.g=a)}z=!1};function A(){this.s=this.s;this.C=this.C}A.prototype.s=!1;A.prototype.pa=function(){this.s||(this.s=!0,this.M())};A.prototype.M=function(){if(this.C)for(;this.C.length;)this.C.shift()()};function B(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1}B.prototype.h=function(){this.defaultPrevented=!0};var bb=function(){if(!k.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{const c=()=>{};k.addEventListener("test",c,b);k.removeEventListener("test",c,b)}catch(c){}return a}();function C(a,b){B.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.i=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;if(b=a.relatedTarget){if(Ba){a:{try{xa(b.nodeName);var e=!0;break a}catch(f){}e=
!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=
a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:cb[a.pointerType]||"";this.state=a.state;this.i=a;a.defaultPrevented&&C.X.h.call(this)}}r(C,B);var cb={2:"touch",3:"pen",4:"mouse"};C.prototype.h=function(){C.X.h.call(this);var a=this.i;a.preventDefault?a.preventDefault():a.returnValue=!1};var D="closure_listenable_"+(1E6*Math.random()|0);var db=0;function eb(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.ia=e;this.key=++db;this.ca=this.fa=!1}function fb(a){a.ca=!0;a.listener=null;a.proxy=null;a.src=null;a.ia=null};function gb(a){this.src=a;this.g={};this.h=0}gb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);var g=hb(a,b,d,e);-1<g?(b=a[g],c||(b.fa=!1)):(b=new eb(b,this.src,f,!!d,e),b.fa=c,a.push(b));return b};function ib(a,b){var c=b.type;if(c in a.g){var d=a.g[c],e=Array.prototype.indexOf.call(d,b,void 0),f;(f=0<=e)&&Array.prototype.splice.call(d,e,1);f&&(fb(b),0==a.g[c].length&&(delete a.g[c],a.h--))}}
function hb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.ca&&f.listener==b&&f.capture==!!c&&f.ia==d)return e}return-1};var jb="closure_lm_"+(1E6*Math.random()|0),kb={},lb=0;function mb(a,b,c,d,e){if(d&&d.once)return nb(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)mb(a,b[f],c,d,e);return null}c=ob(c);return a&&a[D]?a.N(b,c,n(d)?!!d.capture:!!d,e):pb(a,b,c,!1,d,e)}
function pb(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=n(e)?!!e.capture:!!e,m=qb(a);m||(a[jb]=m=new gb(a));c=m.add(b,c,d,g,f);if(c.proxy)return c;d=rb();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)bb||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(sb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");lb++;return c}
function rb(){function a(c){return b.call(a.src,a.listener,c)}const b=tb;return a}function nb(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)nb(a,b[f],c,d,e);return null}c=ob(c);return a&&a[D]?a.O(b,c,n(d)?!!d.capture:!!d,e):pb(a,b,c,!0,d,e)}
function vb(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)vb(a,b[f],c,d,e);else(d=n(d)?!!d.capture:!!d,c=ob(c),a&&a[D])?(a=a.i,b=String(b).toString(),b in a.g&&(f=a.g[b],c=hb(f,c,d,e),-1<c&&(fb(f[c]),Array.prototype.splice.call(f,c,1),0==f.length&&(delete a.g[b],a.h--)))):a&&(a=qb(a))&&(b=a.g[b.toString()],a=-1,b&&(a=hb(b,c,d,e)),(c=-1<a?b[a]:null)&&wb(c))}
function wb(a){if("number"!==typeof a&&a&&!a.ca){var b=a.src;if(b&&b[D])ib(b.i,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(sb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);lb--;(c=qb(b))?(ib(c,a),0==c.h&&(c.src=null,b[jb]=null)):fb(a)}}}function sb(a){return a in kb?kb[a]:kb[a]="on"+a}function tb(a,b){if(a.ca)a=!0;else{b=new C(b,this);var c=a.listener,d=a.ia||a.src;a.fa&&wb(a);a=c.call(d,b)}return a}
function qb(a){a=a[jb];return a instanceof gb?a:null}var xb="__closure_events_fn_"+(1E9*Math.random()>>>0);function ob(a){if("function"===typeof a)return a;a[xb]||(a[xb]=function(b){return a.handleEvent(b)});return a[xb]};function F(){A.call(this);this.i=new gb(this);this.P=this;this.I=null}r(F,A);F.prototype[D]=!0;F.prototype.removeEventListener=function(a,b,c,d){vb(this,a,b,c,d)};
function G(a,b){var c,d=a.I;if(d)for(c=[];d;d=d.I)c.push(d);a=a.P;d=b.type||b;if("string"===typeof b)b=new B(b,a);else if(b instanceof B)b.target=b.target||a;else{var e=b;b=new B(d,a);Sa(b,e)}e=!0;if(c)for(var f=c.length-1;0<=f;f--){var g=b.g=c[f];e=yb(g,d,!0,b)&&e}g=b.g=a;e=yb(g,d,!0,b)&&e;e=yb(g,d,!1,b)&&e;if(c)for(f=0;f<c.length;f++)g=b.g=c[f],e=yb(g,d,!1,b)&&e}
F.prototype.M=function(){F.X.M.call(this);if(this.i){var a=this.i,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,fb(d[e]);delete a.g[c];a.h--}}this.I=null};F.prototype.N=function(a,b,c,d){return this.i.add(String(a),b,!1,c,d)};F.prototype.O=function(a,b,c,d){return this.i.add(String(a),b,!0,c,d)};
function yb(a,b,c,d){b=a.i.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.ca&&g.capture==c){var m=g.listener,v=g.ia||g.src;g.fa&&ib(a.i,g);e=!1!==m.call(v,d)&&e}}return e&&!d.defaultPrevented};function zb(a,b){F.call(this);this.h=a||1;this.g=b||k;this.j=p(this.nb,this);this.l=Date.now()}r(zb,F);h=zb.prototype;h.da=!1;h.R=null;h.nb=function(){if(this.da){var a=Date.now()-this.l;0<a&&a<.8*this.h?this.R=this.g.setTimeout(this.j,this.h-a):(this.R&&(this.g.clearTimeout(this.R),this.R=null),G(this,"tick"),this.da&&(Ab(this),this.start()))}};h.start=function(){this.da=!0;this.R||(this.R=this.g.setTimeout(this.j,this.h),this.l=Date.now())};
function Ab(a){a.da=!1;a.R&&(a.g.clearTimeout(a.R),a.R=null)}h.M=function(){zb.X.M.call(this);Ab(this);delete this.g};function Bb(a,b,c){if("function"===typeof a)c&&(a=p(a,c));else if(a&&"function"==typeof a.handleEvent)a=p(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:k.setTimeout(a,b||0)};function Cb(a){a.g=Bb(()=>{a.g=null;a.i&&(a.i=!1,Cb(a))},a.j);const b=a.h;a.h=null;a.m.apply(null,b)}class Db extends A{constructor(a,b){super();this.m=a;this.j=b;this.h=null;this.i=!1;this.g=null}l(a){this.h=arguments;this.g?this.i=!0:Cb(this)}M(){super.M();this.g&&(k.clearTimeout(this.g),this.g=null,this.i=!1,this.h=null)}};function H(a){A.call(this);this.h=a;this.g={}}r(H,A);var Eb=[];function Fb(a,b,c,d){Array.isArray(c)||(c&&(Eb[0]=c.toString()),c=Eb);for(var e=0;e<c.length;e++){var f=mb(b,c[e],d||a.handleEvent,!1,a.h||a);if(!f)break;a.g[f.key]=f}}function Gb(a){Oa(a.g,function(b,c){this.g.hasOwnProperty(c)&&wb(b)},a);a.g={}}H.prototype.M=function(){H.X.M.call(this);Gb(this)};H.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var Hb=k.JSON.stringify;var Ib=k.JSON.parse;var Jb=class{stringify(a){return k.JSON.stringify(a,void 0)}parse(a){return k.JSON.parse(a,void 0)}};function Kb(){}Kb.prototype.h=null;function Lb(a){return a.h||(a.h=a.i())};function Mb(){}var I={OPEN:"a",sb:"b",Na:"c",Eb:"d"};function Nb(){B.call(this,"d")}r(Nb,B);function Ob(){B.call(this,"c")}r(Ob,B);var J={},Pb=null;function Qb(){return Pb=Pb||new F}J.Pa="serverreachability";function Rb(a){B.call(this,J.Pa,a)}r(Rb,B);function K(a){const b=Qb();G(b,new Rb(b,a))}J.STAT_EVENT="statevent";function Sb(a,b){B.call(this,J.STAT_EVENT,a);this.stat=b}r(Sb,B);function L(a){const b=Qb();G(b,new Sb(b,a))}J.Qa="timingevent";function Tb(a,b){B.call(this,J.Qa,a);this.size=b}r(Tb,B);
function M(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");return k.setTimeout(function(){a()},b)};function Ub(){this.g=!0}Ub.prototype.Aa=function(){this.g=!1};function Vb(a,b,c,d,e,f){a.info(function(){if(a.g)if(f){var g="";for(var m=f.split("&"),v=0;v<m.length;v++){var l=m[v].split("=");if(1<l.length){var q=l[0];l=l[1];var E=q.split("_");g=2<=E.length&&"type"==E[1]?g+(q+"="+l+"&"):g+(q+"=redacted&")}}}else g=null;else g=f;return"XMLHTTP REQ ("+d+") [attempt "+e+"]: "+b+"\n"+c+"\n"+g})}
function Wb(a,b,c,d,e,f,g){a.info(function(){return"XMLHTTP RESP ("+d+") [ attempt "+e+"]: "+b+"\n"+c+"\n"+f+" "+g})}function N(a,b,c,d){a.info(function(){return"XMLHTTP TEXT ("+b+"): "+Xb(a,c)+(d?" "+d:"")})}function Yb(a,b){a.info(function(){return"TIMEOUT: "+b})}Ub.prototype.info=function(){};
function Xb(a,b){if(!a.g)return b;if(!b)return null;try{var c=JSON.parse(b);if(c)for(a=0;a<c.length;a++)if(Array.isArray(c[a])){var d=c[a];if(!(2>d.length)){var e=d[1];if(Array.isArray(e)&&!(1>e.length)){var f=e[0];if("noop"!=f&&"stop"!=f&&"close"!=f)for(var g=1;g<e.length;g++)e[g]=""}}}return Hb(c)}catch(m){return b}};var Zb={NO_ERROR:0,ob:1,Bb:2,Ab:3,vb:4,zb:5,Cb:6,Ma:7,TIMEOUT:8,Fb:9};var $b={tb:"complete",Pb:"success",Na:"error",Ma:"abort",Hb:"ready",Ib:"readystatechange",TIMEOUT:"timeout",Db:"incrementaldata",Gb:"progress",wb:"downloadprogress",Xb:"uploadprogress"};var ac;function bc(){}r(bc,Kb);bc.prototype.g=function(){return new XMLHttpRequest};bc.prototype.i=function(){return{}};ac=new bc;function cc(a,b,c,d){this.l=a;this.j=b;this.m=c;this.U=d||1;this.S=new H(this);this.O=45E3;a=Aa?125:void 0;this.T=new zb(a);this.H=null;this.i=!1;this.u=this.A=this.v=this.K=this.F=this.V=this.B=null;this.D=[];this.g=null;this.s=0;this.o=this.C=null;this.aa=-1;this.I=!1;this.N=0;this.L=null;this.Z=this.J=this.Y=this.P=!1;this.h=new dc}function dc(){this.i=null;this.g="";this.h=!1}var ec={},fc={};h=cc.prototype;h.setTimeout=function(a){this.O=a};
function gc(a,b,c){a.K=1;a.v=hc(O(b));a.u=c;a.P=!0;ic(a,null)}function ic(a,b){a.F=Date.now();jc(a);a.A=O(a.v);var c=a.A,d=a.U;Array.isArray(d)||(d=[String(d)]);kc(c.i,"t",d);a.s=0;c=a.l.J;a.h=new dc;a.g=lc(a.l,c?b:null,!a.u);0<a.N&&(a.L=new Db(p(a.La,a,a.g),a.N));Fb(a.S,a.g,"readystatechange",a.kb);b=a.H?Qa(a.H):{};a.u?(a.C||(a.C="POST"),b["Content-Type"]="application/x-www-form-urlencoded",a.g.ea(a.A,a.C,a.u,b)):(a.C="GET",a.g.ea(a.A,a.C,null,b));K(1);Vb(a.j,a.C,a.A,a.m,a.U,a.u)}
h.kb=function(a){a=a.target;const b=this.L;b&&3==P(a)?b.l():this.La(a)};
h.La=function(a){try{if(a==this.g)a:{const q=P(this.g);var b=this.g.Ea();const E=this.g.ba();if(!(3>q)&&(3!=q||Aa||this.g&&(this.h.h||this.g.ga()||mc(this.g)))){this.I||4!=q||7==b||(8==b||0>=E?K(3):K(2));nc(this);var c=this.g.ba();this.aa=c;b:if(oc(this)){var d=mc(this.g);a="";var e=d.length,f=4==P(this.g);if(!this.h.i){if("undefined"===typeof TextDecoder){Q(this);pc(this);var g="";break b}this.h.i=new k.TextDecoder}for(b=0;b<e;b++)this.h.h=!0,a+=this.h.i.decode(d[b],{stream:f&&b==e-1});d.length=
0;this.h.g+=a;this.s=0;g=this.h.g}else g=this.g.ga();this.i=200==c;Wb(this.j,this.C,this.A,this.m,this.U,q,c);if(this.i){if(this.Y&&!this.J){b:{if(this.g){var m,v=this.g;if((m=v.g?v.g.getResponseHeader("X-HTTP-Initial-Response"):null)&&!t(m)){var l=m;break b}}l=null}if(c=l)N(this.j,this.m,c,"Initial handshake response via X-HTTP-Initial-Response"),this.J=!0,qc(this,c);else{this.i=!1;this.o=3;L(12);Q(this);pc(this);break a}}this.P?(rc(this,q,g),Aa&&this.i&&3==q&&(Fb(this.S,this.T,"tick",this.jb),this.T.start())):
(N(this.j,this.m,g,null),qc(this,g));4==q&&Q(this);this.i&&!this.I&&(4==q?sc(this.l,this):(this.i=!1,jc(this)))}else tc(this.g),400==c&&0<g.indexOf("Unknown SID")?(this.o=3,L(12)):(this.o=0,L(13)),Q(this),pc(this)}}}catch(q){}finally{}};function oc(a){return a.g?"GET"==a.C&&2!=a.K&&a.l.Fa:!1}
function rc(a,b,c){let d=!0,e;for(;!a.I&&a.s<c.length;)if(e=uc(a,c),e==fc){4==b&&(a.o=4,L(14),d=!1);N(a.j,a.m,null,"[Incomplete Response]");break}else if(e==ec){a.o=4;L(15);N(a.j,a.m,c,"[Invalid Chunk]");d=!1;break}else N(a.j,a.m,e,null),qc(a,e);oc(a)&&0!=a.s&&(a.h.g=a.h.g.slice(a.s),a.s=0);4!=b||0!=c.length||a.h.h||(a.o=1,L(16),d=!1);a.i=a.i&&d;d?0<c.length&&!a.Z&&(a.Z=!0,b=a.l,b.g==a&&b.ja&&!b.N&&(b.j.info("Great, no buffering proxy detected. Bytes received: "+c.length),vc(b),b.N=!0,L(11))):(N(a.j,
a.m,c,"[Invalid Chunked Response]"),Q(a),pc(a))}h.jb=function(){if(this.g){var a=P(this.g),b=this.g.ga();this.s<b.length&&(nc(this),rc(this,a,b),this.i&&4!=a&&jc(this))}};function uc(a,b){var c=a.s,d=b.indexOf("\n",c);if(-1==d)return fc;c=Number(b.substring(c,d));if(isNaN(c))return ec;d+=1;if(d+c>b.length)return fc;b=b.slice(d,d+c);a.s=d+c;return b}h.cancel=function(){this.I=!0;Q(this)};function jc(a){a.V=Date.now()+a.O;wc(a,a.O)}
function wc(a,b){if(null!=a.B)throw Error("WatchDog timer not null");a.B=M(p(a.hb,a),b)}function nc(a){a.B&&(k.clearTimeout(a.B),a.B=null)}h.hb=function(){this.B=null;const a=Date.now();0<=a-this.V?(Yb(this.j,this.A),2!=this.K&&(K(3),L(17)),Q(this),this.o=2,pc(this)):wc(this,this.V-a)};function pc(a){0==a.l.G||a.I||sc(a.l,a)}function Q(a){nc(a);var b=a.L;b&&"function"==typeof b.pa&&b.pa();a.L=null;Ab(a.T);Gb(a.S);a.g&&(b=a.g,a.g=null,b.abort(),b.pa())}
function qc(a,b){try{var c=a.l;if(0!=c.G&&(c.g==a||xc(c.h,a)))if(!a.J&&xc(c.h,a)&&3==c.G){try{var d=c.Ga.g.parse(b)}catch(l){d=null}if(Array.isArray(d)&&3==d.length){var e=d;if(0==e[0])a:{if(!c.u){if(c.g)if(c.g.F+3E3<a.F)yc(c),zc(c);else break a;Ac(c);L(18)}}else c.Ca=e[1],0<c.Ca-c.U&&37500>e[2]&&c.F&&0==c.v&&!c.C&&(c.C=M(p(c.eb,c),6E3));if(1>=Bc(c.h)&&c.ka){try{c.ka()}catch(l){}c.ka=void 0}}else R(c,11)}else if((a.J||c.g==a)&&yc(c),!t(b))for(e=c.Ga.g.parse(b),b=0;b<e.length;b++){let l=e[b];c.U=l[0];
l=l[1];if(2==c.G)if("c"==l[0]){c.K=l[1];c.la=l[2];const q=l[3];null!=q&&(c.oa=q,c.j.info("VER="+c.oa));const E=l[4];null!=E&&(c.Da=E,c.j.info("SVER="+c.Da));const Ea=l[5];null!=Ea&&"number"===typeof Ea&&0<Ea&&(d=1.5*Ea,c.L=d,c.j.info("backChannelRequestTimeoutMs_="+d));d=c;const ea=a.g;if(ea){const Fa=ea.g?ea.g.getResponseHeader("X-Client-Wire-Protocol"):null;if(Fa){var f=d.h;f.g||-1==Fa.indexOf("spdy")&&-1==Fa.indexOf("quic")&&-1==Fa.indexOf("h2")||(f.j=f.l,f.g=new Set,f.h&&(Cc(f,f.h),f.h=null))}if(d.D){const ub=
ea.g?ea.g.getResponseHeader("X-HTTP-Session-Id"):null;ub&&(d.Ba=ub,S(d.I,d.D,ub))}}c.G=3;c.l&&c.l.xa();c.ja&&(c.S=Date.now()-a.F,c.j.info("Handshake RTT: "+c.S+"ms"));d=c;var g=a;d.ta=Dc(d,d.J?d.la:null,d.Y);if(g.J){Ec(d.h,g);var m=g,v=d.L;v&&m.setTimeout(v);m.B&&(nc(m),jc(m));d.g=g}else Fc(d);0<c.i.length&&Gc(c)}else"stop"!=l[0]&&"close"!=l[0]||R(c,7);else 3==c.G&&("stop"==l[0]||"close"==l[0]?"stop"==l[0]?R(c,7):Hc(c):"noop"!=l[0]&&c.l&&c.l.wa(l),c.v=0)}K(4)}catch(l){}};var Ic=class{constructor(a,b){this.g=a;this.map=b}};function Jc(a){this.l=a||10;k.PerformanceNavigationTiming?(a=k.performance.getEntriesByType("navigation"),a=0<a.length&&("hq"==a[0].nextHopProtocol||"h2"==a[0].nextHopProtocol)):a=!!(k.chrome&&k.chrome.loadTimes&&k.chrome.loadTimes()&&k.chrome.loadTimes().wasFetchedViaSpdy);this.j=a?this.l:1;this.g=null;1<this.j&&(this.g=new Set);this.h=null;this.i=[]}function Kc(a){return a.h?!0:a.g?a.g.size>=a.j:!1}function Bc(a){return a.h?1:a.g?a.g.size:0}function xc(a,b){return a.h?a.h==b:a.g?a.g.has(b):!1}
function Cc(a,b){a.g?a.g.add(b):a.h=b}function Ec(a,b){a.h&&a.h==b?a.h=null:a.g&&a.g.has(b)&&a.g.delete(b)}Jc.prototype.cancel=function(){this.i=Lc(this);if(this.h)this.h.cancel(),this.h=null;else if(this.g&&0!==this.g.size){for(const a of this.g.values())a.cancel();this.g.clear()}};function Lc(a){if(null!=a.h)return a.i.concat(a.h.D);if(null!=a.g&&0!==a.g.size){let b=a.i;for(const c of a.g.values())b=b.concat(c.D);return b}return ma(a.i)};function Mc(a){if(a.W&&"function"==typeof a.W)return a.W();if("undefined"!==typeof Map&&a instanceof Map||"undefined"!==typeof Set&&a instanceof Set)return Array.from(a.values());if("string"===typeof a)return a.split("");if(ia(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function Nc(a){if(a.qa&&"function"==typeof a.qa)return a.qa();if(!a.W||"function"!=typeof a.W){if("undefined"!==typeof Map&&a instanceof Map)return Array.from(a.keys());if(!("undefined"!==typeof Set&&a instanceof Set)){if(ia(a)||"string"===typeof a){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}b=[];c=0;for(const d in a)b[c++]=d;return b}}}
function Oc(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(ia(a)||"string"===typeof a)Array.prototype.forEach.call(a,b,void 0);else for(var c=Nc(a),d=Mc(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)};var Pc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Qc(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function T(a){this.g=this.o=this.j="";this.m=null;this.s=this.l="";this.h=!1;if(a instanceof T){this.h=a.h;Rc(this,a.j);this.o=a.o;this.g=a.g;Sc(this,a.m);this.l=a.l;var b=a.i;var c=new Tc;c.i=b.i;b.g&&(c.g=new Map(b.g),c.h=b.h);Uc(this,c);this.s=a.s}else a&&(b=String(a).match(Pc))?(this.h=!1,Rc(this,b[1]||"",!0),this.o=Vc(b[2]||""),this.g=Vc(b[3]||"",!0),Sc(this,b[4]),this.l=Vc(b[5]||"",!0),Uc(this,b[6]||"",!0),this.s=Vc(b[7]||"")):(this.h=!1,this.i=new Tc(null,this.h))}
T.prototype.toString=function(){var a=[],b=this.j;b&&a.push(Wc(b,Xc,!0),":");var c=this.g;if(c||"file"==b)a.push("//"),(b=this.o)&&a.push(Wc(b,Xc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.m,null!=c&&a.push(":",String(c));if(c=this.l)this.g&&"/"!=c.charAt(0)&&a.push("/"),a.push(Wc(c,"/"==c.charAt(0)?Yc:Zc,!0));(c=this.i.toString())&&a.push("?",c);(c=this.s)&&a.push("#",Wc(c,$c));return a.join("")};function O(a){return new T(a)}
function Rc(a,b,c){a.j=c?Vc(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))}function Sc(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.m=b}else a.m=null}function Uc(a,b,c){b instanceof Tc?(a.i=b,ad(a.i,a.h)):(c||(b=Wc(b,bd)),a.i=new Tc(b,a.h))}function S(a,b,c){a.i.set(b,c)}function hc(a){S(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Date.now()).toString(36));return a}
function Vc(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function Wc(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,cd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function cd(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Xc=/[#\/\?@]/g,Zc=/[#\?:]/g,Yc=/[#\?]/g,bd=/[#\?@]/g,$c=/#/g;function Tc(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b}
function U(a){a.g||(a.g=new Map,a.h=0,a.i&&Qc(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}h=Tc.prototype;h.add=function(a,b){U(this);this.i=null;a=V(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};function dd(a,b){U(a);b=V(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a.g.delete(b))}function ed(a,b){U(a);b=V(a,b);return a.g.has(b)}
h.forEach=function(a,b){U(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};h.qa=function(){U(this);const a=Array.from(this.g.values()),b=Array.from(this.g.keys()),c=[];for(let d=0;d<b.length;d++){const e=a[d];for(let f=0;f<e.length;f++)c.push(b[d])}return c};h.W=function(a){U(this);let b=[];if("string"===typeof a)ed(this,a)&&(b=b.concat(this.g.get(V(this,a))));else{a=Array.from(this.g.values());for(let c=0;c<a.length;c++)b=b.concat(a[c])}return b};
h.set=function(a,b){U(this);this.i=null;a=V(this,a);ed(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};h.get=function(a,b){if(!a)return b;a=this.W(a);return 0<a.length?String(a[0]):b};function kc(a,b,c){dd(a,b);0<c.length&&(a.i=null,a.g.set(V(a,b),ma(c)),a.h+=c.length)}
h.toString=function(){if(this.i)return this.i;if(!this.g)return"";const a=[],b=Array.from(this.g.keys());for(var c=0;c<b.length;c++){var d=b[c];const f=encodeURIComponent(String(d)),g=this.W(d);for(d=0;d<g.length;d++){var e=f;""!==g[d]&&(e+="="+encodeURIComponent(String(g[d])));a.push(e)}}return this.i=a.join("&")};function V(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b}
function ad(a,b){b&&!a.j&&(U(a),a.i=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(dd(this,d),kc(this,e,c))},a));a.j=b};function fd(a,b){const c=new Ub;if(k.Image){const d=new Image;d.onload=la(W,c,"TestLoadImage: loaded",!0,b,d);d.onerror=la(W,c,"TestLoadImage: error",!1,b,d);d.onabort=la(W,c,"TestLoadImage: abort",!1,b,d);d.ontimeout=la(W,c,"TestLoadImage: timeout",!1,b,d);k.setTimeout(function(){if(d.ontimeout)d.ontimeout()},1E4);d.src=a}else b(!1)}
function gd(a,b){const c=new Ub,d=new AbortController,e=setTimeout(()=>{d.abort();W(c,"TestPingServer: timeout",!1,b)},1E4);fetch(a,{signal:d.signal}).then(f=>{clearTimeout(e);f.ok?W(c,"TestPingServer: ok",!0,b):W(c,"TestPingServer: server error",!1,b)}).catch(()=>{clearTimeout(e);W(c,"TestPingServer: error",!1,b)})}function W(a,b,c,d,e){try{e&&(e.onload=null,e.onerror=null,e.onabort=null,e.ontimeout=null),d(c)}catch(f){}};function hd(){this.g=new Jb}function id(a,b,c){const d=c||"";try{Oc(a,function(e,f){let g=e;n(e)&&(g=Hb(e));b.push(d+f+"="+encodeURIComponent(g))})}catch(e){throw b.push(d+"type="+encodeURIComponent("_badmap")),e;}};function jd(a){this.l=a.cc||null;this.j=a.lb||!1}r(jd,Kb);jd.prototype.g=function(){return new kd(this.l,this.j)};jd.prototype.i=function(a){return function(){return a}}({});function kd(a,b){F.call(this);this.D=a;this.o=b;this.m=void 0;this.status=this.readyState=0;this.responseType=this.responseText=this.response=this.statusText="";this.onreadystatechange=null;this.u=new Headers;this.h=null;this.B="GET";this.A="";this.g=!1;this.v=this.j=this.l=null}r(kd,F);h=kd.prototype;
h.open=function(a,b){if(0!=this.readyState)throw this.abort(),Error("Error reopening a connection");this.B=a;this.A=b;this.readyState=1;ld(this)};h.send=function(a){if(1!=this.readyState)throw this.abort(),Error("need to call open() first. ");this.g=!0;const b={headers:this.u,method:this.B,credentials:this.m,cache:void 0};a&&(b.body=a);(this.D||k).fetch(new Request(this.A,b)).then(this.Wa.bind(this),this.ha.bind(this))};
h.abort=function(){this.response=this.responseText="";this.u=new Headers;this.status=0;this.j&&this.j.cancel("Request was aborted.").catch(()=>{});1<=this.readyState&&this.g&&4!=this.readyState&&(this.g=!1,md(this));this.readyState=0};
h.Wa=function(a){if(this.g&&(this.l=a,this.h||(this.status=this.l.status,this.statusText=this.l.statusText,this.h=a.headers,this.readyState=2,ld(this)),this.g&&(this.readyState=3,ld(this),this.g)))if("arraybuffer"===this.responseType)a.arrayBuffer().then(this.Ua.bind(this),this.ha.bind(this));else if("undefined"!==typeof k.ReadableStream&&"body"in a){this.j=a.body.getReader();if(this.o){if(this.responseType)throw Error('responseType must be empty for "streamBinaryChunks" mode responses.');this.response=
[]}else this.response=this.responseText="",this.v=new TextDecoder;nd(this)}else a.text().then(this.Va.bind(this),this.ha.bind(this))};function nd(a){a.j.read().then(a.Ta.bind(a)).catch(a.ha.bind(a))}h.Ta=function(a){if(this.g){if(this.o&&a.value)this.response.push(a.value);else if(!this.o){var b=a.value?a.value:new Uint8Array(0);if(b=this.v.decode(b,{stream:!a.done}))this.response=this.responseText+=b}a.done?md(this):ld(this);3==this.readyState&&nd(this)}};
h.Va=function(a){this.g&&(this.response=this.responseText=a,md(this))};h.Ua=function(a){this.g&&(this.response=a,md(this))};h.ha=function(){this.g&&md(this)};function md(a){a.readyState=4;a.l=null;a.j=null;a.v=null;ld(a)}h.setRequestHeader=function(a,b){this.u.append(a,b)};h.getResponseHeader=function(a){return this.h?this.h.get(a.toLowerCase())||"":""};
h.getAllResponseHeaders=function(){if(!this.h)return"";const a=[],b=this.h.entries();for(var c=b.next();!c.done;)c=c.value,a.push(c[0]+": "+c[1]),c=b.next();return a.join("\r\n")};function ld(a){a.onreadystatechange&&a.onreadystatechange.call(a)}Object.defineProperty(kd.prototype,"withCredentials",{get:function(){return"include"===this.m},set:function(a){this.m=a?"include":"same-origin"}});function od(a){let b="";Oa(a,function(c,d){b+=d;b+=":";b+=c;b+="\r\n"});return b}function pd(a,b,c){a:{for(d in c){var d=!1;break a}d=!0}d||(c=od(c),"string"===typeof a?(encodeURIComponent(String(b)),null!=c&&encodeURIComponent(String(c))):S(a,b,c))};function X(a){F.call(this);this.headers=new Map;this.o=a||null;this.h=!1;this.B=this.g=null;this.H="";this.m=0;this.j="";this.l=this.F=this.u=this.D=!1;this.A=0;this.v=null;this.J="";this.K=this.L=!1}r(X,F);var qd=/^https?$/i,rd=["POST","PUT"];h=X.prototype;h.Ka=function(a){this.L=a};
h.ea=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.j="";this.m=0;this.D=!1;this.h=!0;this.g=this.o?this.o.g():ac.g();this.B=this.o?Lb(this.o):Lb(ac);this.g.onreadystatechange=p(this.Ha,this);try{this.F=!0,this.g.open(b,String(a),!0),this.F=!1}catch(f){sd(this,f);return}a=c||"";c=new Map(this.headers);if(d)if(Object.getPrototypeOf(d)===Object.prototype)for(var e in d)c.set(e,d[e]);else if("function"===
typeof d.keys&&"function"===typeof d.get)for(const f of d.keys())c.set(f,d.get(f));else throw Error("Unknown input type for opt_headers: "+String(d));d=Array.from(c.keys()).find(f=>"content-type"==f.toLowerCase());e=k.FormData&&a instanceof k.FormData;!(0<=Array.prototype.indexOf.call(rd,b,void 0))||d||e||c.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");for(const [f,g]of c)this.g.setRequestHeader(f,g);this.J&&(this.g.responseType=this.J);"withCredentials"in this.g&&this.g.withCredentials!==
this.L&&(this.g.withCredentials=this.L);try{td(this),0<this.A&&((this.K=ud(this.g))?(this.g.timeout=this.A,this.g.ontimeout=p(this.ra,this)):this.v=Bb(this.ra,this.A,this)),this.u=!0,this.g.send(a),this.u=!1}catch(f){sd(this,f)}};function ud(a){return x&&"number"===typeof a.timeout&&void 0!==a.ontimeout}h.ra=function(){"undefined"!=typeof ha&&this.g&&(this.j="Timed out after "+this.A+"ms, aborting",this.m=8,G(this,"timeout"),this.abort(8))};
function sd(a,b){a.h=!1;a.g&&(a.l=!0,a.g.abort(),a.l=!1);a.j=b;a.m=5;vd(a);wd(a)}function vd(a){a.D||(a.D=!0,G(a,"complete"),G(a,"error"))}h.abort=function(a){this.g&&this.h&&(this.h=!1,this.l=!0,this.g.abort(),this.l=!1,this.m=a||7,G(this,"complete"),G(this,"abort"),wd(this))};h.M=function(){this.g&&(this.h&&(this.h=!1,this.l=!0,this.g.abort(),this.l=!1),wd(this,!0));X.X.M.call(this)};h.Ha=function(){this.s||(this.F||this.u||this.l?xd(this):this.gb())};h.gb=function(){xd(this)};
function xd(a){if(a.h&&"undefined"!=typeof ha&&(!a.B[1]||4!=P(a)||2!=a.ba()))if(a.u&&4==P(a))Bb(a.Ha,0,a);else if(G(a,"readystatechange"),4==P(a)){a.h=!1;try{const g=a.ba();a:switch(g){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var b=!0;break a;default:b=!1}var c;if(!(c=b)){var d;if(d=0===g){var e=String(a.H).match(Pc)[1]||null;!e&&k.self&&k.self.location&&(e=k.self.location.protocol.slice(0,-1));d=!qd.test(e?e.toLowerCase():"")}c=d}if(c)G(a,"complete"),G(a,"success");else{a.m=
6;try{var f=2<P(a)?a.g.statusText:""}catch(m){f=""}a.j=f+" ["+a.ba()+"]";vd(a)}}finally{wd(a)}}}function wd(a,b){if(a.g){td(a);const c=a.g,d=a.B[0]?()=>{}:null;a.g=null;a.B=null;b||G(a,"ready");try{c.onreadystatechange=d}catch(e){}}}function td(a){a.g&&a.K&&(a.g.ontimeout=null);a.v&&(k.clearTimeout(a.v),a.v=null)}h.isActive=function(){return!!this.g};function P(a){return a.g?a.g.readyState:0}h.ba=function(){try{return 2<P(this)?this.g.status:-1}catch(a){return-1}};
h.ga=function(){try{return this.g?this.g.responseText:""}catch(a){return""}};h.Sa=function(a){if(this.g){var b=this.g.responseText;a&&0==b.indexOf(a)&&(b=b.substring(a.length));return Ib(b)}};function mc(a){try{if(!a.g)return null;if("response"in a.g)return a.g.response;switch(a.J){case "":case "text":return a.g.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in a.g)return a.g.mozResponseArrayBuffer}return null}catch(b){return null}}
function tc(a){const b={};a=(a.g&&2<=P(a)?a.g.getAllResponseHeaders()||"":"").split("\r\n");for(let d=0;d<a.length;d++){if(t(a[d]))continue;var c=Ta(a[d]);const e=c[0];c=c[1];if("string"!==typeof c)continue;c=c.trim();const f=b[e]||[];b[e]=f;f.push(c)}Pa(b,function(d){return d.join(", ")})}h.Ea=function(){return this.m};h.Oa=function(){return"string"===typeof this.j?this.j:String(this.j)};function yd(a,b,c){return c&&c.internalChannelParams?c.internalChannelParams[a]||b:b}
function zd(a){this.Da=0;this.i=[];this.j=new Ub;this.la=this.ta=this.I=this.Y=this.g=this.Ba=this.D=this.H=this.s=this.T=this.o=null;this.cb=this.V=0;this.Za=yd("failFast",!1,a);this.F=this.C=this.u=this.m=this.l=null;this.Z=!0;this.Ca=this.U=-1;this.aa=this.v=this.B=0;this.Xa=yd("baseRetryDelayMs",5E3,a);this.ib=yd("retryDelaySeedMs",1E4,a);this.ab=yd("forwardChannelMaxRetries",2,a);this.za=yd("forwardChannelRequestTimeoutMs",2E4,a);this.sa=a&&a.xmlHttpFactory||void 0;this.bb=a&&a.bc||void 0;this.Fa=
a&&a.useFetchStreams||!1;this.L=void 0;this.J=a&&a.supportsCrossDomainXhr||!1;this.K="";this.h=new Jc(a&&a.concurrentRequestLimit);this.Ga=new hd;this.P=a&&a.fastHandshake||!1;this.O=a&&a.encodeInitMessageHeaders||!1;this.P&&this.O&&(this.O=!1);this.Ya=a&&a.Zb||!1;a&&a.Aa&&this.j.Aa();a&&a.forceLongPolling&&(this.Z=!1);this.ja=!this.P&&this.Z&&a&&a.detectBufferingProxy||!1;this.ma=void 0;a&&a.longPollingTimeout&&0<a.longPollingTimeout&&(this.ma=a.longPollingTimeout);this.ka=void 0;this.S=0;this.N=
!1;this.na=this.A=null}h=zd.prototype;h.oa=8;h.G=1;h.connect=function(a,b,c,d){L(0);this.Y=a;this.H=b||{};c&&void 0!==d&&(this.H.OSID=c,this.H.OAID=d);this.F=this.Z;this.I=Dc(this,null,this.Y);Gc(this)};
function Hc(a){Ad(a);if(3==a.G){var b=a.V++,c=O(a.I);S(c,"SID",a.K);S(c,"RID",b);S(c,"TYPE","terminate");Bd(a,c);b=new cc(a,a.j,b);b.K=2;b.v=hc(O(c));c=!1;if(k.navigator&&k.navigator.sendBeacon)try{c=k.navigator.sendBeacon(b.v.toString(),"")}catch(d){}!c&&k.Image&&((new Image).src=b.v,c=!0);c||(b.g=lc(b.l,null),b.g.ea(b.v));b.F=Date.now();jc(b)}Cd(a)}function zc(a){a.g&&(vc(a),a.g.cancel(),a.g=null)}
function Ad(a){zc(a);a.u&&(k.clearTimeout(a.u),a.u=null);yc(a);a.h.cancel();a.m&&("number"===typeof a.m&&k.clearTimeout(a.m),a.m=null)}function Gc(a){if(!Kc(a.h)&&!a.m){a.m=!0;var b=a.Ja;y||ab();z||(y(),z=!0);Wa.add(b,a);a.B=0}}function Dd(a,b){if(Bc(a.h)>=a.h.j-(a.m?1:0))return!1;if(a.m)return a.i=b.D.concat(a.i),!0;if(1==a.G||2==a.G||a.B>=(a.Za?0:a.ab))return!1;a.m=M(p(a.Ja,a,b),Ed(a,a.B));a.B++;return!0}
h.Ja=function(a){if(this.m)if(this.m=null,1==this.G){if(!a){this.V=Math.floor(1E5*Math.random());a=this.V++;const e=new cc(this,this.j,a);let f=this.o;this.T&&(f?(f=Qa(f),Sa(f,this.T)):f=this.T);null!==this.s||this.O||(e.H=f,f=null);if(this.P)a:{var b=0;for(var c=0;c<this.i.length;c++){b:{var d=this.i[c];if("__data__"in d.map&&(d=d.map.__data__,"string"===typeof d)){d=d.length;break b}d=void 0}if(void 0===d)break;b+=d;if(4096<b){b=c;break a}if(4096===b||c===this.i.length-1){b=c+1;break a}}b=1E3}else b=
1E3;b=Fd(this,e,b);c=O(this.I);S(c,"RID",a);S(c,"CVER",22);this.D&&S(c,"X-HTTP-Session-Id",this.D);Bd(this,c);f&&(this.O?b="headers="+encodeURIComponent(String(od(f)))+"&"+b:this.s&&pd(c,this.s,f));Cc(this.h,e);this.Ya&&S(c,"TYPE","init");this.P?(S(c,"$req",b),S(c,"SID","null"),e.Y=!0,gc(e,c,null)):gc(e,c,b);this.G=2}}else 3==this.G&&(a?Gd(this,a):0==this.i.length||Kc(this.h)||Gd(this))};
function Gd(a,b){var c;b?c=b.m:c=a.V++;const d=O(a.I);S(d,"SID",a.K);S(d,"RID",c);S(d,"AID",a.U);Bd(a,d);a.s&&a.o&&pd(d,a.s,a.o);c=new cc(a,a.j,c,a.B+1);null===a.s&&(c.H=a.o);b&&(a.i=b.D.concat(a.i));b=Fd(a,c,1E3);c.setTimeout(Math.round(.5*a.za)+Math.round(.5*a.za*Math.random()));Cc(a.h,c);gc(c,d,b)}function Bd(a,b){a.H&&Oa(a.H,function(c,d){S(b,d,c)});a.l&&Oc({},function(c,d){S(b,d,c)})}
function Fd(a,b,c){c=Math.min(a.i.length,c);var d=a.l?p(a.l.Ra,a.l,a):null;a:{var e=a.i;let f=-1;for(;;){const g=["count="+c];-1==f?0<c?(f=e[0].g,g.push("ofs="+f)):f=0:g.push("ofs="+f);let m=!0;for(let v=0;v<c;v++){let l=e[v].g;const q=e[v].map;l-=f;if(0>l)f=Math.max(0,e[v].g-100),m=!1;else try{id(q,g,"req"+l+"_")}catch(E){d&&d(q)}}if(m){d=g.join("&");break a}}}a=a.i.splice(0,c);b.D=a;return d}function Fc(a){if(!a.g&&!a.u){a.aa=1;var b=a.Ia;y||ab();z||(y(),z=!0);Wa.add(b,a);a.v=0}}
function Ac(a){if(a.g||a.u||3<=a.v)return!1;a.aa++;a.u=M(p(a.Ia,a),Ed(a,a.v));a.v++;return!0}h.Ia=function(){this.u=null;Hd(this);if(this.ja&&!(this.N||null==this.g||0>=this.S)){var a=2*this.S;this.j.info("BP detection timer enabled: "+a);this.A=M(p(this.fb,this),a)}};h.fb=function(){this.A&&(this.A=null,this.j.info("BP detection timeout reached."),this.j.info("Buffering proxy detected and switch to long-polling!"),this.F=!1,this.N=!0,L(10),zc(this),Hd(this))};
function vc(a){null!=a.A&&(k.clearTimeout(a.A),a.A=null)}function Hd(a){a.g=new cc(a,a.j,"rpc",a.aa);null===a.s&&(a.g.H=a.o);a.g.N=0;var b=O(a.ta);S(b,"RID","rpc");S(b,"SID",a.K);S(b,"AID",a.U);S(b,"CI",a.F?"0":"1");!a.F&&a.ma&&S(b,"TO",a.ma);S(b,"TYPE","xmlhttp");Bd(a,b);a.s&&a.o&&pd(b,a.s,a.o);a.L&&a.g.setTimeout(a.L);var c=a.g;a=a.la;c.K=1;c.v=hc(O(b));c.u=null;c.P=!0;ic(c,a)}h.eb=function(){null!=this.C&&(this.C=null,zc(this),Ac(this),L(19))};
function yc(a){null!=a.C&&(k.clearTimeout(a.C),a.C=null)}function sc(a,b){var c=null;if(a.g==b){yc(a);vc(a);a.g=null;var d=2}else if(xc(a.h,b))c=b.D,Ec(a.h,b),d=1;else return;if(0!=a.G)if(b.i)if(1==d){c=b.u?b.u.length:0;b=Date.now()-b.F;var e=a.B;d=Qb();G(d,new Tb(d,c,b,e));Gc(a)}else Fc(a);else if(e=b.o,3==e||0==e&&0<b.aa||!(1==d&&Dd(a,b)||2==d&&Ac(a)))switch(c&&0<c.length&&(b=a.h,b.i=b.i.concat(c)),e){case 1:R(a,5);break;case 4:R(a,10);break;case 3:R(a,6);break;default:R(a,2)}}
function Ed(a,b){let c=a.Xa+Math.floor(Math.random()*a.ib);a.isActive()||(c*=2);return c*b}function R(a,b){a.j.info("Error code "+b);if(2==b){var c=p(a.mb,a),d=a.bb;const e=!d;d=new T(d||"//www.google.com/images/cleardot.gif");k.location&&"http"==k.location.protocol||Rc(d,"https");hc(d);e?fd(d.toString(),c):gd(d.toString(),c)}else L(2);a.G=0;a.l&&a.l.va(b);Cd(a);Ad(a)}h.mb=function(a){a?(this.j.info("Successfully pinged google.com"),L(2)):(this.j.info("Failed to ping google.com"),L(1))};
function Cd(a){a.G=0;a.na=[];if(a.l){const b=Lc(a.h);if(0!=b.length||0!=a.i.length)na(a.na,b),na(a.na,a.i),a.h.i.length=0,ma(a.i),a.i.length=0;a.l.ua()}}function Dc(a,b,c){var d=c instanceof T?O(c):new T(c);if(""!=d.g)b&&(d.g=b+"."+d.g),Sc(d,d.m);else{var e=k.location;d=e.protocol;b=b?b+"."+e.hostname:e.hostname;e=+e.port;var f=new T(null);d&&Rc(f,d);b&&(f.g=b);e&&Sc(f,e);c&&(f.l=c);d=f}c=a.D;b=a.Ba;c&&b&&S(d,c,b);S(d,"VER",a.oa);Bd(a,d);return d}
function lc(a,b,c){if(b&&!a.J)throw Error("Can't create secondary domain capable XhrIo object.");b=a.Fa&&!a.sa?new X(new jd({lb:c})):new X(a.sa);b.Ka(a.J);return b}h.isActive=function(){return!!this.l&&this.l.isActive(this)};function Id(){}h=Id.prototype;h.xa=function(){};h.wa=function(){};h.va=function(){};h.ua=function(){};h.isActive=function(){return!0};h.Ra=function(){};function Jd(){if(x&&!(10<=Number(Na)))throw Error("Environmental error: no available transport.");}Jd.prototype.g=function(a,b){return new Y(a,b)};
function Y(a,b){F.call(this);this.g=new zd(b);this.l=a;this.h=b&&b.messageUrlParams||null;a=b&&b.messageHeaders||null;b&&b.clientProtocolHeaderRequired&&(a?a["X-Client-Protocol"]="webchannel":a={"X-Client-Protocol":"webchannel"});this.g.o=a;a=b&&b.initMessageHeaders||null;b&&b.messageContentType&&(a?a["X-WebChannel-Content-Type"]=b.messageContentType:a={"X-WebChannel-Content-Type":b.messageContentType});b&&b.ya&&(a?a["X-WebChannel-Client-Profile"]=b.ya:a={"X-WebChannel-Client-Profile":b.ya});this.g.T=
a;(a=b&&b.ac)&&!t(a)&&(this.g.s=a);this.v=b&&b.supportsCrossDomainXhr||!1;this.u=b&&b.sendRawJson||!1;(b=b&&b.httpSessionIdParam)&&!t(b)&&(this.g.D=b,a=this.h,null!==a&&b in a&&(a=this.h,b in a&&delete a[b]));this.j=new Z(this)}r(Y,F);Y.prototype.m=function(){this.g.l=this.j;this.v&&(this.g.J=!0);this.g.connect(this.l,this.h||void 0)};Y.prototype.close=function(){Hc(this.g)};
Y.prototype.o=function(a){var b=this.g;if("string"===typeof a){var c={};c.__data__=a;a=c}else this.u&&(c={},c.__data__=Hb(a),a=c);b.i.push(new Ic(b.cb++,a));3==b.G&&Gc(b)};Y.prototype.M=function(){this.g.l=null;delete this.j;Hc(this.g);delete this.g;Y.X.M.call(this)};
function Kd(a){Nb.call(this);a.__headers__&&(this.headers=a.__headers__,this.statusCode=a.__status__,delete a.__headers__,delete a.__status__);var b=a.__sm__;if(b){a:{for(const c in b){a=c;break a}a=void 0}if(this.i=a)a=this.i,b=null!==b&&a in b?b[a]:void 0;this.data=b}else this.data=a}r(Kd,Nb);function Ld(){Ob.call(this);this.status=1}r(Ld,Ob);function Z(a){this.g=a}r(Z,Id);Z.prototype.xa=function(){G(this.g,"a")};Z.prototype.wa=function(a){G(this.g,new Kd(a))};
Z.prototype.va=function(a){G(this.g,new Ld(a))};Z.prototype.ua=function(){G(this.g,"b")};Jd.prototype.createWebChannel=Jd.prototype.g;Y.prototype.send=Y.prototype.o;Y.prototype.open=Y.prototype.m;Y.prototype.close=Y.prototype.close;module.exports.createWebChannelTransport=function(){return new Jd};module.exports.getStatEventTarget=function(){return Qb()};module.exports.Event=J;module.exports.Stat={ub:0,xb:1,yb:2,Rb:3,Wb:4,Tb:5,Ub:6,Sb:7,Qb:8,Vb:9,PROXY:10,NOPROXY:11,Ob:12,Kb:13,Lb:14,Jb:15,Mb:16,Nb:17,qb:18,pb:19,rb:20};Zb.NO_ERROR=0;Zb.TIMEOUT=8;Zb.HTTP_ERROR=6;
module.exports.ErrorCode=Zb;$b.COMPLETE="complete";module.exports.EventType=$b;Mb.EventType=I;I.OPEN="a";I.CLOSE="b";I.ERROR="c";I.MESSAGE="d";F.prototype.listen=F.prototype.N;module.exports.WebChannel=Mb;module.exports.FetchXmlHttpFactory=jd;X.prototype.listenOnce=X.prototype.O;X.prototype.getLastError=X.prototype.Oa;X.prototype.getLastErrorCode=X.prototype.Ea;X.prototype.getStatus=X.prototype.ba;X.prototype.getResponseJson=X.prototype.Sa;X.prototype.getResponseText=X.prototype.ga;
X.prototype.send=X.prototype.ea;X.prototype.setWithCredentials=X.prototype.Ka;module.exports.XhrIo=X;}).apply( typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self  : typeof window !== 'undefined' ? window  : {});
