/** @license
Copyright The Closure Library Authors.
SPDX-License-Identifier: Apache-2.0
*/
(function() {'use strict';var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var p=ca(this);function r(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
r("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=p[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
var ea=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;if(typeof Object.setPrototypeOf=="function")fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var la=fa;
function t(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}
r("Promise",function(a){function b(g){this.g=0;this.i=void 0;this.h=[];this.u=!1;var h=this.j();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(this.g==null){this.g=[];var h=this;this.i(function(){h.l()})}this.g.push(g)};var e=p.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(l){this.j(l)}}}this.g=null};c.prototype.j=function(g){this.i(function(){throw g;})};b.prototype.j=function(){function g(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:g(this.B),reject:g(this.l)}};b.prototype.B=function(g){if(g===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.G(g);else{a:switch(typeof g){case "object":var h=g!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.A(g):this.m(g)}};
b.prototype.A=function(g){var h=void 0;try{h=g.then}catch(k){this.l(k);return}typeof h=="function"?this.F(h,g):this.m(g)};b.prototype.l=function(g){this.o(2,g)};b.prototype.m=function(g){this.o(1,g)};b.prototype.o=function(g,h){if(this.g!=0)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.g);this.g=g;this.i=h;this.g===2&&this.D();this.v()};b.prototype.D=function(){var g=this;e(function(){if(g.C()){var h=p.console;typeof h!=="undefined"&&h.error(g.i)}},1)};b.prototype.C=
function(){if(this.u)return!1;var g=p.CustomEvent,h=p.Event,k=p.dispatchEvent;if(typeof k==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof h==="function"?g=new h("unhandledrejection",{cancelable:!0}):(g=p.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return k(g)};b.prototype.v=function(){if(this.h!=null){for(var g=0;g<this.h.length;++g)f.h(this.h[g]);this.h=null}};var f=new c;b.prototype.G=
function(g){var h=this.j();g.ha(h.resolve,h.reject)};b.prototype.F=function(g,h){var k=this.j();try{g.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(g,h){function k(u,v){return typeof u=="function"?function(G){try{l(u(G))}catch(L){m(L)}}:v}var l,m,q=new b(function(u,v){l=u;m=v});this.ha(k(g,l),k(h,m));return q};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.ha=function(g,h){function k(){switch(l.g){case 1:g(l.i);break;case 2:h(l.i);break;default:throw Error("Unexpected state: "+
l.g);}}var l=this;this.h==null?f.h(k):this.h.push(k);this.u=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var l=t(g),m=l.next();!m.done;m=l.next())d(m.value).ha(h,k)})};b.all=function(g){var h=t(g),k=h.next();return k.done?d([]):new b(function(l,m){function q(G){return function(L){u[G]=L;v--;v==0&&l(u)}}var u=[],v=0;do u.push(void 0),v++,d(k.value).ha(q(u.length-1),m),k=h.next();while(!k.done)})};return b});
function w(a,b){return Object.prototype.hasOwnProperty.call(a,b)}r("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});
r("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=t(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return l==="object"&&k!==null||l==="function"}function e(k){if(!w(k,g)){var l=new c;ba(k,g,{value:l})}}function f(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(m.get(k)!=2||m.get(l)!=3)return!1;m.delete(k);m.set(l,4);return!m.has(k)&&m.get(l)==4}catch(q){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!w(k,g))throw Error("WeakMap key fail: "+k);k[g][this.g]=l;return this};b.prototype.get=function(k){return d(k)&&w(k,g)?k[g][this.g]:void 0};b.prototype.has=function(k){return d(k)&&w(k,
g)&&w(k[g],this.g)};b.prototype.delete=function(k){return d(k)&&w(k,g)&&w(k[g],this.g)?delete k[g][this.g]:!1};return b});
r("Map",function(a){function b(){var h={};return h.P=h.next=h.head=h}function c(h,k){var l=h[1];return da(function(){if(l){for(;l.head!=h[1];)l=l.P;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(h,k){var l=k&&typeof k;l=="object"||l=="function"?f.has(k)?l=f.get(k):(l=""+ ++g,f.set(k,l)):l="p_"+k;var m=h[0][l];if(m&&w(h[0],l))for(h=0;h<m.length;h++){var q=m[h];if(k!==k&&q.key!==q.key||k===q.key)return{id:l,list:m,index:h,entry:q}}return{id:l,
list:m,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=t(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(t([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=h||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(q){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var l=d(this,h);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=k:(l.entry={next:this[1],P:this[1].P,head:this[1],key:h,value:k},l.list.push(l.entry),this[1].P.next=l.entry,this[1].P=l.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],h.entry.P.next=h.entry.next,
h.entry.next.P=h.entry.P,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].P=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=
function(h,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,h.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
r("Set",function(a){function b(c){this.g=new Map;if(c){c=t(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var c=Object.seal({x:4}),d=new a(t([c]));if(!d.has(c)||d.size!=1||d.add(c)!=d||d.size!=1||d.add({x:4})!=d||d.size!=2)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||f.value[0].x!=4||
f.value[1]!=f.value[0]?!1:e.next().done}catch(g){return!1}}())return a;b.prototype.add=function(c){c=c===0?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.g.forEach(function(f){return c.call(d,f,f,e)})};return b});r("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});
function ma(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}r("Array.prototype.values",function(a){return a?a:function(){return ma(this,function(b,c){return c})}});r("Array.prototype.keys",function(a){return a?a:function(){return ma(this,function(b){return b})}});
r("Array.prototype.entries",function(a){return a?a:function(){return ma(this,function(b,c){return[b,c]})}});r("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});
r("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)w(b,d)&&c.push([d,b[d]]);return c}});/** @license

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var na=na||{},x=this||self;function y(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}function oa(a,b,c){return a.call.apply(a.bind,arguments)}function pa(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}
function z(a,b,c){z=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?oa:pa;return z.apply(null,arguments)}function qa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}
function A(a,b){function c(){}c.prototype=b.prototype;a.X=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Qb=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};var ra=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};var sa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};function ta(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function ua(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];var e=typeof d;e=e!="object"?e:d?Array.isArray(d)?"array":e:"null";if(e=="array"||e=="object"&&typeof d.length=="number"){e=a.length||0;var f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}};function va(a,b){this.i=a;this.j=b;this.h=0;this.g=null}va.prototype.get=function(){if(this.h>0){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.i();return a};function wa(a){x.setTimeout(function(){throw a;},0)};function xa(){this.h=this.g=null}xa.prototype.add=function(a,b){var c=ya.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c};function za(){var a=Aa,b=null;a.g&&(b=a.g,a.g=a.g.next,a.g||(a.h=null),b.next=null);return b}var ya=new va(function(){return new Ba},function(a){return a.reset()});function Ba(){this.next=this.g=this.h=null}Ba.prototype.set=function(a,b){this.h=a;this.g=b;this.next=null};Ba.prototype.reset=function(){this.next=this.g=this.h=null};var Ca,Da=!1,Aa=new xa;function Ea(a,b){Ca||Fa();Da||(Ca(),Da=!0);Aa.add(a,b)}function Fa(){var a=Promise.resolve(void 0);Ca=function(){a.then(Ga)}}function Ga(){for(var a;a=za();){try{a.h.call(a.g)}catch(c){wa(c)}var b=ya;b.j(a);b.h<100&&(b.h++,a.next=b.g,b.g=a)}Da=!1};function B(){this.u=this.u;this.C=this.C}B.prototype.u=!1;B.prototype.dispose=function(){this.u||(this.u=!0,this.N())};B.prototype[Symbol.dispose]=function(){this.dispose()};B.prototype.N=function(){if(this.C)for(;this.C.length;)this.C.shift()()};function C(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1}C.prototype.h=function(){this.defaultPrevented=!0};var Ha=function(){if(!x.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};x.addEventListener("test",c,b);x.removeEventListener("test",c,b)}catch(d){}return a}();function Ia(a){return/^[\s\xa0]*$/.test(a)};function D(a,b){C.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.i=null;a&&this.init(a,b)}A(D,C);
D.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;b=a.relatedTarget;b||(c=="mouseover"?b=a.fromElement:c=="mouseout"&&(b=a.toElement));this.relatedTarget=b;d?(this.clientX=d.clientX!==void 0?d.clientX:d.pageX,this.clientY=d.clientY!==void 0?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=a.clientX!==void 0?a.clientX:a.pageX,this.clientY=a.clientY!==
void 0?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=a.pointerType;this.state=a.state;this.i=a;a.defaultPrevented&&D.X.h.call(this)};D.prototype.h=function(){D.X.h.call(this);var a=this.i;a.preventDefault?a.preventDefault():a.returnValue=!1};var Ja="closure_listenable_"+(Math.random()*1E6|0);var Ka=0;function La(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.ja=e;this.key=++Ka;this.ea=this.ga=!1}function Ma(a){a.ea=!0;a.listener=null;a.proxy=null;a.src=null;a.ja=null};function Na(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Oa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function Pa(a){var b={},c;for(c in a)b[c]=a[c];return b}var Qa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ra(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Qa.length;f++)c=Qa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Sa(a){this.src=a;this.g={};this.h=0}Sa.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);var g=Ta(a,b,d,e);g>-1?(b=a[g],c||(b.ga=!1)):(b=new La(b,this.src,f,!!d,e),b.ga=c,a.push(b));return b};function Ua(a,b){var c=b.type;if(c in a.g){var d=a.g[c],e=sa(d,b),f;(f=e>=0)&&Array.prototype.splice.call(d,e,1);f&&(Ma(b),a.g[c].length==0&&(delete a.g[c],a.h--))}}
function Ta(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.ea&&f.listener==b&&f.capture==!!c&&f.ja==d)return e}return-1};var Va="closure_lm_"+(Math.random()*1E6|0),Wa={},Xa=0;function Ya(a,b,c,d,e){if(d&&d.once)return Za(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)Ya(a,b[f],c,d,e);return null}c=$a(c);return a&&a[Ja]?a.J(b,c,y(d)?!!d.capture:!!d,e):ab(a,b,c,!1,d,e)}
function ab(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=y(e)?!!e.capture:!!e,h=bb(a);h||(a[Va]=h=new Sa(a));c=h.add(b,c,d,g,f);if(c.proxy)return c;d=cb();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)Ha||(e=g),e===void 0&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(db(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Xa++;return c}
function cb(){function a(c){return b.call(a.src,a.listener,c)}var b=eb;return a}function Za(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)Za(a,b[f],c,d,e);return null}c=$a(c);return a&&a[Ja]?a.K(b,c,y(d)?!!d.capture:!!d,e):ab(a,b,c,!0,d,e)}
function fb(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)fb(a,b[f],c,d,e);else(d=y(d)?!!d.capture:!!d,c=$a(c),a&&a[Ja])?(a=a.i,b=String(b).toString(),b in a.g&&(f=a.g[b],c=Ta(f,c,d,e),c>-1&&(Ma(f[c]),Array.prototype.splice.call(f,c,1),f.length==0&&(delete a.g[b],a.h--)))):a&&(a=bb(a))&&(b=a.g[b.toString()],a=-1,b&&(a=Ta(b,c,d,e)),(c=a>-1?b[a]:null)&&gb(c))}
function gb(a){if(typeof a!=="number"&&a&&!a.ea){var b=a.src;if(b&&b[Ja])Ua(b.i,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(db(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Xa--;(c=bb(b))?(Ua(c,a),c.h==0&&(c.src=null,b[Va]=null)):Ma(a)}}}function db(a){return a in Wa?Wa[a]:Wa[a]="on"+a}function eb(a,b){if(a.ea)a=!0;else{b=new D(b,this);var c=a.listener,d=a.ja||a.src;a.ga&&gb(a);a=c.call(d,b)}return a}
function bb(a){a=a[Va];return a instanceof Sa?a:null}var hb="__closure_events_fn_"+(Math.random()*1E9>>>0);function $a(a){if(typeof a==="function")return a;a[hb]||(a[hb]=function(b){return a.handleEvent(b)});return a[hb]};function E(){B.call(this);this.i=new Sa(this);this.M=this;this.G=null}A(E,B);E.prototype[Ja]=!0;E.prototype.removeEventListener=function(a,b,c,d){fb(this,a,b,c,d)};
function F(a,b){var c,d=a.G;if(d)for(c=[];d;d=d.G)c.push(d);a=a.M;d=b.type||b;if(typeof b==="string")b=new C(b,a);else if(b instanceof C)b.target=b.target||a;else{var e=b;b=new C(d,a);Ra(b,e)}e=!0;var f;if(c)for(f=c.length-1;f>=0;f--){var g=b.g=c[f];e=ib(g,d,!0,b)&&e}g=b.g=a;e=ib(g,d,!0,b)&&e;e=ib(g,d,!1,b)&&e;if(c)for(f=0;f<c.length;f++)g=b.g=c[f],e=ib(g,d,!1,b)&&e}
E.prototype.N=function(){E.X.N.call(this);if(this.i){var a=this.i,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,Ma(d[e]);delete a.g[c];a.h--}}this.G=null};E.prototype.J=function(a,b,c,d){return this.i.add(String(a),b,!1,c,d)};E.prototype.K=function(a,b,c,d){return this.i.add(String(a),b,!0,c,d)};
function ib(a,b,c,d){b=a.i.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.ea&&g.capture==c){var h=g.listener,k=g.ja||g.src;g.ga&&Ua(a.i,g);e=h.call(k,d)!==!1&&e}}return e&&!d.defaultPrevented};function jb(a,b){if(typeof a!=="function")if(a&&typeof a.handleEvent=="function")a=z(a.handleEvent,a);else throw Error("Invalid listener argument");return Number(b)>2147483647?-1:x.setTimeout(a,b||0)};function H(a,b,c){B.call(this);this.m=c!=null?a.bind(c):a;this.l=b;this.h=null;this.i=!1;this.g=null}H.prototype=ea(B.prototype);H.prototype.constructor=H;if(la)la(H,B);else for(var kb in B)if(kb!="prototype")if(Object.defineProperties){var lb=Object.getOwnPropertyDescriptor(B,kb);lb&&Object.defineProperty(H,kb,lb)}else H[kb]=B[kb];H.X=B.prototype;H.prototype.j=function(a){this.h=arguments;this.g?this.i=!0:mb(this)};
H.prototype.N=function(){B.prototype.N.call(this);this.g&&(x.clearTimeout(this.g),this.g=null,this.i=!1,this.h=null)};function mb(a){a.g=jb(function(){a.g=null;a.i&&(a.i=!1,mb(a))},a.l);var b=a.h;a.h=null;a.m.apply(null,b)};function nb(a){B.call(this);this.h=a;this.g={}}A(nb,B);var ob=[];function pb(a){Na(a.g,function(b,c){this.g.hasOwnProperty(c)&&gb(b)},a);a.g={}}nb.prototype.N=function(){nb.X.N.call(this);pb(this)};nb.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var qb=x.JSON.stringify;var rb=x.JSON.parse;function sb(){}sb.prototype.stringify=function(a){return x.JSON.stringify(a,void 0)};sb.prototype.parse=function(a){return x.JSON.parse(a,void 0)};function tb(){};function ub(){}var vb={OPEN:"a",jb:"b",ERROR:"c",wb:"d"};function wb(){C.call(this,"d")}A(wb,C);function xb(){C.call(this,"c")}A(xb,C);var I={},yb=null;function zb(){return yb=yb||new E}I.Ka="serverreachability";function Ab(a){C.call(this,I.Ka,a)}A(Ab,C);function Bb(a){var b=zb();F(b,new Ab(b,a))}I.STAT_EVENT="statevent";function Cb(a,b){C.call(this,I.STAT_EVENT,a);this.stat=b}A(Cb,C);function J(a){var b=zb();F(b,new Cb(b,a))}I.La="timingevent";function Db(a,b){C.call(this,I.La,a);this.size=b}A(Db,C);
function Eb(a,b){if(typeof a!=="function")throw Error("Fn must not be null and must be a function");return x.setTimeout(function(){a()},b)};function Fb(){this.g=!0}Fb.prototype.wa=function(){this.g=!1};function Gb(a,b,c,d,e,f){a.info(function(){if(a.g)if(f){var g="";for(var h=f.split("&"),k=0;k<h.length;k++){var l=h[k].split("=");if(l.length>1){var m=l[0];l=l[1];var q=m.split("_");g=q.length>=2&&q[1]=="type"?g+(m+"="+l+"&"):g+(m+"=redacted&")}}}else g=null;else g=f;return"XMLHTTP REQ ("+d+") [attempt "+e+"]: "+b+"\n"+c+"\n"+g})}
function Hb(a,b,c,d,e,f,g){a.info(function(){return"XMLHTTP RESP ("+d+") [ attempt "+e+"]: "+b+"\n"+c+"\n"+f+" "+g})}function K(a,b,c,d){a.info(function(){return"XMLHTTP TEXT ("+b+"): "+Ib(a,c)+(d?" "+d:"")})}function Jb(a,b){a.info(function(){return"TIMEOUT: "+b})}Fb.prototype.info=function(){};
function Ib(a,b){if(!a.g)return b;if(!b)return null;try{var c=JSON.parse(b);if(c)for(a=0;a<c.length;a++)if(Array.isArray(c[a])){var d=c[a];if(!(d.length<2)){var e=d[1];if(Array.isArray(e)&&!(e.length<1)){var f=e[0];if(f!="noop"&&f!="stop"&&f!="close")for(var g=1;g<e.length;g++)e[g]=""}}}return qb(c)}catch(h){return b}};var Kb={NO_ERROR:0,fb:1,sb:2,rb:3,mb:4,qb:5,tb:6,Ia:7,TIMEOUT:8,xb:9};var Lb={kb:"complete",Hb:"success",ERROR:"error",Ia:"abort",zb:"ready",Ab:"readystatechange",TIMEOUT:"timeout",ub:"incrementaldata",yb:"progress",nb:"downloadprogress",Pb:"uploadprogress"};var Mb;function Nb(){}A(Nb,tb);Nb.prototype.g=function(){return new XMLHttpRequest};Mb=new Nb;function M(a){return encodeURIComponent(String(a))}function Ob(a){var b=1;a=a.split(":");for(var c=[];b>0&&a.length;)c.push(a.shift()),b--;a.length&&c.push(a.join(":"));return c};function N(a,b,c,d){this.j=a;this.i=b;this.l=c;this.T=d||1;this.W=new nb(this);this.H=45E3;this.J=null;this.o=!1;this.u=this.B=this.A=this.M=this.F=this.U=this.D=null;this.G=[];this.g=null;this.C=0;this.m=this.v=null;this.Z=-1;this.K=!1;this.R=0;this.O=null;this.Y=this.L=this.V=this.S=!1;this.h=new Pb}function Pb(){this.i=null;this.g="";this.h=!1}var Qb={},Rb={};function Sb(a,b,c){a.M=1;a.A=Tb(O(b));a.u=c;a.S=!0;Ub(a,null)}
function Ub(a,b){a.F=Date.now();Vb(a);a.B=O(a.A);var c=a.B,d=a.T;Array.isArray(d)||(d=[String(d)]);Wb(c.i,"t",d);a.C=0;c=a.j.K;a.h=new Pb;a.g=Xb(a.j,c?b:null,!a.u);a.R>0&&(a.O=new H(z(a.aa,a,a.g),a.R));b=a.W;c=a.g;d=a.ca;var e="readystatechange";Array.isArray(e)||(e&&(ob[0]=e.toString()),e=ob);for(var f=0;f<e.length;f++){var g=Ya(c,e[f],d||b.handleEvent,!1,b.h||b);if(!g)break;b.g[g.key]=g}b=a.J?Pa(a.J):{};a.u?(a.v||(a.v="POST"),b["Content-Type"]="application/x-www-form-urlencoded",a.g.fa(a.B,a.v,
a.u,b)):(a.v="GET",a.g.fa(a.B,a.v,null,b));Bb(1);Gb(a.i,a.v,a.B,a.l,a.T,a.u)}N.prototype.ca=function(a){a=a.target;var b=this.O;b&&P(a)==3?b.j():this.aa(a)};
N.prototype.aa=function(a){try{if(a==this.g)a:{var b=P(this.g),c=this.g.Aa(),d=this.g.da();if(!(b<3)&&(b!=3||this.g&&(this.h.h||this.g.na()||Yb(this.g)))){this.K||b!=4||c==7||(c==8||d<=0?Bb(3):Bb(2));Zb(this);var e=this.g.da();this.Z=e;var f=$b(this);this.o=e==200;Hb(this.i,this.v,this.B,this.l,this.T,b,e);if(this.o){if(this.V&&!this.L){b:{if(this.g){var g,h=this.g;if((g=h.g?h.g.getResponseHeader("X-HTTP-Initial-Response"):null)&&!Ia(g)){var k=g;break b}}k=null}if(a=k)K(this.i,this.l,a,"Initial handshake response via X-HTTP-Initial-Response"),
this.L=!0,ac(this,a);else{this.o=!1;this.m=3;J(12);Q(this);bc(this);break a}}if(this.S){a=!0;for(var l;!this.K&&this.C<f.length;)if(l=cc(this,f),l==Rb){b==4&&(this.m=4,J(14),a=!1);K(this.i,this.l,null,"[Incomplete Response]");break}else if(l==Qb){this.m=4;J(15);K(this.i,this.l,f,"[Invalid Chunk]");a=!1;break}else K(this.i,this.l,l,null),ac(this,l);dc(this)&&this.C!=0&&(this.h.g=this.h.g.slice(this.C),this.C=0);b!=4||f.length!=0||this.h.h||(this.m=1,J(16),a=!1);this.o=this.o&&a;if(!a)K(this.i,this.l,
f,"[Invalid Chunked Response]"),Q(this),bc(this);else if(f.length>0&&!this.Y){this.Y=!0;var m=this.j;m.g==this&&m.ba&&!m.O&&(m.j.info("Great, no buffering proxy detected. Bytes received: "+f.length),ec(m),m.O=!0,J(11))}}else K(this.i,this.l,f,null),ac(this,f);b==4&&Q(this);this.o&&!this.K&&(b==4?fc(this.j,this):(this.o=!1,Vb(this)))}else hc(this.g),e==400&&f.indexOf("Unknown SID")>0?(this.m=3,J(12)):(this.m=0,J(13)),Q(this),bc(this)}}}catch(q){}finally{}};
function $b(a){if(!dc(a))return a.g.na();var b=Yb(a.g);if(b==="")return"";var c="",d=b.length,e=P(a.g)==4;if(!a.h.i){if(typeof TextDecoder==="undefined")return Q(a),bc(a),"";a.h.i=new x.TextDecoder}for(var f=0;f<d;f++)a.h.h=!0,c+=a.h.i.decode(b[f],{stream:!(e&&f==d-1)});b.length=0;a.h.g+=c;a.C=0;return a.h.g}function dc(a){return a.g?a.v=="GET"&&a.M!=2&&a.j.Ca:!1}
function cc(a,b){var c=a.C,d=b.indexOf("\n",c);if(d==-1)return Rb;c=Number(b.substring(c,d));if(isNaN(c))return Qb;d+=1;if(d+c>b.length)return Rb;b=b.slice(d,d+c);a.C=d+c;return b}N.prototype.cancel=function(){this.K=!0;Q(this)};function Vb(a){a.U=Date.now()+a.H;ic(a,a.H)}function ic(a,b){if(a.D!=null)throw Error("WatchDog timer not null");a.D=Eb(z(a.ba,a),b)}function Zb(a){a.D&&(x.clearTimeout(a.D),a.D=null)}
N.prototype.ba=function(){this.D=null;var a=Date.now();a-this.U>=0?(Jb(this.i,this.B),this.M!=2&&(Bb(3),J(17)),Q(this),this.m=2,bc(this)):ic(this,this.U-a)};function bc(a){a.j.I==0||a.K||fc(a.j,a)}function Q(a){Zb(a);var b=a.O;b&&typeof b.dispose=="function"&&b.dispose();a.O=null;pb(a.W);a.g&&(b=a.g,a.g=null,b.abort(),b.dispose())}
function ac(a,b){try{var c=a.j;if(c.I!=0&&(c.g==a||jc(c.h,a)))if(!a.L&&jc(c.h,a)&&c.I==3){try{var d=c.Da.g.parse(b)}catch(ka){d=null}if(Array.isArray(d)&&d.length==3){var e=d;if(e[0]==0)a:{if(!c.v){if(c.g)if(c.g.F+3E3<a.F)kc(c),lc(c);else break a;mc(c);J(18)}}else c.za=e[1],0<c.za-c.V&&e[2]<37500&&c.F&&c.A==0&&!c.C&&(c.C=Eb(z(c.Xa,c),6E3));nc(c.h)<=1&&c.va&&(c.va=void 0)}else R(c,11)}else if((a.L||c.g==a)&&kc(c),!Ia(b))for(e=c.Da.g.parse(b),b=0;b<e.length;b++){var f=e[b];c.V=f[0];f=f[1];if(c.I==2)if(f[0]==
"c"){c.L=f[1];c.ca=f[2];var g=f[3];g!=null&&(c.ma=g,c.j.info("VER="+c.ma));var h=f[4];h!=null&&(c.Ba=h,c.j.info("SVER="+c.Ba));var k=f[5];k!=null&&typeof k==="number"&&k>0&&(d=1.5*k,c.M=d,c.j.info("backChannelRequestTimeoutMs_="+d));d=c;var l=a.g;if(l){var m=l.g?l.g.getResponseHeader("X-Client-Wire-Protocol"):null;if(m){var q=d.h;q.g||m.indexOf("spdy")==-1&&m.indexOf("quic")==-1&&m.indexOf("h2")==-1||(q.j=q.l,q.g=new Set,q.h&&(oc(q,q.h),q.h=null))}if(d.G){var u=l.g?l.g.getResponseHeader("X-HTTP-Session-Id"):
null;u&&(d.ya=u,S(d.J,d.G,u))}}c.I=3;c.l&&c.l.ta();c.ba&&(c.T=Date.now()-a.F,c.j.info("Handshake RTT: "+c.T+"ms"));d=c;var v=a;d.pa=pc(d,d.K?d.ca:null,d.Y);if(v.L){qc(d.h,v);var G=v,L=d.M;L&&(G.H=L);G.D&&(Zb(G),Vb(G));d.g=v}else rc(d);c.i.length>0&&sc(c)}else f[0]!="stop"&&f[0]!="close"||R(c,7);else c.I==3&&(f[0]=="stop"||f[0]=="close"?f[0]=="stop"?R(c,7):tc(c):f[0]!="noop"&&c.l&&c.l.sa(f),c.A=0)}Bb(4)}catch(ka){}};function uc(a,b){this.g=a;this.map=b};function vc(a){this.l=a||10;x.PerformanceNavigationTiming?(a=x.performance.getEntriesByType("navigation"),a=a.length>0&&(a[0].nextHopProtocol=="hq"||a[0].nextHopProtocol=="h2")):a=!!(x.chrome&&x.chrome.loadTimes&&x.chrome.loadTimes()&&x.chrome.loadTimes().wasFetchedViaSpdy);this.j=a?this.l:1;this.g=null;this.j>1&&(this.g=new Set);this.h=null;this.i=[]}function wc(a){return a.h?!0:a.g?a.g.size>=a.j:!1}function nc(a){return a.h?1:a.g?a.g.size:0}function jc(a,b){return a.h?a.h==b:a.g?a.g.has(b):!1}
function oc(a,b){a.g?a.g.add(b):a.h=b}function qc(a,b){a.h&&a.h==b?a.h=null:a.g&&a.g.has(b)&&a.g.delete(b)}vc.prototype.cancel=function(){this.i=xc(this);if(this.h)this.h.cancel(),this.h=null;else if(this.g&&this.g.size!==0){for(var a=t(this.g.values()),b=a.next();!b.done;b=a.next())b.value.cancel();this.g.clear()}};
function xc(a){if(a.h!=null)return a.i.concat(a.h.G);if(a.g!=null&&a.g.size!==0){var b=a.i;a=t(a.g.values());for(var c=a.next();!c.done;c=a.next())b=b.concat(c.value.G);return b}return ta(a.i)};var yc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function zc(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(d>=0){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function T(a){this.g=this.o=this.j="";this.u=null;this.m=this.h="";this.l=!1;var b;a instanceof T?(this.l=a.l,Ac(this,a.j),this.o=a.o,this.g=a.g,Bc(this,a.u),this.h=a.h,Cc(this,Fc(a.i)),this.m=a.m):a&&(b=String(a).match(yc))?(this.l=!1,Ac(this,b[1]||"",!0),this.o=Gc(b[2]||""),this.g=Gc(b[3]||"",!0),Bc(this,b[4]),this.h=Gc(b[5]||"",!0),Cc(this,b[6]||"",!0),this.m=Gc(b[7]||"")):(this.l=!1,this.i=new Hc(null,this.l))}
T.prototype.toString=function(){var a=[],b=this.j;b&&a.push(Ic(b,Jc,!0),":");var c=this.g;if(c||b=="file")a.push("//"),(b=this.o)&&a.push(Ic(b,Jc,!0),"@"),a.push(M(c).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.u,c!=null&&a.push(":",String(c));if(c=this.h)this.g&&c.charAt(0)!="/"&&a.push("/"),a.push(Ic(c,c.charAt(0)=="/"?Kc:Lc,!0));(c=this.i.toString())&&a.push("?",c);(c=this.m)&&a.push("#",Ic(c,Mc));return a.join("")};
T.prototype.resolve=function(a){var b=O(this),c=!!a.j;c?Ac(b,a.j):c=!!a.o;c?b.o=a.o:c=!!a.g;c?b.g=a.g:c=a.u!=null;var d=a.h;if(c)Bc(b,a.u);else if(c=!!a.h){if(d.charAt(0)!="/")if(this.g&&!this.h)d="/"+d;else{var e=b.h.lastIndexOf("/");e!=-1&&(d=b.h.slice(0,e+1)+d)}e=d;if(e==".."||e==".")d="";else if(e.indexOf("./")!=-1||e.indexOf("/.")!=-1){d=e.lastIndexOf("/",0)==0;e=e.split("/");for(var f=[],g=0;g<e.length;){var h=e[g++];h=="."?d&&g==e.length&&f.push(""):h==".."?((f.length>1||f.length==1&&f[0]!=
"")&&f.pop(),d&&g==e.length&&f.push("")):(f.push(h),d=!0)}d=f.join("/")}else d=e}c?b.h=d:c=a.i.toString()!=="";c?Cc(b,Fc(a.i)):c=!!a.m;c&&(b.m=a.m);return b};function O(a){return new T(a)}function Ac(a,b,c){a.j=c?Gc(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))}function Bc(a,b){if(b){b=Number(b);if(isNaN(b)||b<0)throw Error("Bad port number "+b);a.u=b}else a.u=null}function Cc(a,b,c){b instanceof Hc?(a.i=b,Nc(a.i,a.l)):(c||(b=Ic(b,Oc)),a.i=new Hc(b,a.l))}function S(a,b,c){a.i.set(b,c)}
function Tb(a){S(a,"zx",Math.floor(Math.random()*2147483648).toString(36)+Math.abs(Math.floor(Math.random()*2147483648)^Date.now()).toString(36));return a}function Gc(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function Ic(a,b,c){return typeof a==="string"?(a=encodeURI(a).replace(b,Pc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function Pc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}
var Jc=/[#\/\?@]/g,Lc=/[#\?:]/g,Kc=/[#\?]/g,Oc=/[#\?@]/g,Mc=/#/g;function Hc(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b}function U(a){a.g||(a.g=new Map,a.h=0,a.i&&zc(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}n=Hc.prototype;n.add=function(a,b){U(this);this.i=null;a=V(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};function Qc(a,b){U(a);b=V(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a.g.delete(b))}
function Rc(a,b){U(a);b=V(a,b);return a.g.has(b)}n.forEach=function(a,b){U(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};function Sc(a,b){U(a);var c=[];if(typeof b==="string")Rc(a,b)&&(c=c.concat(a.g.get(V(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c}n.set=function(a,b){U(this);this.i=null;a=V(this,a);Rc(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};
n.get=function(a,b){if(!a)return b;a=Sc(this,a);return a.length>0?String(a[0]):b};function Wb(a,b,c){Qc(a,b);c.length>0&&(a.i=null,a.g.set(V(a,b),ta(c)),a.h+=c.length)}n.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=M(d);d=Sc(this,d);for(var f=0;f<d.length;f++){var g=e;d[f]!==""&&(g+="="+M(d[f]));a.push(g)}}return this.i=a.join("&")};
function Fc(a){var b=new Hc;b.i=a.i;a.g&&(b.g=new Map(a.g),b.h=a.h);return b}function V(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b}function Nc(a,b){b&&!a.j&&(U(a),a.i=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Qc(this,d),Wb(this,e,c))},a));a.j=b};function Tc(a,b){var c=new Fb;if(x.Image){var d=new Image;d.onload=qa(W,c,"TestLoadImage: loaded",!0,b,d);d.onerror=qa(W,c,"TestLoadImage: error",!1,b,d);d.onabort=qa(W,c,"TestLoadImage: abort",!1,b,d);d.ontimeout=qa(W,c,"TestLoadImage: timeout",!1,b,d);x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},1E4);d.src=a}else b(!1)}
function Uc(a,b){var c=new Fb,d=new AbortController,e=setTimeout(function(){d.abort();W(c,"TestPingServer: timeout",!1,b)},1E4);fetch(a,{signal:d.signal}).then(function(f){clearTimeout(e);f.ok?W(c,"TestPingServer: ok",!0,b):W(c,"TestPingServer: server error",!1,b)}).catch(function(){clearTimeout(e);W(c,"TestPingServer: error",!1,b)})}function W(a,b,c,d,e){try{e&&(e.onload=null,e.onerror=null,e.onabort=null,e.ontimeout=null),d(c)}catch(f){}};function Vc(){this.g=new sb};function Wc(a){this.i=a.Ub||null;this.h=a.cb||!1}A(Wc,tb);Wc.prototype.g=function(){return new Xc(this.i,this.h)};function Xc(a,b){E.call(this);this.H=a;this.o=b;this.m=void 0;this.status=this.readyState=0;this.responseType=this.responseText=this.response=this.statusText="";this.onreadystatechange=null;this.A=new Headers;this.h=null;this.F="GET";this.D="";this.g=!1;this.B=this.j=this.l=null;this.v=new AbortController}A(Xc,E);n=Xc.prototype;
n.open=function(a,b){if(this.readyState!=0)throw this.abort(),Error("Error reopening a connection");this.F=a;this.D=b;this.readyState=1;Yc(this)};n.send=function(a){if(this.readyState!=1)throw this.abort(),Error("need to call open() first. ");if(this.v.signal.aborted)throw this.abort(),Error("Request was aborted.");this.g=!0;var b={headers:this.A,method:this.F,credentials:this.m,cache:void 0,signal:this.v.signal};a&&(b.body=a);(this.H||x).fetch(new Request(this.D,b)).then(this.Ra.bind(this),this.ia.bind(this))};
n.abort=function(){this.response=this.responseText="";this.A=new Headers;this.status=0;this.v.abort();this.j&&this.j.cancel("Request was aborted.").catch(function(){});this.readyState>=1&&this.g&&this.readyState!=4&&(this.g=!1,Zc(this));this.readyState=0};
n.Ra=function(a){if(this.g&&(this.l=a,this.h||(this.status=this.l.status,this.statusText=this.l.statusText,this.h=a.headers,this.readyState=2,Yc(this)),this.g&&(this.readyState=3,Yc(this),this.g)))if(this.responseType==="arraybuffer")a.arrayBuffer().then(this.Pa.bind(this),this.ia.bind(this));else if(typeof x.ReadableStream!=="undefined"&&"body"in a){this.j=a.body.getReader();if(this.o){if(this.responseType)throw Error('responseType must be empty for "streamBinaryChunks" mode responses.');this.response=
[]}else this.response=this.responseText="",this.B=new TextDecoder;$c(this)}else a.text().then(this.Qa.bind(this),this.ia.bind(this))};function $c(a){a.j.read().then(a.Oa.bind(a)).catch(a.ia.bind(a))}n.Oa=function(a){if(this.g){if(this.o&&a.value)this.response.push(a.value);else if(!this.o){var b=a.value?a.value:new Uint8Array(0);if(b=this.B.decode(b,{stream:!a.done}))this.response=this.responseText+=b}a.done?Zc(this):Yc(this);this.readyState==3&&$c(this)}};
n.Qa=function(a){this.g&&(this.response=this.responseText=a,Zc(this))};n.Pa=function(a){this.g&&(this.response=a,Zc(this))};n.ia=function(){this.g&&Zc(this)};function Zc(a){a.readyState=4;a.l=null;a.j=null;a.B=null;Yc(a)}n.setRequestHeader=function(a,b){this.A.append(a,b)};n.getResponseHeader=function(a){return this.h?this.h.get(a.toLowerCase())||"":""};
n.getAllResponseHeaders=function(){if(!this.h)return"";for(var a=[],b=this.h.entries(),c=b.next();!c.done;)c=c.value,a.push(c[0]+": "+c[1]),c=b.next();return a.join("\r\n")};function Yc(a){a.onreadystatechange&&a.onreadystatechange.call(a)}Object.defineProperty(Xc.prototype,"withCredentials",{get:function(){return this.m==="include"},set:function(a){this.m=a?"include":"same-origin"}});function ad(a){var b="";Na(a,function(c,d){b+=d;b+=":";b+=c;b+="\r\n"});return b}function bd(a,b,c){a:{for(d in c){var d=!1;break a}d=!0}d||(c=ad(c),typeof a==="string"?(M(b),c!=null&&M(c)):S(a,b,c))};function X(a){E.call(this);this.headers=new Map;this.L=a||null;this.h=!1;this.g=null;this.D="";this.o=0;this.l="";this.j=this.B=this.v=this.A=!1;this.m=null;this.F="";this.H=!1}A(X,E);var cd=/^https?$/i,dd=["POST","PUT"];n=X.prototype;n.Ha=function(a){this.H=a};
n.fa=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.o=0;this.A=!1;this.h=!0;this.g=this.L?this.L.g():Mb.g();this.g.onreadystatechange=ra(z(this.Ea,this));try{this.B=!0,this.g.open(b,String(a),!0),this.B=!1}catch(g){ed(this,g);return}a=c||"";c=new Map(this.headers);if(d)if(Object.getPrototypeOf(d)===Object.prototype)for(var e in d)c.set(e,d[e]);else if(typeof d.keys==="function"&&
typeof d.get==="function"){e=t(d.keys());for(var f=e.next();!f.done;f=e.next())f=f.value,c.set(f,d.get(f))}else throw Error("Unknown input type for opt_headers: "+String(d));d=Array.from(c.keys()).find(function(g){return"content-type"==g.toLowerCase()});e=x.FormData&&a instanceof x.FormData;!(sa(dd,b)>=0)||d||e||c.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b=t(c);for(d=b.next();!d.done;d=b.next())c=t(d.value),d=c.next().value,c=c.next().value,this.g.setRequestHeader(d,c);
this.F&&(this.g.responseType=this.F);"withCredentials"in this.g&&this.g.withCredentials!==this.H&&(this.g.withCredentials=this.H);try{this.m&&(clearTimeout(this.m),this.m=null),this.v=!0,this.g.send(a),this.v=!1}catch(g){ed(this,g)}};function ed(a,b){a.h=!1;a.g&&(a.j=!0,a.g.abort(),a.j=!1);a.l=b;a.o=5;fd(a);gd(a)}function fd(a){a.A||(a.A=!0,F(a,"complete"),F(a,"error"))}
n.abort=function(a){this.g&&this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1,this.o=a||7,F(this,"complete"),F(this,"abort"),gd(this))};n.N=function(){this.g&&(this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1),gd(this,!0));X.X.N.call(this)};n.Ea=function(){this.u||(this.B||this.v||this.j?hd(this):this.Za())};n.Za=function(){hd(this)};
function hd(a){if(a.h&&typeof na!="undefined")if(a.v&&P(a)==4)setTimeout(a.Ea.bind(a),0);else if(F(a,"readystatechange"),P(a)==4){a.h=!1;try{var b=a.da();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=b===0){var f=String(a.D).match(yc)[1]||null;!f&&x.self&&x.self.location&&(f=x.self.location.protocol.slice(0,-1));e=!cd.test(f?f.toLowerCase():"")}d=e}if(d)F(a,"complete"),F(a,"success");else{a.o=6;try{var g=P(a)>
2?a.g.statusText:""}catch(h){g=""}a.l=g+" ["+a.da()+"]";fd(a)}}finally{gd(a)}}}function gd(a,b){if(a.g){a.m&&(clearTimeout(a.m),a.m=null);var c=a.g;a.g=null;b||F(a,"ready");try{c.onreadystatechange=null}catch(d){}}}n.isActive=function(){return!!this.g};function P(a){return a.g?a.g.readyState:0}n.da=function(){try{return P(this)>2?this.g.status:-1}catch(a){return-1}};n.na=function(){try{return this.g?this.g.responseText:""}catch(a){return""}};
n.Na=function(a){if(this.g){var b=this.g.responseText;a&&b.indexOf(a)==0&&(b=b.substring(a.length));return rb(b)}};function Yb(a){try{if(!a.g)return null;if("response"in a.g)return a.g.response;switch(a.F){case "":case "text":return a.g.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in a.g)return a.g.mozResponseArrayBuffer}return null}catch(b){return null}}
function hc(a){var b={};a=(a.g&&P(a)>=2?a.g.getAllResponseHeaders()||"":"").split("\r\n");for(var c=0;c<a.length;c++)if(!Ia(a[c])){var d=Ob(a[c]),e=d[0];d=d[1];if(typeof d==="string"){d=d.trim();var f=b[e]||[];b[e]=f;f.push(d)}}Oa(b,function(g){return g.join(", ")})}n.Aa=function(){return this.o};n.Ja=function(){return typeof this.l==="string"?this.l:String(this.l)};function id(a,b,c){return c&&c.internalChannelParams?c.internalChannelParams[a]||b:b}
function jd(a){this.Ba=0;this.i=[];this.j=new Fb;this.ca=this.pa=this.J=this.Y=this.g=this.ya=this.G=this.H=this.u=this.U=this.o=null;this.ab=this.W=0;this.Ua=id("failFast",!1,a);this.F=this.C=this.v=this.m=this.l=null;this.Z=!0;this.za=this.V=-1;this.aa=this.A=this.D=0;this.Sa=id("baseRetryDelayMs",5E3,a);this.bb=id("retryDelaySeedMs",1E4,a);this.Va=id("forwardChannelMaxRetries",2,a);this.xa=id("forwardChannelRequestTimeoutMs",2E4,a);this.oa=a&&a.xmlHttpFactory||void 0;this.Wa=a&&a.Tb||void 0;this.Ca=
a&&a.useFetchStreams||!1;this.M=void 0;this.K=a&&a.supportsCrossDomainXhr||!1;this.L="";this.h=new vc(a&&a.concurrentRequestLimit);this.Da=new Vc;this.S=a&&a.fastHandshake||!1;this.R=a&&a.encodeInitMessageHeaders||!1;this.S&&this.R&&(this.R=!1);this.Ta=a&&a.Rb||!1;a&&a.wa&&this.j.wa();a&&a.forceLongPolling&&(this.Z=!1);this.ba=!this.S&&this.Z&&a&&a.detectBufferingProxy||!1;this.ka=void 0;a&&a.longPollingTimeout&&a.longPollingTimeout>0&&(this.ka=a.longPollingTimeout);this.va=void 0;this.T=0;this.O=
!1;this.la=this.B=null}n=jd.prototype;n.ma=8;n.I=1;n.connect=function(a,b,c,d){J(0);this.Y=a;this.H=b||{};c&&d!==void 0&&(this.H.OSID=c,this.H.OAID=d);this.F=this.Z;this.J=pc(this,null,this.Y);sc(this)};
function tc(a){kd(a);if(a.I==3){var b=a.W++,c=O(a.J);S(c,"SID",a.L);S(c,"RID",b);S(c,"TYPE","terminate");ld(a,c);b=new N(a,a.j,b);b.M=2;b.A=Tb(O(c));c=!1;if(x.navigator&&x.navigator.sendBeacon)try{c=x.navigator.sendBeacon(b.A.toString(),"")}catch(d){}!c&&x.Image&&((new Image).src=b.A,c=!0);c||(b.g=Xb(b.j,null),b.g.fa(b.A));b.F=Date.now();Vb(b)}md(a)}function lc(a){a.g&&(ec(a),a.g.cancel(),a.g=null)}
function kd(a){lc(a);a.v&&(x.clearTimeout(a.v),a.v=null);kc(a);a.h.cancel();a.m&&(typeof a.m==="number"&&x.clearTimeout(a.m),a.m=null)}function sc(a){wc(a.h)||a.m||(a.m=!0,Ea(a.Ga,a),a.D=0)}function nd(a,b){if(nc(a.h)>=a.h.j-(a.m?1:0))return!1;if(a.m)return a.i=b.G.concat(a.i),!0;if(a.I==1||a.I==2||a.D>=(a.Ua?0:a.Va))return!1;a.m=Eb(z(a.Ga,a,b),od(a,a.D));a.D++;return!0}
n.Ga=function(a){if(this.m)if(this.m=null,this.I==1){if(!a){this.W=Math.floor(Math.random()*1E5);a=this.W++;var b=new N(this,this.j,a),c=this.o;this.U&&(c?(c=Pa(c),Ra(c,this.U)):c=this.U);this.u!==null||this.R||(b.J=c,c=null);var d;if(this.S)a:{for(var e=d=0;e<this.i.length;e++){b:{var f=this.i[e];if("__data__"in f.map&&(f=f.map.__data__,typeof f==="string")){f=f.length;break b}f=void 0}if(f===void 0)break;d+=f;if(d>4096){d=e;break a}if(d===4096||e===this.i.length-1){d=e+1;break a}}d=1E3}else d=1E3;
d=pd(this,b,d);e=O(this.J);S(e,"RID",a);S(e,"CVER",22);this.G&&S(e,"X-HTTP-Session-Id",this.G);ld(this,e);c&&(this.R?d="headers="+M(ad(c))+"&"+d:this.u&&bd(e,this.u,c));oc(this.h,b);this.Ta&&S(e,"TYPE","init");this.S?(S(e,"$req",d),S(e,"SID","null"),b.V=!0,Sb(b,e,null)):Sb(b,e,d);this.I=2}}else this.I==3&&(a?qd(this,a):this.i.length==0||wc(this.h)||qd(this))};
function qd(a,b){var c;b?c=b.l:c=a.W++;var d=O(a.J);S(d,"SID",a.L);S(d,"RID",c);S(d,"AID",a.V);ld(a,d);a.u&&a.o&&bd(d,a.u,a.o);c=new N(a,a.j,c,a.D+1);a.u===null&&(c.J=a.o);b&&(a.i=b.G.concat(a.i));b=pd(a,c,1E3);c.H=Math.round(a.xa*.5)+Math.round(a.xa*.5*Math.random());oc(a.h,c);Sb(c,d,b)}function ld(a,b){a.H&&Na(a.H,function(c,d){S(b,d,c)});a.l&&Na({},function(c,d){S(b,d,c)})}
function pd(a,b,c){c=Math.min(a.i.length,c);var d=a.l?z(a.l.Ma,a.l,a):null;a:{for(var e=a.i,f=-1;;){var g=["count="+c];f==-1?c>0?(f=e[0].g,g.push("ofs="+f)):f=0:g.push("ofs="+f);for(var h=!0,k=0;k<c;k++){var l=e[k].g,m=e[k].map;l-=f;if(l<0)f=Math.max(0,e[k].g-100),h=!1;else try{l="req"+l+"_"||"";try{var q=m instanceof Map?m:Object.entries(m);for(var u=t(q),v=u.next();!v.done;v=u.next()){var G=t(v.value),L=G.next().value,ka=G.next().value,Dc=ka;y(ka)&&(Dc=qb(ka));g.push(l+L+"="+encodeURIComponent(Dc))}}catch(Ec){throw g.push(l+
"type="+encodeURIComponent("_badmap")),Ec;}}catch(Ec){d&&d(m)}}if(h){q=g.join("&");break a}}q=void 0}a=a.i.splice(0,c);b.G=a;return q}function rc(a){a.g||a.v||(a.aa=1,Ea(a.Fa,a),a.A=0)}function mc(a){if(a.g||a.v||a.A>=3)return!1;a.aa++;a.v=Eb(z(a.Fa,a),od(a,a.A));a.A++;return!0}n.Fa=function(){this.v=null;rd(this);if(this.ba&&!(this.O||this.g==null||this.T<=0)){var a=4*this.T;this.j.info("BP detection timer enabled: "+a);this.B=Eb(z(this.Ya,this),a)}};
n.Ya=function(){this.B&&(this.B=null,this.j.info("BP detection timeout reached."),this.j.info("Buffering proxy detected and switch to long-polling!"),this.F=!1,this.O=!0,J(10),lc(this),rd(this))};function ec(a){a.B!=null&&(x.clearTimeout(a.B),a.B=null)}
function rd(a){a.g=new N(a,a.j,"rpc",a.aa);a.u===null&&(a.g.J=a.o);a.g.R=0;var b=O(a.pa);S(b,"RID","rpc");S(b,"SID",a.L);S(b,"AID",a.V);S(b,"CI",a.F?"0":"1");!a.F&&a.ka&&S(b,"TO",a.ka);S(b,"TYPE","xmlhttp");ld(a,b);a.u&&a.o&&bd(b,a.u,a.o);a.M&&(a.g.H=a.M);var c=a.g;a=a.ca;c.M=1;c.A=Tb(O(b));c.u=null;c.S=!0;Ub(c,a)}n.Xa=function(){this.C!=null&&(this.C=null,lc(this),mc(this),J(19))};function kc(a){a.C!=null&&(x.clearTimeout(a.C),a.C=null)}
function fc(a,b){var c=null;if(a.g==b){kc(a);ec(a);a.g=null;var d=2}else if(jc(a.h,b))c=b.G,qc(a.h,b),d=1;else return;if(a.I!=0)if(b.o)if(d==1){c=b.u?b.u.length:0;b=Date.now()-b.F;var e=a.D;d=zb();F(d,new Db(d,c,b,e));sc(a)}else rc(a);else if(e=b.m,e==3||e==0&&b.Z>0||!(d==1&&nd(a,b)||d==2&&mc(a)))switch(c&&c.length>0&&(b=a.h,b.i=b.i.concat(c)),e){case 1:R(a,5);break;case 4:R(a,10);break;case 3:R(a,6);break;default:R(a,2)}}
function od(a,b){var c=a.Sa+Math.floor(Math.random()*a.bb);a.isActive()||(c*=2);return c*b}function R(a,b){a.j.info("Error code "+b);if(b==2){var c=z(a.eb,a),d=a.Wa,e=!d;d=new T(d||"//www.google.com/images/cleardot.gif");x.location&&x.location.protocol=="http"||Ac(d,"https");Tb(d);e?Tc(d.toString(),c):Uc(d.toString(),c)}else J(2);a.I=0;a.l&&a.l.ra(b);md(a);kd(a)}n.eb=function(a){a?(this.j.info("Successfully pinged google.com"),J(2)):(this.j.info("Failed to ping google.com"),J(1))};
function md(a){a.I=0;a.la=[];if(a.l){var b=xc(a.h);if(b.length!=0||a.i.length!=0)ua(a.la,b),ua(a.la,a.i),a.h.i.length=0,ta(a.i),a.i.length=0;a.l.qa()}}function pc(a,b,c){var d=c instanceof T?O(c):new T(c);if(d.g!="")b&&(d.g=b+"."+d.g),Bc(d,d.u);else{var e=x.location;d=e.protocol;b=b?b+"."+e.hostname:e.hostname;e=+e.port;var f=new T(null);d&&Ac(f,d);b&&(f.g=b);e&&Bc(f,e);c&&(f.h=c);d=f}c=a.G;b=a.ya;c&&b&&S(d,c,b);S(d,"VER",a.ma);ld(a,d);return d}
function Xb(a,b,c){if(b&&!a.K)throw Error("Can't create secondary domain capable XhrIo object.");b=a.Ca&&!a.oa?new X(new Wc({cb:c})):new X(a.oa);b.Ha(a.K);return b}n.isActive=function(){return!!this.l&&this.l.isActive(this)};function sd(){}n=sd.prototype;n.ta=function(){};n.sa=function(){};n.ra=function(){};n.qa=function(){};n.isActive=function(){return!0};n.Ma=function(){};function td(){}td.prototype.g=function(a,b){return new Y(a,b)};
function Y(a,b){E.call(this);this.g=new jd(b);this.l=a;this.h=b&&b.messageUrlParams||null;a=b&&b.messageHeaders||null;b&&b.clientProtocolHeaderRequired&&(a?a["X-Client-Protocol"]="webchannel":a={"X-Client-Protocol":"webchannel"});this.g.o=a;a=b&&b.initMessageHeaders||null;b&&b.messageContentType&&(a?a["X-WebChannel-Content-Type"]=b.messageContentType:a={"X-WebChannel-Content-Type":b.messageContentType});b&&b.ua&&(a?a["X-WebChannel-Client-Profile"]=b.ua:a={"X-WebChannel-Client-Profile":b.ua});this.g.U=
a;(a=b&&b.Sb)&&!Ia(a)&&(this.g.u=a);this.A=b&&b.supportsCrossDomainXhr||!1;this.v=b&&b.sendRawJson||!1;(b=b&&b.httpSessionIdParam)&&!Ia(b)&&(this.g.G=b,a=this.h,a!==null&&b in a&&(a=this.h,b in a&&delete a[b]));this.j=new Z(this)}A(Y,E);Y.prototype.m=function(){this.g.l=this.j;this.A&&(this.g.K=!0);this.g.connect(this.l,this.h||void 0)};Y.prototype.close=function(){tc(this.g)};
Y.prototype.o=function(a){var b=this.g;if(typeof a==="string"){var c={};c.__data__=a;a=c}else this.v&&(c={},c.__data__=qb(a),a=c);b.i.push(new uc(b.ab++,a));b.I==3&&sc(b)};Y.prototype.N=function(){this.g.l=null;delete this.j;tc(this.g);delete this.g;Y.X.N.call(this)};
function ud(a){wb.call(this);a.__headers__&&(this.headers=a.__headers__,this.statusCode=a.__status__,delete a.__headers__,delete a.__status__);var b=a.__sm__;if(b){a:{for(var c in b){a=c;break a}a=void 0}if(this.i=a)a=this.i,b=b!==null&&a in b?b[a]:void 0;this.data=b}else this.data=a}A(ud,wb);function vd(){xb.call(this);this.status=1}A(vd,xb);function Z(a){this.g=a}A(Z,sd);Z.prototype.ta=function(){F(this.g,"a")};Z.prototype.sa=function(a){F(this.g,new ud(a))};
Z.prototype.ra=function(a){F(this.g,new vd(a))};Z.prototype.qa=function(){F(this.g,"b")};td.prototype.createWebChannel=td.prototype.g;Y.prototype.send=Y.prototype.o;Y.prototype.open=Y.prototype.m;Y.prototype.close=Y.prototype.close;module.exports.createWebChannelTransport=function(){return new td};module.exports.getStatEventTarget=function(){return zb()};module.exports.Event=I;module.exports.Stat={lb:0,ob:1,pb:2,Jb:3,Ob:4,Lb:5,Mb:6,Kb:7,Ib:8,Nb:9,PROXY:10,NOPROXY:11,Gb:12,Cb:13,Db:14,Bb:15,Eb:16,Fb:17,hb:18,gb:19,ib:20};Kb.NO_ERROR=0;Kb.TIMEOUT=8;Kb.HTTP_ERROR=6;
module.exports.ErrorCode=Kb;Lb.COMPLETE="complete";module.exports.EventType=Lb;ub.EventType=vb;vb.OPEN="a";vb.CLOSE="b";vb.ERROR="c";vb.MESSAGE="d";E.prototype.listen=E.prototype.J;module.exports.WebChannel=ub;module.exports.FetchXmlHttpFactory=Wc;X.prototype.listenOnce=X.prototype.K;X.prototype.getLastError=X.prototype.Ja;X.prototype.getLastErrorCode=X.prototype.Aa;X.prototype.getStatus=X.prototype.da;X.prototype.getResponseJson=X.prototype.Na;X.prototype.getResponseText=X.prototype.na;
X.prototype.send=X.prototype.fa;X.prototype.setWithCredentials=X.prototype.Ha;module.exports.XhrIo=X;}).apply( typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self  : typeof window !== 'undefined' ? window  : {});
