/** @license
Copyright The Closure Library Authors.
SPDX-License-Identifier: Apache-2.0
*/
(function() {'use strict';var h,aa=Object.defineProperty;function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);
function ea(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&aa(c,a,{configurable:!0,writable:!0,value:b})}}ea("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});ea("Array.prototype.values",function(a){return a?a:function(){return this[Symbol.iterator]()}});/** @license

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var fa=fa||{},k=this||self;function ha(a){var b=typeof a;b=b!="object"?b:a?Array.isArray(a)?"array":b:"null";return b=="array"||b=="object"&&typeof a.length=="number"}function n(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}function ia(a,b,c){return a.call.apply(a.bind,arguments)}function p(a,b,c){p=ia;return p.apply(null,arguments)}function ja(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}
function r(a,b){function c(){}c.prototype=b.prototype;a.Z=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Pb=function(d,e,f){for(var g=Array(arguments.length-2),l=2;l<arguments.length;l++)g[l-2]=arguments[l];return b.prototype[e].apply(d,g)}};var ka=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?a=>a&&AsyncContext.Snapshot.wrap(a):a=>a;function la(a){const b=a.length;if(b>0){const c=Array(b);for(let d=0;d<b;d++)c[d]=a[d];return c}return[]}function ma(a,b){for(let c=1;c<arguments.length;c++){const d=arguments[c];if(ha(d)){const e=a.length||0,f=d.length||0;a.length=e+f;for(let g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}};class na{constructor(a,b){this.i=a;this.j=b;this.h=0;this.g=null}get(){let a;this.h>0?(this.h--,a=this.g,this.g=a.next,a.next=null):a=this.i();return a}};function oa(a){k.setTimeout(()=>{throw a;},0)};function pa(){var a=qa;let b=null;a.g&&(b=a.g,a.g=a.g.next,a.g||(a.h=null),b.next=null);return b}class ra{constructor(){this.h=this.g=null}add(a,b){const c=sa.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c}}var sa=new na(()=>new ta,a=>a.reset());class ta{constructor(){this.next=this.g=this.h=null}set(a,b){this.h=a;this.g=b;this.next=null}reset(){this.next=this.g=this.h=null}};let t,u=!1,qa=new ra,va=()=>{const a=Promise.resolve(void 0);t=()=>{a.then(ua)}};function ua(){for(var a;a=pa();){try{a.h.call(a.g)}catch(c){oa(c)}var b=sa;b.j(a);b.h<100&&(b.h++,a.next=b.g,b.g=a)}u=!1};function v(){this.s=this.s;this.C=this.C}v.prototype.s=!1;v.prototype.dispose=function(){this.s||(this.s=!0,this.M())};v.prototype[Symbol.dispose]=function(){this.dispose()};v.prototype.M=function(){if(this.C)for(;this.C.length;)this.C.shift()()};function w(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1}w.prototype.h=function(){this.defaultPrevented=!0};var wa=function(){if(!k.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{const c=()=>{};k.addEventListener("test",c,b);k.removeEventListener("test",c,b)}catch(c){}return a}();function y(a){return/^[\s\xa0]*$/.test(a)};function z(a,b){w.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.i=null;a&&this.init(a,b)}r(z,w);
z.prototype.init=function(a,b){const c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;b=a.relatedTarget;b||(c=="mouseover"?b=a.fromElement:c=="mouseout"&&(b=a.toElement));this.relatedTarget=b;d?(this.clientX=d.clientX!==void 0?d.clientX:d.pageX,this.clientY=d.clientY!==void 0?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=a.clientX!==void 0?a.clientX:a.pageX,this.clientY=a.clientY!==
void 0?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=a.pointerType;this.state=a.state;this.i=a;a.defaultPrevented&&z.Z.h.call(this)};z.prototype.h=function(){z.Z.h.call(this);const a=this.i;a.preventDefault?a.preventDefault():a.returnValue=!1};var A="closure_listenable_"+(Math.random()*1E6|0);var za=0;function Aa(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.ha=e;this.key=++za;this.da=this.fa=!1}function Ba(a){a.da=!0;a.listener=null;a.proxy=null;a.src=null;a.ha=null};function Ca(a,b,c){for(const d in a)b.call(c,a[d],d,a)}function Da(a,b){for(const c in a)b.call(void 0,a[c],c,a)}function Ea(a){const b={};for(const c in a)b[c]=a[c];return b}const Fa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ga(a,b){let c,d;for(let e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(let f=0;f<Fa.length;f++)c=Fa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Ha(a){this.src=a;this.g={};this.h=0}Ha.prototype.add=function(a,b,c,d,e){const f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);const g=Ia(a,b,d,e);g>-1?(b=a[g],c||(b.fa=!1)):(b=new Aa(b,this.src,f,!!d,e),b.fa=c,a.push(b));return b};function Ja(a,b){const c=b.type;if(c in a.g){var d=a.g[c],e=Array.prototype.indexOf.call(d,b,void 0),f;(f=e>=0)&&Array.prototype.splice.call(d,e,1);f&&(Ba(b),a.g[c].length==0&&(delete a.g[c],a.h--))}}
function Ia(a,b,c,d){for(let e=0;e<a.length;++e){const f=a[e];if(!f.da&&f.listener==b&&f.capture==!!c&&f.ha==d)return e}return-1};var Ka="closure_lm_"+(Math.random()*1E6|0),La={},Ma=0;function Na(a,b,c,d,e){if(d&&d.once)return Oa(a,b,c,d,e);if(Array.isArray(b)){for(let f=0;f<b.length;f++)Na(a,b[f],c,d,e);return null}c=Pa(c);return a&&a[A]?a.I(b,c,n(d)?!!d.capture:!!d,e):Qa(a,b,c,!1,d,e)}
function Qa(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");const g=n(e)?!!e.capture:!!e;let l=Ra(a);l||(a[Ka]=l=new Ha(a));c=l.add(b,c,d,g,f);if(c.proxy)return c;d=Sa();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)wa||(e=g),e===void 0&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Ta(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Ma++;return c}
function Sa(){function a(c){return b.call(a.src,a.listener,c)}const b=Ua;return a}function Oa(a,b,c,d,e){if(Array.isArray(b)){for(let f=0;f<b.length;f++)Oa(a,b[f],c,d,e);return null}c=Pa(c);return a&&a[A]?a.J(b,c,n(d)?!!d.capture:!!d,e):Qa(a,b,c,!0,d,e)}
function Va(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Va(a,b[f],c,d,e);else(d=n(d)?!!d.capture:!!d,c=Pa(c),a&&a[A])?(a=a.i,f=String(b).toString(),f in a.g&&(b=a.g[f],c=Ia(b,c,d,e),c>-1&&(Ba(b[c]),Array.prototype.splice.call(b,c,1),b.length==0&&(delete a.g[f],a.h--)))):a&&(a=Ra(a))&&(b=a.g[b.toString()],a=-1,b&&(a=Ia(b,c,d,e)),(c=a>-1?b[a]:null)&&Wa(c))}
function Wa(a){if(typeof a!=="number"&&a&&!a.da){var b=a.src;if(b&&b[A])Ja(b.i,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Ta(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Ma--;(c=Ra(b))?(Ja(c,a),c.h==0&&(c.src=null,b[Ka]=null)):Ba(a)}}}function Ta(a){return a in La?La[a]:La[a]="on"+a}function Ua(a,b){if(a.da)a=!0;else{b=new z(b,this);const c=a.listener,d=a.ha||a.src;a.fa&&Wa(a);a=c.call(d,b)}return a}
function Ra(a){a=a[Ka];return a instanceof Ha?a:null}var Xa="__closure_events_fn_"+(Math.random()*1E9>>>0);function Pa(a){if(typeof a==="function")return a;a[Xa]||(a[Xa]=function(b){return a.handleEvent(b)});return a[Xa]};function B(){v.call(this);this.i=new Ha(this);this.L=this;this.F=null}r(B,v);B.prototype[A]=!0;B.prototype.removeEventListener=function(a,b,c,d){Va(this,a,b,c,d)};
function C(a,b){var c,d=a.F;if(d)for(c=[];d;d=d.F)c.push(d);a=a.L;d=b.type||b;if(typeof b==="string")b=new w(b,a);else if(b instanceof w)b.target=b.target||a;else{var e=b;b=new w(d,a);Ga(b,e)}e=!0;let f,g;if(c)for(g=c.length-1;g>=0;g--)f=b.g=c[g],e=Ya(f,d,!0,b)&&e;f=b.g=a;e=Ya(f,d,!0,b)&&e;e=Ya(f,d,!1,b)&&e;if(c)for(g=0;g<c.length;g++)f=b.g=c[g],e=Ya(f,d,!1,b)&&e}
B.prototype.M=function(){B.Z.M.call(this);if(this.i){var a=this.i;let b=0;for(const c in a.g){const d=a.g[c];for(let e=0;e<d.length;e++)++b,Ba(d[e]);delete a.g[c];a.h--}}this.F=null};B.prototype.I=function(a,b,c,d){return this.i.add(String(a),b,!1,c,d)};B.prototype.J=function(a,b,c,d){return this.i.add(String(a),b,!0,c,d)};
function Ya(a,b,c,d){b=a.i.g[String(b)];if(!b)return!0;b=b.concat();let e=!0;for(let f=0;f<b.length;++f){const g=b[f];if(g&&!g.da&&g.capture==c){const l=g.listener,q=g.ha||g.src;g.fa&&Ja(a.i,g);e=l.call(q,d)!==!1&&e}}return e&&!d.defaultPrevented};function Za(a,b){if(typeof a!=="function")if(a&&typeof a.handleEvent=="function")a=p(a.handleEvent,a);else throw Error("Invalid listener argument");return Number(b)>2147483647?-1:k.setTimeout(a,b||0)};function $a(a){a.g=Za(()=>{a.g=null;a.i&&(a.i=!1,$a(a))},a.l);const b=a.h;a.h=null;a.m.apply(null,b)}class bb extends v{constructor(a,b){super();this.m=a;this.l=b;this.h=null;this.i=!1;this.g=null}j(a){this.h=arguments;this.g?this.i=!0:$a(this)}M(){super.M();this.g&&(k.clearTimeout(this.g),this.g=null,this.i=!1,this.h=null)}};function D(a){v.call(this);this.h=a;this.g={}}r(D,v);var cb=[];function db(a){Ca(a.g,function(b,c){this.g.hasOwnProperty(c)&&Wa(b)},a);a.g={}}D.prototype.M=function(){D.Z.M.call(this);db(this)};D.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var eb=k.JSON.stringify;var fb=k.JSON.parse;var gb=class{stringify(a){return k.JSON.stringify(a,void 0)}parse(a){return k.JSON.parse(a,void 0)}};function hb(){};function ib(){}var E={OPEN:"a",jb:"b",Ia:"c",vb:"d"};function jb(){w.call(this,"d")}r(jb,w);function kb(){w.call(this,"c")}r(kb,w);var F={},lb=null;function mb(){return lb=lb||new B}F.Ka="serverreachability";function nb(a){w.call(this,F.Ka,a)}r(nb,w);function G(a){const b=mb();C(b,new nb(b,a))}F.STAT_EVENT="statevent";function ob(a,b){w.call(this,F.STAT_EVENT,a);this.stat=b}r(ob,w);function H(a){const b=mb();C(b,new ob(b,a))}F.La="timingevent";function pb(a,b){w.call(this,F.La,a);this.size=b}r(pb,w);
function I(a,b){if(typeof a!=="function")throw Error("Fn must not be null and must be a function");return k.setTimeout(function(){a()},b)};function J(){this.g=!0}J.prototype.wa=function(){this.g=!1};function qb(a,b,c,d,e,f){a.info(function(){if(a.g)if(f){var g="";var l=f.split("&");for(let m=0;m<l.length;m++){var q=l[m].split("=");if(q.length>1){const x=q[0];q=q[1];const L=x.split("_");g=L.length>=2&&L[1]=="type"?g+(x+"="+q+"&"):g+(x+"=redacted&")}}}else g=null;else g=f;return"XMLHTTP REQ ("+d+") [attempt "+e+"]: "+b+"\n"+c+"\n"+g})}
function rb(a,b,c,d,e,f,g){a.info(function(){return"XMLHTTP RESP ("+d+") [ attempt "+e+"]: "+b+"\n"+c+"\n"+f+" "+g})}function K(a,b,c,d){a.info(function(){return"XMLHTTP TEXT ("+b+"): "+sb(a,c)+(d?" "+d:"")})}function tb(a,b){a.info(function(){return"TIMEOUT: "+b})}J.prototype.info=function(){};
function sb(a,b){if(!a.g)return b;if(!b)return null;try{const f=JSON.parse(b);if(f)for(a=0;a<f.length;a++)if(Array.isArray(f[a])){var c=f[a];if(!(c.length<2)){var d=c[1];if(Array.isArray(d)&&!(d.length<1)){var e=d[0];if(e!="noop"&&e!="stop"&&e!="close")for(let g=1;g<d.length;g++)d[g]=""}}}return eb(f)}catch(f){return b}};var ub={NO_ERROR:0,fb:1,sb:2,rb:3,mb:4,qb:5,tb:6,Ha:7,TIMEOUT:8,wb:9};var vb={kb:"complete",Gb:"success",Ia:"error",Ha:"abort",yb:"ready",zb:"readystatechange",TIMEOUT:"timeout",ub:"incrementaldata",xb:"progress",nb:"downloadprogress",Ob:"uploadprogress"};var wb;function xb(){}r(xb,hb);xb.prototype.g=function(){return new XMLHttpRequest};wb=new xb;function M(a){return encodeURIComponent(String(a))}function yb(a){var b=1;a=a.split(":");const c=[];for(;b>0&&a.length;)c.push(a.shift()),b--;a.length&&c.push(a.join(":"));return c};function N(a,b,c,d){this.j=a;this.i=b;this.l=c;this.R=d||1;this.U=new D(this);this.H=45E3;this.I=null;this.o=!1;this.s=this.A=this.v=this.L=this.D=this.S=this.B=null;this.F=[];this.g=null;this.C=0;this.m=this.u=null;this.X=-1;this.J=!1;this.O=0;this.N=null;this.W=this.K=this.T=this.P=!1;this.h=new zb}function zb(){this.i=null;this.g="";this.h=!1}var Ab={},Bb={};function Cb(a,b,c){a.L=1;a.v=Db(O(b));a.s=c;a.P=!0;Eb(a,null)}
function Eb(a,b){a.D=Date.now();Fb(a);a.A=O(a.v);var c=a.A,d=a.R;Array.isArray(d)||(d=[String(d)]);Gb(c.i,"t",d);a.C=0;c=a.j.J;a.h=new zb;a.g=Hb(a.j,c?b:null,!a.s);a.O>0&&(a.N=new bb(p(a.Y,a,a.g),a.O));b=a.U;c=a.g;d=a.ba;var e="readystatechange";Array.isArray(e)||(e&&(cb[0]=e.toString()),e=cb);for(let f=0;f<e.length;f++){const g=Na(c,e[f],d||b.handleEvent,!1,b.h||b);if(!g)break;b.g[g.key]=g}b=a.I?Ea(a.I):{};a.s?(a.u||(a.u="POST"),b["Content-Type"]="application/x-www-form-urlencoded",a.g.ea(a.A,a.u,
a.s,b)):(a.u="GET",a.g.ea(a.A,a.u,null,b));G(1);qb(a.i,a.u,a.A,a.l,a.R,a.s)}N.prototype.ba=function(a){a=a.target;const b=this.N;b&&P(a)==3?b.j():this.Y(a)};
N.prototype.Y=function(a){try{if(a==this.g)a:{const l=P(this.g),q=this.g.Aa(),m=this.g.ca();if(!(l<3)&&(l!=3||this.g&&(this.h.h||this.g.na()||Ib(this.g)))){this.J||l!=4||q==7||(q==8||m<=0?G(3):G(2));Jb(this);var b=this.g.ca();this.X=b;var c=Kb(this);this.o=b==200;rb(this.i,this.u,this.A,this.l,this.R,l,b);if(this.o){if(this.T&&!this.K){b:{if(this.g){var d,e=this.g;if((d=e.g?e.g.getResponseHeader("X-HTTP-Initial-Response"):null)&&!y(d)){var f=d;break b}}f=null}if(a=f)K(this.i,this.l,a,"Initial handshake response via X-HTTP-Initial-Response"),
this.K=!0,Lb(this,a);else{this.o=!1;this.m=3;H(12);Q(this);Mb(this);break a}}if(this.P){a=!0;let x;for(;!this.J&&this.C<c.length;)if(x=Nb(this,c),x==Bb){l==4&&(this.m=4,H(14),a=!1);K(this.i,this.l,null,"[Incomplete Response]");break}else if(x==Ab){this.m=4;H(15);K(this.i,this.l,c,"[Invalid Chunk]");a=!1;break}else K(this.i,this.l,x,null),Lb(this,x);Ob(this)&&this.C!=0&&(this.h.g=this.h.g.slice(this.C),this.C=0);l!=4||c.length!=0||this.h.h||(this.m=1,H(16),a=!1);this.o=this.o&&a;if(!a)K(this.i,this.l,
c,"[Invalid Chunked Response]"),Q(this),Mb(this);else if(c.length>0&&!this.W){this.W=!0;var g=this.j;g.g==this&&g.aa&&!g.N&&(g.j.info("Great, no buffering proxy detected. Bytes received: "+c.length),Pb(g),g.N=!0,H(11))}}else K(this.i,this.l,c,null),Lb(this,c);l==4&&Q(this);this.o&&!this.J&&(l==4?Qb(this.j,this):(this.o=!1,Fb(this)))}else Rb(this.g),b==400&&c.indexOf("Unknown SID")>0?(this.m=3,H(12)):(this.m=0,H(13)),Q(this),Mb(this)}}}catch(l){}finally{}};
function Kb(a){if(!Ob(a))return a.g.na();const b=Ib(a.g);if(b==="")return"";let c="";const d=b.length,e=P(a.g)==4;if(!a.h.i){if(typeof TextDecoder==="undefined")return Q(a),Mb(a),"";a.h.i=new k.TextDecoder}for(let f=0;f<d;f++)a.h.h=!0,c+=a.h.i.decode(b[f],{stream:!(e&&f==d-1)});b.length=0;a.h.g+=c;a.C=0;return a.h.g}function Ob(a){return a.g?a.u=="GET"&&a.L!=2&&a.j.Ba:!1}
function Nb(a,b){var c=a.C,d=b.indexOf("\n",c);if(d==-1)return Bb;c=Number(b.substring(c,d));if(isNaN(c))return Ab;d+=1;if(d+c>b.length)return Bb;b=b.slice(d,d+c);a.C=d+c;return b}N.prototype.cancel=function(){this.J=!0;Q(this)};function Fb(a){a.S=Date.now()+a.H;Sb(a,a.H)}function Sb(a,b){if(a.B!=null)throw Error("WatchDog timer not null");a.B=I(p(a.aa,a),b)}function Jb(a){a.B&&(k.clearTimeout(a.B),a.B=null)}
N.prototype.aa=function(){this.B=null;const a=Date.now();a-this.S>=0?(tb(this.i,this.A),this.L!=2&&(G(3),H(17)),Q(this),this.m=2,Mb(this)):Sb(this,this.S-a)};function Mb(a){a.j.G==0||a.J||Qb(a.j,a)}function Q(a){Jb(a);var b=a.N;b&&typeof b.dispose=="function"&&b.dispose();a.N=null;db(a.U);a.g&&(b=a.g,a.g=null,b.abort(),b.dispose())}
function Lb(a,b){try{var c=a.j;if(c.G!=0&&(c.g==a||Tb(c.h,a)))if(!a.K&&Tb(c.h,a)&&c.G==3){try{var d=c.Ca.g.parse(b)}catch(m){d=null}if(Array.isArray(d)&&d.length==3){var e=d;if(e[0]==0)a:{if(!c.u){if(c.g)if(c.g.D+3E3<a.D)Ub(c),Vb(c);else break a;Wb(c);H(18)}}else c.ya=e[1],0<c.ya-c.T&&e[2]<37500&&c.D&&c.v==0&&!c.C&&(c.C=I(p(c.Ya,c),6E3));if(Xb(c.h)<=1&&c.ba){try{c.ba()}catch(m){}c.ba=void 0}}else R(c,11)}else if((a.K||c.g==a)&&Ub(c),!y(b))for(e=c.Ca.g.parse(b),b=0;b<e.length;b++){let m=e[b];c.T=m[0];
m=m[1];if(c.G==2)if(m[0]=="c"){c.K=m[1];c.ia=m[2];const x=m[3];x!=null&&(c.la=x,c.j.info("VER="+c.la));const L=m[4];L!=null&&(c.za=L,c.j.info("SVER="+c.za));const xa=m[5];xa!=null&&typeof xa==="number"&&xa>0&&(d=1.5*xa,c.L=d,c.j.info("backChannelRequestTimeoutMs_="+d));d=c;const ba=a.g;if(ba){const ya=ba.g?ba.g.getResponseHeader("X-Client-Wire-Protocol"):null;if(ya){var f=d.h;f.g||ya.indexOf("spdy")==-1&&ya.indexOf("quic")==-1&&ya.indexOf("h2")==-1||(f.j=f.l,f.g=new Set,f.h&&(Yb(f,f.h),f.h=null))}if(d.F){const ab=
ba.g?ba.g.getResponseHeader("X-HTTP-Session-Id"):null;ab&&(d.xa=ab,S(d.I,d.F,ab))}}c.G=3;c.l&&c.l.ta();c.aa&&(c.R=Date.now()-a.D,c.j.info("Handshake RTT: "+c.R+"ms"));d=c;var g=a;d.pa=Zb(d,d.J?d.ia:null,d.W);if(g.K){$b(d.h,g);var l=g,q=d.L;q&&(l.H=q);l.B&&(Jb(l),Fb(l));d.g=g}else ac(d);c.i.length>0&&bc(c)}else m[0]!="stop"&&m[0]!="close"||R(c,7);else c.G==3&&(m[0]=="stop"||m[0]=="close"?m[0]=="stop"?R(c,7):cc(c):m[0]!="noop"&&c.l&&c.l.sa(m),c.v=0)}G(4)}catch(m){}};var dc=class{constructor(a,b){this.g=a;this.map=b}};function ec(a){this.l=a||10;k.PerformanceNavigationTiming?(a=k.performance.getEntriesByType("navigation"),a=a.length>0&&(a[0].nextHopProtocol=="hq"||a[0].nextHopProtocol=="h2")):a=!!(k.chrome&&k.chrome.loadTimes&&k.chrome.loadTimes()&&k.chrome.loadTimes().wasFetchedViaSpdy);this.j=a?this.l:1;this.g=null;this.j>1&&(this.g=new Set);this.h=null;this.i=[]}function fc(a){return a.h?!0:a.g?a.g.size>=a.j:!1}function Xb(a){return a.h?1:a.g?a.g.size:0}function Tb(a,b){return a.h?a.h==b:a.g?a.g.has(b):!1}
function Yb(a,b){a.g?a.g.add(b):a.h=b}function $b(a,b){a.h&&a.h==b?a.h=null:a.g&&a.g.has(b)&&a.g.delete(b)}ec.prototype.cancel=function(){this.i=gc(this);if(this.h)this.h.cancel(),this.h=null;else if(this.g&&this.g.size!==0){for(const a of this.g.values())a.cancel();this.g.clear()}};function gc(a){if(a.h!=null)return a.i.concat(a.h.F);if(a.g!=null&&a.g.size!==0){let b=a.i;for(const c of a.g.values())b=b.concat(c.F);return b}return la(a.i)};function hc(a){if(a.V&&typeof a.V=="function")return a.V();if(typeof Map!=="undefined"&&a instanceof Map||typeof Set!=="undefined"&&a instanceof Set)return Array.from(a.values());if(typeof a==="string")return a.split("");if(ha(a)){var b=[],c=a.length;for(var d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function ic(a){if(a.ma&&typeof a.ma=="function")return a.ma();if(!a.V||typeof a.V!="function"){if(typeof Map!=="undefined"&&a instanceof Map)return Array.from(a.keys());if(!(typeof Set!=="undefined"&&a instanceof Set)){if(ha(a)||typeof a==="string"){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}b=[];c=0;for(const d in a)b[c++]=d;return b}}}
function jc(a,b){if(a.forEach&&typeof a.forEach=="function")a.forEach(b,void 0);else if(ha(a)||typeof a==="string")Array.prototype.forEach.call(a,b,void 0);else{const c=ic(a),d=hc(a),e=d.length;for(let f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};var kc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function lc(a,b){if(a){a=a.split("&");for(let c=0;c<a.length;c++){const d=a[c].indexOf("=");let e,f=null;d>=0?(e=a[c].substring(0,d),f=a[c].substring(d+1)):e=a[c];b(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};function T(a){this.g=this.o=this.j="";this.s=null;this.m=this.h="";this.l=!1;let b;a instanceof T?(this.l=a.l,mc(this,a.j),this.o=a.o,this.g=a.g,nc(this,a.s),this.h=a.h,oc(this,pc(a.i)),this.m=a.m):a&&(b=String(a).match(kc))?(this.l=!1,mc(this,b[1]||"",!0),this.o=qc(b[2]||""),this.g=qc(b[3]||"",!0),nc(this,b[4]),this.h=qc(b[5]||"",!0),oc(this,b[6]||"",!0),this.m=qc(b[7]||"")):(this.l=!1,this.i=new rc(null,this.l))}
T.prototype.toString=function(){const a=[];var b=this.j;b&&a.push(sc(b,tc,!0),":");var c=this.g;if(c||b=="file")a.push("//"),(b=this.o)&&a.push(sc(b,tc,!0),"@"),a.push(uc(M(c))),c=this.s,c!=null&&a.push(":",String(c));if(c=this.h)this.g&&c.charAt(0)!="/"&&a.push("/"),a.push(sc(c,c.charAt(0)=="/"?vc:wc,!0));(c=this.i.toString())&&a.push("?",c);(c=this.m)&&a.push("#",sc(c,xc));return a.join("")};
T.prototype.resolve=function(a){const b=O(this);let c=!!a.j;c?mc(b,a.j):c=!!a.o;c?b.o=a.o:c=!!a.g;c?b.g=a.g:c=a.s!=null;var d=a.h;if(c)nc(b,a.s);else if(c=!!a.h){if(d.charAt(0)!="/")if(this.g&&!this.h)d="/"+d;else{var e=b.h.lastIndexOf("/");e!=-1&&(d=b.h.slice(0,e+1)+d)}e=d;if(e==".."||e==".")d="";else if(e.indexOf("./")!=-1||e.indexOf("/.")!=-1){d=e.lastIndexOf("/",0)==0;e=e.split("/");const f=[];for(let g=0;g<e.length;){const l=e[g++];l=="."?d&&g==e.length&&f.push(""):l==".."?((f.length>1||f.length==
1&&f[0]!="")&&f.pop(),d&&g==e.length&&f.push("")):(f.push(l),d=!0)}d=f.join("/")}else d=e}c?b.h=d:c=a.i.toString()!=="";c?oc(b,pc(a.i)):c=!!a.m;c&&(b.m=a.m);return b};function O(a){return new T(a)}function mc(a,b,c){a.j=c?qc(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))}function nc(a,b){if(b){b=Number(b);if(isNaN(b)||b<0)throw Error("Bad port number "+b);a.s=b}else a.s=null}function oc(a,b,c){b instanceof rc?(a.i=b,yc(a.i,a.l)):(c||(b=sc(b,zc)),a.i=new rc(b,a.l))}function S(a,b,c){a.i.set(b,c)}
function Db(a){S(a,"zx",Math.floor(Math.random()*2147483648).toString(36)+Math.abs(Math.floor(Math.random()*2147483648)^Date.now()).toString(36));return a}function qc(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function sc(a,b,c){return typeof a==="string"?(a=encodeURI(a).replace(b,Ac),c&&(a=uc(a)),a):null}function Ac(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}function uc(a){return a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")}
var tc=/[#\/\?@]/g,wc=/[#\?:]/g,vc=/[#\?]/g,zc=/[#\?@]/g,xc=/#/g;function rc(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b}function U(a){a.g||(a.g=new Map,a.h=0,a.i&&lc(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}h=rc.prototype;h.add=function(a,b){U(this);this.i=null;a=V(this,a);let c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};function Bc(a,b){U(a);b=V(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a.g.delete(b))}
function Cc(a,b){U(a);b=V(a,b);return a.g.has(b)}h.forEach=function(a,b){U(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};h.ma=function(){U(this);const a=Array.from(this.g.values()),b=Array.from(this.g.keys()),c=[];for(let d=0;d<b.length;d++){const e=a[d];for(let f=0;f<e.length;f++)c.push(b[d])}return c};
h.V=function(a){U(this);let b=[];if(typeof a==="string")Cc(this,a)&&(b=b.concat(this.g.get(V(this,a))));else{a=Array.from(this.g.values());for(let c=0;c<a.length;c++)b=b.concat(a[c])}return b};h.set=function(a,b){U(this);this.i=null;a=V(this,a);Cc(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};h.get=function(a,b){if(!a)return b;a=this.V(a);return a.length>0?String(a[0]):b};function Gb(a,b,c){Bc(a,b);c.length>0&&(a.i=null,a.g.set(V(a,b),la(c)),a.h+=c.length)}
h.toString=function(){if(this.i)return this.i;if(!this.g)return"";const a=[],b=Array.from(this.g.keys());for(let d=0;d<b.length;d++){var c=b[d];const e=M(c);c=this.V(c);for(let f=0;f<c.length;f++){let g=e;c[f]!==""&&(g+="="+M(c[f]));a.push(g)}}return this.i=a.join("&")};function pc(a){const b=new rc;b.i=a.i;a.g&&(b.g=new Map(a.g),b.h=a.h);return b}function V(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b}
function yc(a,b){b&&!a.j&&(U(a),a.i=null,a.g.forEach(function(c,d){const e=d.toLowerCase();d!=e&&(Bc(this,d),Gb(this,e,c))},a));a.j=b};function Dc(a,b){const c=new J;if(k.Image){const d=new Image;d.onload=ja(W,c,"TestLoadImage: loaded",!0,b,d);d.onerror=ja(W,c,"TestLoadImage: error",!1,b,d);d.onabort=ja(W,c,"TestLoadImage: abort",!1,b,d);d.ontimeout=ja(W,c,"TestLoadImage: timeout",!1,b,d);k.setTimeout(function(){if(d.ontimeout)d.ontimeout()},1E4);d.src=a}else b(!1)}
function Ec(a,b){const c=new J,d=new AbortController,e=setTimeout(()=>{d.abort();W(c,"TestPingServer: timeout",!1,b)},1E4);fetch(a,{signal:d.signal}).then(f=>{clearTimeout(e);f.ok?W(c,"TestPingServer: ok",!0,b):W(c,"TestPingServer: server error",!1,b)}).catch(()=>{clearTimeout(e);W(c,"TestPingServer: error",!1,b)})}function W(a,b,c,d,e){try{e&&(e.onload=null,e.onerror=null,e.onabort=null,e.ontimeout=null),d(c)}catch(f){}};function Fc(){this.g=new gb}function Gc(a,b,c){const d=c||"";try{jc(a,function(e,f){let g=e;n(e)&&(g=eb(e));b.push(d+f+"="+encodeURIComponent(g))})}catch(e){throw b.push(d+"type="+encodeURIComponent("_badmap")),e;}};function Hc(a){this.i=a.Tb||null;this.h=a.cb||!1}r(Hc,hb);Hc.prototype.g=function(){return new Ic(this.i,this.h)};function Ic(a,b){B.call(this);this.D=a;this.o=b;this.m=void 0;this.status=this.readyState=0;this.responseType=this.responseText=this.response=this.statusText="";this.onreadystatechange=null;this.u=new Headers;this.h=null;this.B="GET";this.A="";this.g=!1;this.v=this.j=this.l=null}r(Ic,B);h=Ic.prototype;
h.open=function(a,b){if(this.readyState!=0)throw this.abort(),Error("Error reopening a connection");this.B=a;this.A=b;this.readyState=1;Jc(this)};h.send=function(a){if(this.readyState!=1)throw this.abort(),Error("need to call open() first. ");this.g=!0;const b={headers:this.u,method:this.B,credentials:this.m,cache:void 0};a&&(b.body=a);(this.D||k).fetch(new Request(this.A,b)).then(this.Ra.bind(this),this.ga.bind(this))};
h.abort=function(){this.response=this.responseText="";this.u=new Headers;this.status=0;this.j&&this.j.cancel("Request was aborted.").catch(()=>{});this.readyState>=1&&this.g&&this.readyState!=4&&(this.g=!1,Kc(this));this.readyState=0};
h.Ra=function(a){if(this.g&&(this.l=a,this.h||(this.status=this.l.status,this.statusText=this.l.statusText,this.h=a.headers,this.readyState=2,Jc(this)),this.g&&(this.readyState=3,Jc(this),this.g)))if(this.responseType==="arraybuffer")a.arrayBuffer().then(this.Pa.bind(this),this.ga.bind(this));else if(typeof k.ReadableStream!=="undefined"&&"body"in a){this.j=a.body.getReader();if(this.o){if(this.responseType)throw Error('responseType must be empty for "streamBinaryChunks" mode responses.');this.response=
[]}else this.response=this.responseText="",this.v=new TextDecoder;Lc(this)}else a.text().then(this.Qa.bind(this),this.ga.bind(this))};function Lc(a){a.j.read().then(a.Oa.bind(a)).catch(a.ga.bind(a))}h.Oa=function(a){if(this.g){if(this.o&&a.value)this.response.push(a.value);else if(!this.o){var b=a.value?a.value:new Uint8Array(0);if(b=this.v.decode(b,{stream:!a.done}))this.response=this.responseText+=b}a.done?Kc(this):Jc(this);this.readyState==3&&Lc(this)}};
h.Qa=function(a){this.g&&(this.response=this.responseText=a,Kc(this))};h.Pa=function(a){this.g&&(this.response=a,Kc(this))};h.ga=function(){this.g&&Kc(this)};function Kc(a){a.readyState=4;a.l=null;a.j=null;a.v=null;Jc(a)}h.setRequestHeader=function(a,b){this.u.append(a,b)};h.getResponseHeader=function(a){return this.h?this.h.get(a.toLowerCase())||"":""};
h.getAllResponseHeaders=function(){if(!this.h)return"";const a=[],b=this.h.entries();for(var c=b.next();!c.done;)c=c.value,a.push(c[0]+": "+c[1]),c=b.next();return a.join("\r\n")};function Jc(a){a.onreadystatechange&&a.onreadystatechange.call(a)}Object.defineProperty(Ic.prototype,"withCredentials",{get:function(){return this.m==="include"},set:function(a){this.m=a?"include":"same-origin"}});function Mc(a){let b="";Ca(a,function(c,d){b+=d;b+=":";b+=c;b+="\r\n"});return b}function Nc(a,b,c){a:{for(d in c){var d=!1;break a}d=!0}d||(c=Mc(c),typeof a==="string"?(M(b),c!=null&&M(c)):S(a,b,c))};function X(a){B.call(this);this.headers=new Map;this.K=a||null;this.h=!1;this.g=null;this.B="";this.o=0;this.l="";this.j=this.A=this.u=this.v=!1;this.m=null;this.D="";this.H=!1}r(X,B);var Oc=/^https?$/i,Pc=["POST","PUT"];h=X.prototype;h.Ga=function(a){this.H=a};
h.ea=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.B+"; newUri="+a);b=b?b.toUpperCase():"GET";this.B=a;this.l="";this.o=0;this.v=!1;this.h=!0;this.g=this.K?this.K.g():wb.g();this.g.onreadystatechange=ka(p(this.Da,this));try{this.A=!0,this.g.open(b,String(a),!0),this.A=!1}catch(f){Qc(this,f);return}a=c||"";c=new Map(this.headers);if(d)if(Object.getPrototypeOf(d)===Object.prototype)for(var e in d)c.set(e,d[e]);else if(typeof d.keys==="function"&&
typeof d.get==="function")for(const f of d.keys())c.set(f,d.get(f));else throw Error("Unknown input type for opt_headers: "+String(d));d=Array.from(c.keys()).find(f=>"content-type"==f.toLowerCase());e=k.FormData&&a instanceof k.FormData;!(Array.prototype.indexOf.call(Pc,b,void 0)>=0)||d||e||c.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");for(const [f,g]of c)this.g.setRequestHeader(f,g);this.D&&(this.g.responseType=this.D);"withCredentials"in this.g&&this.g.withCredentials!==
this.H&&(this.g.withCredentials=this.H);try{this.m&&(clearTimeout(this.m),this.m=null),this.u=!0,this.g.send(a),this.u=!1}catch(f){Qc(this,f)}};function Qc(a,b){a.h=!1;a.g&&(a.j=!0,a.g.abort(),a.j=!1);a.l=b;a.o=5;Rc(a);Sc(a)}function Rc(a){a.v||(a.v=!0,C(a,"complete"),C(a,"error"))}h.abort=function(a){this.g&&this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1,this.o=a||7,C(this,"complete"),C(this,"abort"),Sc(this))};
h.M=function(){this.g&&(this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1),Sc(this,!0));X.Z.M.call(this)};h.Da=function(){this.s||(this.A||this.u||this.j?Tc(this):this.ab())};h.ab=function(){Tc(this)};
function Tc(a){if(a.h&&typeof fa!="undefined")if(a.u&&P(a)==4)setTimeout(a.Da.bind(a),0);else if(C(a,"readystatechange"),P(a)==4){a.h=!1;try{const f=a.ca();a:switch(f){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var b=!0;break a;default:b=!1}var c;if(!(c=b)){var d;if(d=f===0){let g=String(a.B).match(kc)[1]||null;!g&&k.self&&k.self.location&&(g=k.self.location.protocol.slice(0,-1));d=!Oc.test(g?g.toLowerCase():"")}c=d}if(c)C(a,"complete"),C(a,"success");else{a.o=6;try{var e=P(a)>
2?a.g.statusText:""}catch(g){e=""}a.l=e+" ["+a.ca()+"]";Rc(a)}}finally{Sc(a)}}}function Sc(a,b){if(a.g){a.m&&(clearTimeout(a.m),a.m=null);const c=a.g;a.g=null;b||C(a,"ready");try{c.onreadystatechange=null}catch(d){}}}h.isActive=function(){return!!this.g};function P(a){return a.g?a.g.readyState:0}h.ca=function(){try{return P(this)>2?this.g.status:-1}catch(a){return-1}};h.na=function(){try{return this.g?this.g.responseText:""}catch(a){return""}};
h.Na=function(a){if(this.g){var b=this.g.responseText;a&&b.indexOf(a)==0&&(b=b.substring(a.length));return fb(b)}};function Ib(a){try{if(!a.g)return null;if("response"in a.g)return a.g.response;switch(a.D){case "":case "text":return a.g.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in a.g)return a.g.mozResponseArrayBuffer}return null}catch(b){return null}}
function Rb(a){const b={};a=(a.g&&P(a)>=2?a.g.getAllResponseHeaders()||"":"").split("\r\n");for(let d=0;d<a.length;d++){if(y(a[d]))continue;var c=yb(a[d]);const e=c[0];c=c[1];if(typeof c!=="string")continue;c=c.trim();const f=b[e]||[];b[e]=f;f.push(c)}Da(b,function(d){return d.join(", ")})}h.Aa=function(){return this.o};h.Ja=function(){return typeof this.l==="string"?this.l:String(this.l)};function Uc(a,b,c){return c&&c.internalChannelParams?c.internalChannelParams[a]||b:b}
function Vc(a){this.za=0;this.i=[];this.j=new J;this.ia=this.pa=this.I=this.W=this.g=this.xa=this.F=this.H=this.s=this.S=this.o=null;this.Xa=this.U=0;this.Ua=Uc("failFast",!1,a);this.D=this.C=this.u=this.m=this.l=null;this.X=!0;this.ya=this.T=-1;this.Y=this.v=this.B=0;this.Sa=Uc("baseRetryDelayMs",5E3,a);this.bb=Uc("retryDelaySeedMs",1E4,a);this.Va=Uc("forwardChannelMaxRetries",2,a);this.va=Uc("forwardChannelRequestTimeoutMs",2E4,a);this.oa=a&&a.xmlHttpFactory||void 0;this.Wa=a&&a.Sb||void 0;this.Ba=
a&&a.useFetchStreams||!1;this.L=void 0;this.J=a&&a.supportsCrossDomainXhr||!1;this.K="";this.h=new ec(a&&a.concurrentRequestLimit);this.Ca=new Fc;this.P=a&&a.fastHandshake||!1;this.O=a&&a.encodeInitMessageHeaders||!1;this.P&&this.O&&(this.O=!1);this.Ta=a&&a.Qb||!1;a&&a.wa&&this.j.wa();a&&a.forceLongPolling&&(this.X=!1);this.aa=!this.P&&this.X&&a&&a.detectBufferingProxy||!1;this.ja=void 0;a&&a.longPollingTimeout&&a.longPollingTimeout>0&&(this.ja=a.longPollingTimeout);this.ba=void 0;this.R=0;this.N=
!1;this.ka=this.A=null}h=Vc.prototype;h.la=8;h.G=1;h.connect=function(a,b,c,d){H(0);this.W=a;this.H=b||{};c&&d!==void 0&&(this.H.OSID=c,this.H.OAID=d);this.D=this.X;this.I=Zb(this,null,this.W);bc(this)};
function cc(a){Wc(a);if(a.G==3){var b=a.U++,c=O(a.I);S(c,"SID",a.K);S(c,"RID",b);S(c,"TYPE","terminate");Xc(a,c);b=new N(a,a.j,b);b.L=2;b.v=Db(O(c));c=!1;if(k.navigator&&k.navigator.sendBeacon)try{c=k.navigator.sendBeacon(b.v.toString(),"")}catch(d){}!c&&k.Image&&((new Image).src=b.v,c=!0);c||(b.g=Hb(b.j,null),b.g.ea(b.v));b.D=Date.now();Fb(b)}Yc(a)}function Vb(a){a.g&&(Pb(a),a.g.cancel(),a.g=null)}
function Wc(a){Vb(a);a.u&&(k.clearTimeout(a.u),a.u=null);Ub(a);a.h.cancel();a.m&&(typeof a.m==="number"&&k.clearTimeout(a.m),a.m=null)}function bc(a){if(!fc(a.h)&&!a.m){a.m=!0;var b=a.Fa;t||va();u||(t(),u=!0);qa.add(b,a);a.B=0}}function Zc(a,b){if(Xb(a.h)>=a.h.j-(a.m?1:0))return!1;if(a.m)return a.i=b.F.concat(a.i),!0;if(a.G==1||a.G==2||a.B>=(a.Ua?0:a.Va))return!1;a.m=I(p(a.Fa,a,b),$c(a,a.B));a.B++;return!0}
h.Fa=function(a){if(this.m)if(this.m=null,this.G==1){if(!a){this.U=Math.floor(Math.random()*1E5);a=this.U++;const e=new N(this,this.j,a);let f=this.o;this.S&&(f?(f=Ea(f),Ga(f,this.S)):f=this.S);this.s!==null||this.O||(e.I=f,f=null);if(this.P)a:{var b=0;for(var c=0;c<this.i.length;c++){b:{var d=this.i[c];if("__data__"in d.map&&(d=d.map.__data__,typeof d==="string")){d=d.length;break b}d=void 0}if(d===void 0)break;b+=d;if(b>4096){b=c;break a}if(b===4096||c===this.i.length-1){b=c+1;break a}}b=1E3}else b=
1E3;b=ad(this,e,b);c=O(this.I);S(c,"RID",a);S(c,"CVER",22);this.F&&S(c,"X-HTTP-Session-Id",this.F);Xc(this,c);f&&(this.O?b="headers="+M(Mc(f))+"&"+b:this.s&&Nc(c,this.s,f));Yb(this.h,e);this.Ta&&S(c,"TYPE","init");this.P?(S(c,"$req",b),S(c,"SID","null"),e.T=!0,Cb(e,c,null)):Cb(e,c,b);this.G=2}}else this.G==3&&(a?bd(this,a):this.i.length==0||fc(this.h)||bd(this))};
function bd(a,b){var c;b?c=b.l:c=a.U++;const d=O(a.I);S(d,"SID",a.K);S(d,"RID",c);S(d,"AID",a.T);Xc(a,d);a.s&&a.o&&Nc(d,a.s,a.o);c=new N(a,a.j,c,a.B+1);a.s===null&&(c.I=a.o);b&&(a.i=b.F.concat(a.i));b=ad(a,c,1E3);c.H=Math.round(a.va*.5)+Math.round(a.va*.5*Math.random());Yb(a.h,c);Cb(c,d,b)}function Xc(a,b){a.H&&Ca(a.H,function(c,d){S(b,d,c)});a.l&&jc({},function(c,d){S(b,d,c)})}
function ad(a,b,c){c=Math.min(a.i.length,c);var d=a.l?p(a.l.Ma,a.l,a):null;a:{var e=a.i;let f=-1;for(;;){const g=["count="+c];f==-1?c>0?(f=e[0].g,g.push("ofs="+f)):f=0:g.push("ofs="+f);let l=!0;for(let q=0;q<c;q++){let m=e[q].g;const x=e[q].map;m-=f;if(m<0)f=Math.max(0,e[q].g-100),l=!1;else try{Gc(x,g,"req"+m+"_")}catch(L){d&&d(x)}}if(l){d=g.join("&");break a}}d=void 0}a=a.i.splice(0,c);b.F=a;return d}function ac(a){if(!a.g&&!a.u){a.Y=1;var b=a.Ea;t||va();u||(t(),u=!0);qa.add(b,a);a.v=0}}
function Wb(a){if(a.g||a.u||a.v>=3)return!1;a.Y++;a.u=I(p(a.Ea,a),$c(a,a.v));a.v++;return!0}h.Ea=function(){this.u=null;cd(this);if(this.aa&&!(this.N||this.g==null||this.R<=0)){var a=2*this.R;this.j.info("BP detection timer enabled: "+a);this.A=I(p(this.Za,this),a)}};h.Za=function(){this.A&&(this.A=null,this.j.info("BP detection timeout reached."),this.j.info("Buffering proxy detected and switch to long-polling!"),this.D=!1,this.N=!0,H(10),Vb(this),cd(this))};
function Pb(a){a.A!=null&&(k.clearTimeout(a.A),a.A=null)}function cd(a){a.g=new N(a,a.j,"rpc",a.Y);a.s===null&&(a.g.I=a.o);a.g.O=0;var b=O(a.pa);S(b,"RID","rpc");S(b,"SID",a.K);S(b,"AID",a.T);S(b,"CI",a.D?"0":"1");!a.D&&a.ja&&S(b,"TO",a.ja);S(b,"TYPE","xmlhttp");Xc(a,b);a.s&&a.o&&Nc(b,a.s,a.o);a.L&&(a.g.H=a.L);var c=a.g;a=a.ia;c.L=1;c.v=Db(O(b));c.s=null;c.P=!0;Eb(c,a)}h.Ya=function(){this.C!=null&&(this.C=null,Vb(this),Wb(this),H(19))};function Ub(a){a.C!=null&&(k.clearTimeout(a.C),a.C=null)}
function Qb(a,b){var c=null;if(a.g==b){Ub(a);Pb(a);a.g=null;var d=2}else if(Tb(a.h,b))c=b.F,$b(a.h,b),d=1;else return;if(a.G!=0)if(b.o)if(d==1){c=b.s?b.s.length:0;b=Date.now()-b.D;var e=a.B;d=mb();C(d,new pb(d,c,b,e));bc(a)}else ac(a);else if(e=b.m,e==3||e==0&&b.X>0||!(d==1&&Zc(a,b)||d==2&&Wb(a)))switch(c&&c.length>0&&(b=a.h,b.i=b.i.concat(c)),e){case 1:R(a,5);break;case 4:R(a,10);break;case 3:R(a,6);break;default:R(a,2)}}
function $c(a,b){let c=a.Sa+Math.floor(Math.random()*a.bb);a.isActive()||(c*=2);return c*b}function R(a,b){a.j.info("Error code "+b);if(b==2){var c=p(a.eb,a),d=a.Wa;const e=!d;d=new T(d||"//www.google.com/images/cleardot.gif");k.location&&k.location.protocol=="http"||mc(d,"https");Db(d);e?Dc(d.toString(),c):Ec(d.toString(),c)}else H(2);a.G=0;a.l&&a.l.ra(b);Yc(a);Wc(a)}h.eb=function(a){a?(this.j.info("Successfully pinged google.com"),H(2)):(this.j.info("Failed to ping google.com"),H(1))};
function Yc(a){a.G=0;a.ka=[];if(a.l){const b=gc(a.h);if(b.length!=0||a.i.length!=0)ma(a.ka,b),ma(a.ka,a.i),a.h.i.length=0,la(a.i),a.i.length=0;a.l.qa()}}function Zb(a,b,c){var d=c instanceof T?O(c):new T(c);if(d.g!="")b&&(d.g=b+"."+d.g),nc(d,d.s);else{var e=k.location;d=e.protocol;b=b?b+"."+e.hostname:e.hostname;e=+e.port;const f=new T(null);d&&mc(f,d);b&&(f.g=b);e&&nc(f,e);c&&(f.h=c);d=f}c=a.F;b=a.xa;c&&b&&S(d,c,b);S(d,"VER",a.la);Xc(a,d);return d}
function Hb(a,b,c){if(b&&!a.J)throw Error("Can't create secondary domain capable XhrIo object.");b=a.Ba&&!a.oa?new X(new Hc({cb:c})):new X(a.oa);b.Ga(a.J);return b}h.isActive=function(){return!!this.l&&this.l.isActive(this)};function dd(){}h=dd.prototype;h.ta=function(){};h.sa=function(){};h.ra=function(){};h.qa=function(){};h.isActive=function(){return!0};h.Ma=function(){};function ed(){}ed.prototype.g=function(a,b){return new Y(a,b)};
function Y(a,b){B.call(this);this.g=new Vc(b);this.l=a;this.h=b&&b.messageUrlParams||null;a=b&&b.messageHeaders||null;b&&b.clientProtocolHeaderRequired&&(a?a["X-Client-Protocol"]="webchannel":a={"X-Client-Protocol":"webchannel"});this.g.o=a;a=b&&b.initMessageHeaders||null;b&&b.messageContentType&&(a?a["X-WebChannel-Content-Type"]=b.messageContentType:a={"X-WebChannel-Content-Type":b.messageContentType});b&&b.ua&&(a?a["X-WebChannel-Client-Profile"]=b.ua:a={"X-WebChannel-Client-Profile":b.ua});this.g.S=
a;(a=b&&b.Rb)&&!y(a)&&(this.g.s=a);this.v=b&&b.supportsCrossDomainXhr||!1;this.u=b&&b.sendRawJson||!1;(b=b&&b.httpSessionIdParam)&&!y(b)&&(this.g.F=b,a=this.h,a!==null&&b in a&&(a=this.h,b in a&&delete a[b]));this.j=new Z(this)}r(Y,B);Y.prototype.m=function(){this.g.l=this.j;this.v&&(this.g.J=!0);this.g.connect(this.l,this.h||void 0)};Y.prototype.close=function(){cc(this.g)};
Y.prototype.o=function(a){var b=this.g;if(typeof a==="string"){var c={};c.__data__=a;a=c}else this.u&&(c={},c.__data__=eb(a),a=c);b.i.push(new dc(b.Xa++,a));b.G==3&&bc(b)};Y.prototype.M=function(){this.g.l=null;delete this.j;cc(this.g);delete this.g;Y.Z.M.call(this)};
function fd(a){jb.call(this);a.__headers__&&(this.headers=a.__headers__,this.statusCode=a.__status__,delete a.__headers__,delete a.__status__);var b=a.__sm__;if(b){a:{for(const c in b){a=c;break a}a=void 0}if(this.i=a)a=this.i,b=b!==null&&a in b?b[a]:void 0;this.data=b}else this.data=a}r(fd,jb);function gd(){kb.call(this);this.status=1}r(gd,kb);function Z(a){this.g=a}r(Z,dd);Z.prototype.ta=function(){C(this.g,"a")};Z.prototype.sa=function(a){C(this.g,new fd(a))};
Z.prototype.ra=function(a){C(this.g,new gd(a))};Z.prototype.qa=function(){C(this.g,"b")};ed.prototype.createWebChannel=ed.prototype.g;Y.prototype.send=Y.prototype.o;Y.prototype.open=Y.prototype.m;Y.prototype.close=Y.prototype.close;module.exports.createWebChannelTransport=function(){return new ed};module.exports.getStatEventTarget=function(){return mb()};module.exports.Event=F;module.exports.Stat={lb:0,ob:1,pb:2,Ib:3,Nb:4,Kb:5,Lb:6,Jb:7,Hb:8,Mb:9,PROXY:10,NOPROXY:11,Fb:12,Bb:13,Cb:14,Ab:15,Db:16,Eb:17,hb:18,gb:19,ib:20};ub.NO_ERROR=0;ub.TIMEOUT=8;ub.HTTP_ERROR=6;
module.exports.ErrorCode=ub;vb.COMPLETE="complete";module.exports.EventType=vb;ib.EventType=E;E.OPEN="a";E.CLOSE="b";E.ERROR="c";E.MESSAGE="d";B.prototype.listen=B.prototype.I;module.exports.WebChannel=ib;module.exports.FetchXmlHttpFactory=Hc;X.prototype.listenOnce=X.prototype.J;X.prototype.getLastError=X.prototype.Ja;X.prototype.getLastErrorCode=X.prototype.Aa;X.prototype.getStatus=X.prototype.ca;X.prototype.getResponseJson=X.prototype.Na;X.prototype.getResponseText=X.prototype.na;
X.prototype.send=X.prototype.ea;X.prototype.setWithCredentials=X.prototype.Ga;module.exports.XhrIo=X;}).apply( typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self  : typeof window !== 'undefined' ? window  : {});
