/** @license
Copyright The Closure Library Authors.
SPDX-License-Identifier: Apache-2.0
*/
(function() {'use strict';var h,aa=Object.defineProperty;function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this);
function da(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&aa(c,a,{configurable:!0,writable:!0,value:b})}}da("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});da("Array.prototype.values",function(a){return a?a:function(){return this[Symbol.iterator]()}});
da("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push([d,b[d]]);return c}});/** @license

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ea=ea||{},l=this||self;function n(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}function fa(a,b,c){return a.call.apply(a.bind,arguments)}function p(a,b,c){p=fa;return p.apply(null,arguments)}function ha(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}
function t(a,b){function c(){}c.prototype=b.prototype;a.Z=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ob=function(d,e,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[e].apply(d,g)}};var ia=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?a=>a&&AsyncContext.Snapshot.wrap(a):a=>a;function ja(a){const b=a.length;if(b>0){const c=Array(b);for(let d=0;d<b;d++)c[d]=a[d];return c}return[]}function ka(a,b){for(let d=1;d<arguments.length;d++){const e=arguments[d];var c=typeof e;c=c!="object"?c:e?Array.isArray(e)?"array":c:"null";if(c=="array"||c=="object"&&typeof e.length=="number"){c=a.length||0;const f=e.length||0;a.length=c+f;for(let g=0;g<f;g++)a[c+g]=e[g]}else a.push(e)}};class la{constructor(a,b){this.i=a;this.j=b;this.h=0;this.g=null}get(){let a;this.h>0?(this.h--,a=this.g,this.g=a.next,a.next=null):a=this.i();return a}};function ma(a){l.setTimeout(()=>{throw a;},0)};function na(){var a=oa;let b=null;a.g&&(b=a.g,a.g=a.g.next,a.g||(a.h=null),b.next=null);return b}class pa{constructor(){this.h=this.g=null}add(a,b){const c=qa.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c}}var qa=new la(()=>new ra,a=>a.reset());class ra{constructor(){this.next=this.g=this.h=null}set(a,b){this.h=a;this.g=b;this.next=null}reset(){this.next=this.g=this.h=null}};let u,v=!1,oa=new pa,ta=()=>{const a=Promise.resolve(void 0);u=()=>{a.then(sa)}};function sa(){for(var a;a=na();){try{a.h.call(a.g)}catch(c){ma(c)}var b=qa;b.j(a);b.h<100&&(b.h++,a.next=b.g,b.g=a)}v=!1};function w(){this.u=this.u;this.C=this.C}w.prototype.u=!1;w.prototype.dispose=function(){this.u||(this.u=!0,this.N())};w.prototype[Symbol.dispose]=function(){this.dispose()};w.prototype.N=function(){if(this.C)for(;this.C.length;)this.C.shift()()};function x(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1}x.prototype.h=function(){this.defaultPrevented=!0};var ua=function(){if(!l.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{const c=()=>{};l.addEventListener("test",c,b);l.removeEventListener("test",c,b)}catch(c){}return a}();function y(a){return/^[\s\xa0]*$/.test(a)};function z(a,b){x.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.i=null;a&&this.init(a,b)}t(z,x);
z.prototype.init=function(a,b){const c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;b=a.relatedTarget;b||(c=="mouseover"?b=a.fromElement:c=="mouseout"&&(b=a.toElement));this.relatedTarget=b;d?(this.clientX=d.clientX!==void 0?d.clientX:d.pageX,this.clientY=d.clientY!==void 0?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=a.clientX!==void 0?a.clientX:a.pageX,this.clientY=a.clientY!==
void 0?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=a.pointerType;this.state=a.state;this.i=a;a.defaultPrevented&&z.Z.h.call(this)};z.prototype.h=function(){z.Z.h.call(this);const a=this.i;a.preventDefault?a.preventDefault():a.returnValue=!1};var B="closure_listenable_"+(Math.random()*1E6|0);var va=0;function wa(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.ha=e;this.key=++va;this.da=this.fa=!1}function xa(a){a.da=!0;a.listener=null;a.proxy=null;a.src=null;a.ha=null};function ya(a,b,c){for(const d in a)b.call(c,a[d],d,a)}function za(a,b){for(const c in a)b.call(void 0,a[c],c,a)}function Aa(a){const b={};for(const c in a)b[c]=a[c];return b}const Ba="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ca(a,b){let c,d;for(let e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(let f=0;f<Ba.length;f++)c=Ba[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Da(a){this.src=a;this.g={};this.h=0}Da.prototype.add=function(a,b,c,d,e){const f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);const g=Ea(a,b,d,e);g>-1?(b=a[g],c||(b.fa=!1)):(b=new wa(b,this.src,f,!!d,e),b.fa=c,a.push(b));return b};function Fa(a,b){const c=b.type;if(c in a.g){var d=a.g[c],e=Array.prototype.indexOf.call(d,b,void 0),f;(f=e>=0)&&Array.prototype.splice.call(d,e,1);f&&(xa(b),a.g[c].length==0&&(delete a.g[c],a.h--))}}
function Ea(a,b,c,d){for(let e=0;e<a.length;++e){const f=a[e];if(!f.da&&f.listener==b&&f.capture==!!c&&f.ha==d)return e}return-1};var Ga="closure_lm_"+(Math.random()*1E6|0),Ha={},Ia=0;function Ja(a,b,c,d,e){if(d&&d.once)return Ka(a,b,c,d,e);if(Array.isArray(b)){for(let f=0;f<b.length;f++)Ja(a,b[f],c,d,e);return null}c=La(c);return a&&a[B]?a.J(b,c,n(d)?!!d.capture:!!d,e):Ma(a,b,c,!1,d,e)}
function Ma(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");const g=n(e)?!!e.capture:!!e;let k=Na(a);k||(a[Ga]=k=new Da(a));c=k.add(b,c,d,g,f);if(c.proxy)return c;d=Oa();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)ua||(e=g),e===void 0&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Pa(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Ia++;return c}
function Oa(){function a(c){return b.call(a.src,a.listener,c)}const b=Qa;return a}function Ka(a,b,c,d,e){if(Array.isArray(b)){for(let f=0;f<b.length;f++)Ka(a,b[f],c,d,e);return null}c=La(c);return a&&a[B]?a.K(b,c,n(d)?!!d.capture:!!d,e):Ma(a,b,c,!0,d,e)}
function Ra(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Ra(a,b[f],c,d,e);else(d=n(d)?!!d.capture:!!d,c=La(c),a&&a[B])?(a=a.i,f=String(b).toString(),f in a.g&&(b=a.g[f],c=Ea(b,c,d,e),c>-1&&(xa(b[c]),Array.prototype.splice.call(b,c,1),b.length==0&&(delete a.g[f],a.h--)))):a&&(a=Na(a))&&(b=a.g[b.toString()],a=-1,b&&(a=Ea(b,c,d,e)),(c=a>-1?b[a]:null)&&Sa(c))}
function Sa(a){if(typeof a!=="number"&&a&&!a.da){var b=a.src;if(b&&b[B])Fa(b.i,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Pa(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Ia--;(c=Na(b))?(Fa(c,a),c.h==0&&(c.src=null,b[Ga]=null)):xa(a)}}}function Pa(a){return a in Ha?Ha[a]:Ha[a]="on"+a}function Qa(a,b){if(a.da)a=!0;else{b=new z(b,this);const c=a.listener,d=a.ha||a.src;a.fa&&Sa(a);a=c.call(d,b)}return a}
function Na(a){a=a[Ga];return a instanceof Da?a:null}var Ta="__closure_events_fn_"+(Math.random()*1E9>>>0);function La(a){if(typeof a==="function")return a;a[Ta]||(a[Ta]=function(b){return a.handleEvent(b)});return a[Ta]};function C(){w.call(this);this.i=new Da(this);this.M=this;this.G=null}t(C,w);C.prototype[B]=!0;C.prototype.removeEventListener=function(a,b,c,d){Ra(this,a,b,c,d)};
function F(a,b){var c,d=a.G;if(d)for(c=[];d;d=d.G)c.push(d);a=a.M;d=b.type||b;if(typeof b==="string")b=new x(b,a);else if(b instanceof x)b.target=b.target||a;else{var e=b;b=new x(d,a);Ca(b,e)}e=!0;let f,g;if(c)for(g=c.length-1;g>=0;g--)f=b.g=c[g],e=Ua(f,d,!0,b)&&e;f=b.g=a;e=Ua(f,d,!0,b)&&e;e=Ua(f,d,!1,b)&&e;if(c)for(g=0;g<c.length;g++)f=b.g=c[g],e=Ua(f,d,!1,b)&&e}
C.prototype.N=function(){C.Z.N.call(this);if(this.i){var a=this.i;let b=0;for(const c in a.g){const d=a.g[c];for(let e=0;e<d.length;e++)++b,xa(d[e]);delete a.g[c];a.h--}}this.G=null};C.prototype.J=function(a,b,c,d){return this.i.add(String(a),b,!1,c,d)};C.prototype.K=function(a,b,c,d){return this.i.add(String(a),b,!0,c,d)};
function Ua(a,b,c,d){b=a.i.g[String(b)];if(!b)return!0;b=b.concat();let e=!0;for(let f=0;f<b.length;++f){const g=b[f];if(g&&!g.da&&g.capture==c){const k=g.listener,q=g.ha||g.src;g.fa&&Fa(a.i,g);e=k.call(q,d)!==!1&&e}}return e&&!d.defaultPrevented};function Va(a,b){if(typeof a!=="function")if(a&&typeof a.handleEvent=="function")a=p(a.handleEvent,a);else throw Error("Invalid listener argument");return Number(b)>2147483647?-1:l.setTimeout(a,b||0)};function Wa(a){a.g=Va(()=>{a.g=null;a.i&&(a.i=!1,Wa(a))},a.l);const b=a.h;a.h=null;a.m.apply(null,b)}class Xa extends w{constructor(a,b){super();this.m=a;this.l=b;this.h=null;this.i=!1;this.g=null}j(a){this.h=arguments;this.g?this.i=!0:Wa(this)}N(){super.N();this.g&&(l.clearTimeout(this.g),this.g=null,this.i=!1,this.h=null)}};function G(a){w.call(this);this.h=a;this.g={}}t(G,w);var Ya=[];function Za(a){ya(a.g,function(b,c){this.g.hasOwnProperty(c)&&Sa(b)},a);a.g={}}G.prototype.N=function(){G.Z.N.call(this);Za(this)};G.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var $a=l.JSON.stringify;var bb=l.JSON.parse;var cb=class{stringify(a){return l.JSON.stringify(a,void 0)}parse(a){return l.JSON.parse(a,void 0)}};function db(){};function eb(){}var H={OPEN:"a",hb:"b",ERROR:"c",tb:"d"};function fb(){x.call(this,"d")}t(fb,x);function gb(){x.call(this,"c")}t(gb,x);var I={},hb=null;function ib(){return hb=hb||new C}I.Ia="serverreachability";function jb(a){x.call(this,I.Ia,a)}t(jb,x);function kb(a){const b=ib();F(b,new jb(b,a))}I.STAT_EVENT="statevent";function lb(a,b){x.call(this,I.STAT_EVENT,a);this.stat=b}t(lb,x);function J(a){const b=ib();F(b,new lb(b,a))}I.Ja="timingevent";function mb(a,b){x.call(this,I.Ja,a);this.size=b}t(mb,x);
function nb(a,b){if(typeof a!=="function")throw Error("Fn must not be null and must be a function");return l.setTimeout(function(){a()},b)};function ob(){this.g=!0}ob.prototype.ua=function(){this.g=!1};function pb(a,b,c,d,e,f){a.info(function(){if(a.g)if(f){var g="";var k=f.split("&");for(let m=0;m<k.length;m++){var q=k[m].split("=");if(q.length>1){const r=q[0];q=q[1];const A=r.split("_");g=A.length>=2&&A[1]=="type"?g+(r+"="+q+"&"):g+(r+"=redacted&")}}}else g=null;else g=f;return"XMLHTTP REQ ("+d+") [attempt "+e+"]: "+b+"\n"+c+"\n"+g})}
function qb(a,b,c,d,e,f,g){a.info(function(){return"XMLHTTP RESP ("+d+") [ attempt "+e+"]: "+b+"\n"+c+"\n"+f+" "+g})}function K(a,b,c,d){a.info(function(){return"XMLHTTP TEXT ("+b+"): "+rb(a,c)+(d?" "+d:"")})}function sb(a,b){a.info(function(){return"TIMEOUT: "+b})}ob.prototype.info=function(){};
function rb(a,b){if(!a.g)return b;if(!b)return null;try{const f=JSON.parse(b);if(f)for(a=0;a<f.length;a++)if(Array.isArray(f[a])){var c=f[a];if(!(c.length<2)){var d=c[1];if(Array.isArray(d)&&!(d.length<1)){var e=d[0];if(e!="noop"&&e!="stop"&&e!="close")for(let g=1;g<d.length;g++)d[g]=""}}}return $a(f)}catch(f){return b}};var tb={NO_ERROR:0,cb:1,qb:2,pb:3,kb:4,ob:5,rb:6,Ga:7,TIMEOUT:8,ub:9};var ub={ib:"complete",Fb:"success",ERROR:"error",Ga:"abort",xb:"ready",yb:"readystatechange",TIMEOUT:"timeout",sb:"incrementaldata",wb:"progress",lb:"downloadprogress",Nb:"uploadprogress"};var vb;function wb(){}t(wb,db);wb.prototype.g=function(){return new XMLHttpRequest};vb=new wb;function L(a){return encodeURIComponent(String(a))}function xb(a){var b=1;a=a.split(":");const c=[];for(;b>0&&a.length;)c.push(a.shift()),b--;a.length&&c.push(a.join(":"));return c};function N(a,b,c,d){this.j=a;this.i=b;this.l=c;this.S=d||1;this.V=new G(this);this.H=45E3;this.J=null;this.o=!1;this.u=this.B=this.A=this.M=this.F=this.T=this.D=null;this.G=[];this.g=null;this.C=0;this.m=this.v=null;this.X=-1;this.K=!1;this.P=0;this.O=null;this.W=this.L=this.U=this.R=!1;this.h=new yb}function yb(){this.i=null;this.g="";this.h=!1}var zb={},Ab={};function Bb(a,b,c){a.M=1;a.A=Cb(O(b));a.u=c;a.R=!0;Db(a,null)}
function Db(a,b){a.F=Date.now();Eb(a);a.B=O(a.A);var c=a.B,d=a.S;Array.isArray(d)||(d=[String(d)]);Fb(c.i,"t",d);a.C=0;c=a.j.K;a.h=new yb;a.g=Gb(a.j,c?b:null,!a.u);a.P>0&&(a.O=new Xa(p(a.Y,a,a.g),a.P));b=a.V;c=a.g;d=a.ba;var e="readystatechange";Array.isArray(e)||(e&&(Ya[0]=e.toString()),e=Ya);for(let f=0;f<e.length;f++){const g=Ja(c,e[f],d||b.handleEvent,!1,b.h||b);if(!g)break;b.g[g.key]=g}b=a.J?Aa(a.J):{};a.u?(a.v||(a.v="POST"),b["Content-Type"]="application/x-www-form-urlencoded",a.g.ea(a.B,a.v,
a.u,b)):(a.v="GET",a.g.ea(a.B,a.v,null,b));kb(1);pb(a.i,a.v,a.B,a.l,a.S,a.u)}N.prototype.ba=function(a){a=a.target;const b=this.O;b&&P(a)==3?b.j():this.Y(a)};
N.prototype.Y=function(a){try{if(a==this.g)a:{const k=P(this.g),q=this.g.ya(),m=this.g.ca();if(!(k<3)&&(k!=3||this.g&&(this.h.h||this.g.la()||Hb(this.g)))){this.K||k!=4||q==7||(q==8||m<=0?kb(3):kb(2));Ib(this);var b=this.g.ca();this.X=b;var c=Jb(this);this.o=b==200;qb(this.i,this.v,this.B,this.l,this.S,k,b);if(this.o){if(this.U&&!this.L){b:{if(this.g){var d,e=this.g;if((d=e.g?e.g.getResponseHeader("X-HTTP-Initial-Response"):null)&&!y(d)){var f=d;break b}}f=null}if(a=f)K(this.i,this.l,a,"Initial handshake response via X-HTTP-Initial-Response"),
this.L=!0,Kb(this,a);else{this.o=!1;this.m=3;J(12);Q(this);Lb(this);break a}}if(this.R){a=!0;let r;for(;!this.K&&this.C<c.length;)if(r=Mb(this,c),r==Ab){k==4&&(this.m=4,J(14),a=!1);K(this.i,this.l,null,"[Incomplete Response]");break}else if(r==zb){this.m=4;J(15);K(this.i,this.l,c,"[Invalid Chunk]");a=!1;break}else K(this.i,this.l,r,null),Kb(this,r);Nb(this)&&this.C!=0&&(this.h.g=this.h.g.slice(this.C),this.C=0);k!=4||c.length!=0||this.h.h||(this.m=1,J(16),a=!1);this.o=this.o&&a;if(!a)K(this.i,this.l,
c,"[Invalid Chunked Response]"),Q(this),Lb(this);else if(c.length>0&&!this.W){this.W=!0;var g=this.j;g.g==this&&g.aa&&!g.O&&(g.j.info("Great, no buffering proxy detected. Bytes received: "+c.length),Ob(g),g.O=!0,J(11))}}else K(this.i,this.l,c,null),Kb(this,c);k==4&&Q(this);this.o&&!this.K&&(k==4?Pb(this.j,this):(this.o=!1,Eb(this)))}else Qb(this.g),b==400&&c.indexOf("Unknown SID")>0?(this.m=3,J(12)):(this.m=0,J(13)),Q(this),Lb(this)}}}catch(k){}finally{}};
function Jb(a){if(!Nb(a))return a.g.la();const b=Hb(a.g);if(b==="")return"";let c="";const d=b.length,e=P(a.g)==4;if(!a.h.i){if(typeof TextDecoder==="undefined")return Q(a),Lb(a),"";a.h.i=new l.TextDecoder}for(let f=0;f<d;f++)a.h.h=!0,c+=a.h.i.decode(b[f],{stream:!(e&&f==d-1)});b.length=0;a.h.g+=c;a.C=0;return a.h.g}function Nb(a){return a.g?a.v=="GET"&&a.M!=2&&a.j.Aa:!1}
function Mb(a,b){var c=a.C,d=b.indexOf("\n",c);if(d==-1)return Ab;c=Number(b.substring(c,d));if(isNaN(c))return zb;d+=1;if(d+c>b.length)return Ab;b=b.slice(d,d+c);a.C=d+c;return b}N.prototype.cancel=function(){this.K=!0;Q(this)};function Eb(a){a.T=Date.now()+a.H;Rb(a,a.H)}function Rb(a,b){if(a.D!=null)throw Error("WatchDog timer not null");a.D=nb(p(a.aa,a),b)}function Ib(a){a.D&&(l.clearTimeout(a.D),a.D=null)}
N.prototype.aa=function(){this.D=null;const a=Date.now();a-this.T>=0?(sb(this.i,this.B),this.M!=2&&(kb(3),J(17)),Q(this),this.m=2,Lb(this)):Rb(this,this.T-a)};function Lb(a){a.j.I==0||a.K||Pb(a.j,a)}function Q(a){Ib(a);var b=a.O;b&&typeof b.dispose=="function"&&b.dispose();a.O=null;Za(a.V);a.g&&(b=a.g,a.g=null,b.abort(),b.dispose())}
function Kb(a,b){try{var c=a.j;if(c.I!=0&&(c.g==a||Sb(c.h,a)))if(!a.L&&Sb(c.h,a)&&c.I==3){try{var d=c.Ba.g.parse(b)}catch(m){d=null}if(Array.isArray(d)&&d.length==3){var e=d;if(e[0]==0)a:{if(!c.v){if(c.g)if(c.g.F+3E3<a.F)Tb(c),Ub(c);else break a;Vb(c);J(18)}}else c.xa=e[1],0<c.xa-c.U&&e[2]<37500&&c.F&&c.A==0&&!c.C&&(c.C=nb(p(c.Va,c),6E3));Wb(c.h)<=1&&c.ta&&(c.ta=void 0)}else R(c,11)}else if((a.L||c.g==a)&&Tb(c),!y(b))for(e=c.Ba.g.parse(b),b=0;b<e.length;b++){let m=e[b];c.U=m[0];m=m[1];if(c.I==2)if(m[0]==
"c"){c.L=m[1];c.ba=m[2];const r=m[3];r!=null&&(c.ka=r,c.j.info("VER="+c.ka));const A=m[4];A!=null&&(c.za=A,c.j.info("SVER="+c.za));const D=m[5];D!=null&&typeof D==="number"&&D>0&&(d=1.5*D,c.M=d,c.j.info("backChannelRequestTimeoutMs_="+d));d=c;const E=a.g;if(E){const M=E.g?E.g.getResponseHeader("X-Client-Wire-Protocol"):null;if(M){var f=d.h;f.g||M.indexOf("spdy")==-1&&M.indexOf("quic")==-1&&M.indexOf("h2")==-1||(f.j=f.l,f.g=new Set,f.h&&(Xb(f,f.h),f.h=null))}if(d.G){const ab=E.g?E.g.getResponseHeader("X-HTTP-Session-Id"):
null;ab&&(d.wa=ab,S(d.J,d.G,ab))}}c.I=3;c.l&&c.l.ra();c.aa&&(c.S=Date.now()-a.F,c.j.info("Handshake RTT: "+c.S+"ms"));d=c;var g=a;d.na=Yb(d,d.K?d.ba:null,d.W);if(g.L){Zb(d.h,g);var k=g,q=d.M;q&&(k.H=q);k.D&&(Ib(k),Eb(k));d.g=g}else $b(d);c.i.length>0&&ac(c)}else m[0]!="stop"&&m[0]!="close"||R(c,7);else c.I==3&&(m[0]=="stop"||m[0]=="close"?m[0]=="stop"?R(c,7):bc(c):m[0]!="noop"&&c.l&&c.l.qa(m),c.A=0)}kb(4)}catch(m){}};var cc=class{constructor(a,b){this.g=a;this.map=b}};function dc(a){this.l=a||10;l.PerformanceNavigationTiming?(a=l.performance.getEntriesByType("navigation"),a=a.length>0&&(a[0].nextHopProtocol=="hq"||a[0].nextHopProtocol=="h2")):a=!!(l.chrome&&l.chrome.loadTimes&&l.chrome.loadTimes()&&l.chrome.loadTimes().wasFetchedViaSpdy);this.j=a?this.l:1;this.g=null;this.j>1&&(this.g=new Set);this.h=null;this.i=[]}function ec(a){return a.h?!0:a.g?a.g.size>=a.j:!1}function Wb(a){return a.h?1:a.g?a.g.size:0}function Sb(a,b){return a.h?a.h==b:a.g?a.g.has(b):!1}
function Xb(a,b){a.g?a.g.add(b):a.h=b}function Zb(a,b){a.h&&a.h==b?a.h=null:a.g&&a.g.has(b)&&a.g.delete(b)}dc.prototype.cancel=function(){this.i=fc(this);if(this.h)this.h.cancel(),this.h=null;else if(this.g&&this.g.size!==0){for(const a of this.g.values())a.cancel();this.g.clear()}};function fc(a){if(a.h!=null)return a.i.concat(a.h.G);if(a.g!=null&&a.g.size!==0){let b=a.i;for(const c of a.g.values())b=b.concat(c.G);return b}return ja(a.i)};var hc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function ic(a,b){if(a){a=a.split("&");for(let c=0;c<a.length;c++){const d=a[c].indexOf("=");let e,f=null;d>=0?(e=a[c].substring(0,d),f=a[c].substring(d+1)):e=a[c];b(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};function T(a){this.g=this.o=this.j="";this.u=null;this.m=this.h="";this.l=!1;let b;a instanceof T?(this.l=a.l,jc(this,a.j),this.o=a.o,this.g=a.g,kc(this,a.u),this.h=a.h,lc(this,mc(a.i)),this.m=a.m):a&&(b=String(a).match(hc))?(this.l=!1,jc(this,b[1]||"",!0),this.o=nc(b[2]||""),this.g=nc(b[3]||"",!0),kc(this,b[4]),this.h=nc(b[5]||"",!0),lc(this,b[6]||"",!0),this.m=nc(b[7]||"")):(this.l=!1,this.i=new oc(null,this.l))}
T.prototype.toString=function(){const a=[];var b=this.j;b&&a.push(pc(b,qc,!0),":");var c=this.g;if(c||b=="file")a.push("//"),(b=this.o)&&a.push(pc(b,qc,!0),"@"),a.push(L(c).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.u,c!=null&&a.push(":",String(c));if(c=this.h)this.g&&c.charAt(0)!="/"&&a.push("/"),a.push(pc(c,c.charAt(0)=="/"?rc:sc,!0));(c=this.i.toString())&&a.push("?",c);(c=this.m)&&a.push("#",pc(c,tc));return a.join("")};
T.prototype.resolve=function(a){const b=O(this);let c=!!a.j;c?jc(b,a.j):c=!!a.o;c?b.o=a.o:c=!!a.g;c?b.g=a.g:c=a.u!=null;var d=a.h;if(c)kc(b,a.u);else if(c=!!a.h){if(d.charAt(0)!="/")if(this.g&&!this.h)d="/"+d;else{var e=b.h.lastIndexOf("/");e!=-1&&(d=b.h.slice(0,e+1)+d)}e=d;if(e==".."||e==".")d="";else if(e.indexOf("./")!=-1||e.indexOf("/.")!=-1){d=e.lastIndexOf("/",0)==0;e=e.split("/");const f=[];for(let g=0;g<e.length;){const k=e[g++];k=="."?d&&g==e.length&&f.push(""):k==".."?((f.length>1||f.length==
1&&f[0]!="")&&f.pop(),d&&g==e.length&&f.push("")):(f.push(k),d=!0)}d=f.join("/")}else d=e}c?b.h=d:c=a.i.toString()!=="";c?lc(b,mc(a.i)):c=!!a.m;c&&(b.m=a.m);return b};function O(a){return new T(a)}function jc(a,b,c){a.j=c?nc(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))}function kc(a,b){if(b){b=Number(b);if(isNaN(b)||b<0)throw Error("Bad port number "+b);a.u=b}else a.u=null}function lc(a,b,c){b instanceof oc?(a.i=b,uc(a.i,a.l)):(c||(b=pc(b,vc)),a.i=new oc(b,a.l))}function S(a,b,c){a.i.set(b,c)}
function Cb(a){S(a,"zx",Math.floor(Math.random()*2147483648).toString(36)+Math.abs(Math.floor(Math.random()*2147483648)^Date.now()).toString(36));return a}function nc(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function pc(a,b,c){return typeof a==="string"?(a=encodeURI(a).replace(b,wc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function wc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}
var qc=/[#\/\?@]/g,sc=/[#\?:]/g,rc=/[#\?]/g,vc=/[#\?@]/g,tc=/#/g;function oc(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b}function U(a){a.g||(a.g=new Map,a.h=0,a.i&&ic(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}h=oc.prototype;h.add=function(a,b){U(this);this.i=null;a=V(this,a);let c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};function xc(a,b){U(a);b=V(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a.g.delete(b))}
function yc(a,b){U(a);b=V(a,b);return a.g.has(b)}h.forEach=function(a,b){U(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};function zc(a,b){U(a);let c=[];if(typeof b==="string")yc(a,b)&&(c=c.concat(a.g.get(V(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c}h.set=function(a,b){U(this);this.i=null;a=V(this,a);yc(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};
h.get=function(a,b){if(!a)return b;a=zc(this,a);return a.length>0?String(a[0]):b};function Fb(a,b,c){xc(a,b);c.length>0&&(a.i=null,a.g.set(V(a,b),ja(c)),a.h+=c.length)}h.toString=function(){if(this.i)return this.i;if(!this.g)return"";const a=[],b=Array.from(this.g.keys());for(let d=0;d<b.length;d++){var c=b[d];const e=L(c);c=zc(this,c);for(let f=0;f<c.length;f++){let g=e;c[f]!==""&&(g+="="+L(c[f]));a.push(g)}}return this.i=a.join("&")};
function mc(a){const b=new oc;b.i=a.i;a.g&&(b.g=new Map(a.g),b.h=a.h);return b}function V(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b}function uc(a,b){b&&!a.j&&(U(a),a.i=null,a.g.forEach(function(c,d){const e=d.toLowerCase();d!=e&&(xc(this,d),Fb(this,e,c))},a));a.j=b};function Ac(a,b){const c=new ob;if(l.Image){const d=new Image;d.onload=ha(W,c,"TestLoadImage: loaded",!0,b,d);d.onerror=ha(W,c,"TestLoadImage: error",!1,b,d);d.onabort=ha(W,c,"TestLoadImage: abort",!1,b,d);d.ontimeout=ha(W,c,"TestLoadImage: timeout",!1,b,d);l.setTimeout(function(){if(d.ontimeout)d.ontimeout()},1E4);d.src=a}else b(!1)}
function Bc(a,b){const c=new ob,d=new AbortController,e=setTimeout(()=>{d.abort();W(c,"TestPingServer: timeout",!1,b)},1E4);fetch(a,{signal:d.signal}).then(f=>{clearTimeout(e);f.ok?W(c,"TestPingServer: ok",!0,b):W(c,"TestPingServer: server error",!1,b)}).catch(()=>{clearTimeout(e);W(c,"TestPingServer: error",!1,b)})}function W(a,b,c,d,e){try{e&&(e.onload=null,e.onerror=null,e.onabort=null,e.ontimeout=null),d(c)}catch(f){}};function Cc(){this.g=new cb};function Dc(a){this.i=a.Sb||null;this.h=a.ab||!1}t(Dc,db);Dc.prototype.g=function(){return new Ec(this.i,this.h)};function Ec(a,b){C.call(this);this.H=a;this.o=b;this.m=void 0;this.status=this.readyState=0;this.responseType=this.responseText=this.response=this.statusText="";this.onreadystatechange=null;this.A=new Headers;this.h=null;this.F="GET";this.D="";this.g=!1;this.B=this.j=this.l=null;this.v=new AbortController}t(Ec,C);h=Ec.prototype;
h.open=function(a,b){if(this.readyState!=0)throw this.abort(),Error("Error reopening a connection");this.F=a;this.D=b;this.readyState=1;Fc(this)};h.send=function(a){if(this.readyState!=1)throw this.abort(),Error("need to call open() first. ");if(this.v.signal.aborted)throw this.abort(),Error("Request was aborted.");this.g=!0;const b={headers:this.A,method:this.F,credentials:this.m,cache:void 0,signal:this.v.signal};a&&(b.body=a);(this.H||l).fetch(new Request(this.D,b)).then(this.Pa.bind(this),this.ga.bind(this))};
h.abort=function(){this.response=this.responseText="";this.A=new Headers;this.status=0;this.v.abort();this.j&&this.j.cancel("Request was aborted.").catch(()=>{});this.readyState>=1&&this.g&&this.readyState!=4&&(this.g=!1,Gc(this));this.readyState=0};
h.Pa=function(a){if(this.g&&(this.l=a,this.h||(this.status=this.l.status,this.statusText=this.l.statusText,this.h=a.headers,this.readyState=2,Fc(this)),this.g&&(this.readyState=3,Fc(this),this.g)))if(this.responseType==="arraybuffer")a.arrayBuffer().then(this.Na.bind(this),this.ga.bind(this));else if(typeof l.ReadableStream!=="undefined"&&"body"in a){this.j=a.body.getReader();if(this.o){if(this.responseType)throw Error('responseType must be empty for "streamBinaryChunks" mode responses.');this.response=
[]}else this.response=this.responseText="",this.B=new TextDecoder;Hc(this)}else a.text().then(this.Oa.bind(this),this.ga.bind(this))};function Hc(a){a.j.read().then(a.Ma.bind(a)).catch(a.ga.bind(a))}h.Ma=function(a){if(this.g){if(this.o&&a.value)this.response.push(a.value);else if(!this.o){var b=a.value?a.value:new Uint8Array(0);if(b=this.B.decode(b,{stream:!a.done}))this.response=this.responseText+=b}a.done?Gc(this):Fc(this);this.readyState==3&&Hc(this)}};
h.Oa=function(a){this.g&&(this.response=this.responseText=a,Gc(this))};h.Na=function(a){this.g&&(this.response=a,Gc(this))};h.ga=function(){this.g&&Gc(this)};function Gc(a){a.readyState=4;a.l=null;a.j=null;a.B=null;Fc(a)}h.setRequestHeader=function(a,b){this.A.append(a,b)};h.getResponseHeader=function(a){return this.h?this.h.get(a.toLowerCase())||"":""};
h.getAllResponseHeaders=function(){if(!this.h)return"";const a=[],b=this.h.entries();for(var c=b.next();!c.done;)c=c.value,a.push(c[0]+": "+c[1]),c=b.next();return a.join("\r\n")};function Fc(a){a.onreadystatechange&&a.onreadystatechange.call(a)}Object.defineProperty(Ec.prototype,"withCredentials",{get:function(){return this.m==="include"},set:function(a){this.m=a?"include":"same-origin"}});function Ic(a){let b="";ya(a,function(c,d){b+=d;b+=":";b+=c;b+="\r\n"});return b}function Jc(a,b,c){a:{for(d in c){var d=!1;break a}d=!0}d||(c=Ic(c),typeof a==="string"?(L(b),c!=null&&L(c)):S(a,b,c))};function X(a){C.call(this);this.headers=new Map;this.L=a||null;this.h=!1;this.g=null;this.D="";this.o=0;this.l="";this.j=this.B=this.v=this.A=!1;this.m=null;this.F="";this.H=!1}t(X,C);var Kc=/^https?$/i,Lc=["POST","PUT"];h=X.prototype;h.Fa=function(a){this.H=a};
h.ea=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.o=0;this.A=!1;this.h=!0;this.g=this.L?this.L.g():vb.g();this.g.onreadystatechange=ia(p(this.Ca,this));try{this.B=!0,this.g.open(b,String(a),!0),this.B=!1}catch(f){Mc(this,f);return}a=c||"";c=new Map(this.headers);if(d)if(Object.getPrototypeOf(d)===Object.prototype)for(var e in d)c.set(e,d[e]);else if(typeof d.keys==="function"&&
typeof d.get==="function")for(const f of d.keys())c.set(f,d.get(f));else throw Error("Unknown input type for opt_headers: "+String(d));d=Array.from(c.keys()).find(f=>"content-type"==f.toLowerCase());e=l.FormData&&a instanceof l.FormData;!(Array.prototype.indexOf.call(Lc,b,void 0)>=0)||d||e||c.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");for(const [f,g]of c)this.g.setRequestHeader(f,g);this.F&&(this.g.responseType=this.F);"withCredentials"in this.g&&this.g.withCredentials!==
this.H&&(this.g.withCredentials=this.H);try{this.m&&(clearTimeout(this.m),this.m=null),this.v=!0,this.g.send(a),this.v=!1}catch(f){Mc(this,f)}};function Mc(a,b){a.h=!1;a.g&&(a.j=!0,a.g.abort(),a.j=!1);a.l=b;a.o=5;Nc(a);Oc(a)}function Nc(a){a.A||(a.A=!0,F(a,"complete"),F(a,"error"))}h.abort=function(a){this.g&&this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1,this.o=a||7,F(this,"complete"),F(this,"abort"),Oc(this))};
h.N=function(){this.g&&(this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1),Oc(this,!0));X.Z.N.call(this)};h.Ca=function(){this.u||(this.B||this.v||this.j?Pc(this):this.Xa())};h.Xa=function(){Pc(this)};
function Pc(a){if(a.h&&typeof ea!="undefined")if(a.v&&P(a)==4)setTimeout(a.Ca.bind(a),0);else if(F(a,"readystatechange"),P(a)==4){a.h=!1;try{const f=a.ca();a:switch(f){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var b=!0;break a;default:b=!1}var c;if(!(c=b)){var d;if(d=f===0){let g=String(a.D).match(hc)[1]||null;!g&&l.self&&l.self.location&&(g=l.self.location.protocol.slice(0,-1));d=!Kc.test(g?g.toLowerCase():"")}c=d}if(c)F(a,"complete"),F(a,"success");else{a.o=6;try{var e=P(a)>
2?a.g.statusText:""}catch(g){e=""}a.l=e+" ["+a.ca()+"]";Nc(a)}}finally{Oc(a)}}}function Oc(a,b){if(a.g){a.m&&(clearTimeout(a.m),a.m=null);const c=a.g;a.g=null;b||F(a,"ready");try{c.onreadystatechange=null}catch(d){}}}h.isActive=function(){return!!this.g};function P(a){return a.g?a.g.readyState:0}h.ca=function(){try{return P(this)>2?this.g.status:-1}catch(a){return-1}};h.la=function(){try{return this.g?this.g.responseText:""}catch(a){return""}};
h.La=function(a){if(this.g){var b=this.g.responseText;a&&b.indexOf(a)==0&&(b=b.substring(a.length));return bb(b)}};function Hb(a){try{if(!a.g)return null;if("response"in a.g)return a.g.response;switch(a.F){case "":case "text":return a.g.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in a.g)return a.g.mozResponseArrayBuffer}return null}catch(b){return null}}
function Qb(a){const b={};a=(a.g&&P(a)>=2?a.g.getAllResponseHeaders()||"":"").split("\r\n");for(let d=0;d<a.length;d++){if(y(a[d]))continue;var c=xb(a[d]);const e=c[0];c=c[1];if(typeof c!=="string")continue;c=c.trim();const f=b[e]||[];b[e]=f;f.push(c)}za(b,function(d){return d.join(", ")})}h.ya=function(){return this.o};h.Ha=function(){return typeof this.l==="string"?this.l:String(this.l)};function Qc(a,b,c){return c&&c.internalChannelParams?c.internalChannelParams[a]||b:b}
function Rc(a){this.za=0;this.i=[];this.j=new ob;this.ba=this.na=this.J=this.W=this.g=this.wa=this.G=this.H=this.u=this.T=this.o=null;this.Ya=this.V=0;this.Sa=Qc("failFast",!1,a);this.F=this.C=this.v=this.m=this.l=null;this.X=!0;this.xa=this.U=-1;this.Y=this.A=this.D=0;this.Qa=Qc("baseRetryDelayMs",5E3,a);this.Za=Qc("retryDelaySeedMs",1E4,a);this.Ta=Qc("forwardChannelMaxRetries",2,a);this.va=Qc("forwardChannelRequestTimeoutMs",2E4,a);this.ma=a&&a.xmlHttpFactory||void 0;this.Ua=a&&a.Rb||void 0;this.Aa=
a&&a.useFetchStreams||!1;this.M=void 0;this.K=a&&a.supportsCrossDomainXhr||!1;this.L="";this.h=new dc(a&&a.concurrentRequestLimit);this.Ba=new Cc;this.R=a&&a.fastHandshake||!1;this.P=a&&a.encodeInitMessageHeaders||!1;this.R&&this.P&&(this.P=!1);this.Ra=a&&a.Pb||!1;a&&a.ua&&this.j.ua();a&&a.forceLongPolling&&(this.X=!1);this.aa=!this.R&&this.X&&a&&a.detectBufferingProxy||!1;this.ia=void 0;a&&a.longPollingTimeout&&a.longPollingTimeout>0&&(this.ia=a.longPollingTimeout);this.ta=void 0;this.S=0;this.O=
!1;this.ja=this.B=null}h=Rc.prototype;h.ka=8;h.I=1;h.connect=function(a,b,c,d){J(0);this.W=a;this.H=b||{};c&&d!==void 0&&(this.H.OSID=c,this.H.OAID=d);this.F=this.X;this.J=Yb(this,null,this.W);ac(this)};
function bc(a){Sc(a);if(a.I==3){var b=a.V++,c=O(a.J);S(c,"SID",a.L);S(c,"RID",b);S(c,"TYPE","terminate");Tc(a,c);b=new N(a,a.j,b);b.M=2;b.A=Cb(O(c));c=!1;if(l.navigator&&l.navigator.sendBeacon)try{c=l.navigator.sendBeacon(b.A.toString(),"")}catch(d){}!c&&l.Image&&((new Image).src=b.A,c=!0);c||(b.g=Gb(b.j,null),b.g.ea(b.A));b.F=Date.now();Eb(b)}Uc(a)}function Ub(a){a.g&&(Ob(a),a.g.cancel(),a.g=null)}
function Sc(a){Ub(a);a.v&&(l.clearTimeout(a.v),a.v=null);Tb(a);a.h.cancel();a.m&&(typeof a.m==="number"&&l.clearTimeout(a.m),a.m=null)}function ac(a){if(!ec(a.h)&&!a.m){a.m=!0;var b=a.Ea;u||ta();v||(u(),v=!0);oa.add(b,a);a.D=0}}function Vc(a,b){if(Wb(a.h)>=a.h.j-(a.m?1:0))return!1;if(a.m)return a.i=b.G.concat(a.i),!0;if(a.I==1||a.I==2||a.D>=(a.Sa?0:a.Ta))return!1;a.m=nb(p(a.Ea,a,b),Wc(a,a.D));a.D++;return!0}
h.Ea=function(a){if(this.m)if(this.m=null,this.I==1){if(!a){this.V=Math.floor(Math.random()*1E5);a=this.V++;const e=new N(this,this.j,a);let f=this.o;this.T&&(f?(f=Aa(f),Ca(f,this.T)):f=this.T);this.u!==null||this.P||(e.J=f,f=null);if(this.R)a:{var b=0;for(var c=0;c<this.i.length;c++){b:{var d=this.i[c];if("__data__"in d.map&&(d=d.map.__data__,typeof d==="string")){d=d.length;break b}d=void 0}if(d===void 0)break;b+=d;if(b>4096){b=c;break a}if(b===4096||c===this.i.length-1){b=c+1;break a}}b=1E3}else b=
1E3;b=Xc(this,e,b);c=O(this.J);S(c,"RID",a);S(c,"CVER",22);this.G&&S(c,"X-HTTP-Session-Id",this.G);Tc(this,c);f&&(this.P?b="headers="+L(Ic(f))+"&"+b:this.u&&Jc(c,this.u,f));Xb(this.h,e);this.Ra&&S(c,"TYPE","init");this.R?(S(c,"$req",b),S(c,"SID","null"),e.U=!0,Bb(e,c,null)):Bb(e,c,b);this.I=2}}else this.I==3&&(a?Yc(this,a):this.i.length==0||ec(this.h)||Yc(this))};
function Yc(a,b){var c;b?c=b.l:c=a.V++;const d=O(a.J);S(d,"SID",a.L);S(d,"RID",c);S(d,"AID",a.U);Tc(a,d);a.u&&a.o&&Jc(d,a.u,a.o);c=new N(a,a.j,c,a.D+1);a.u===null&&(c.J=a.o);b&&(a.i=b.G.concat(a.i));b=Xc(a,c,1E3);c.H=Math.round(a.va*.5)+Math.round(a.va*.5*Math.random());Xb(a.h,c);Bb(c,d,b)}function Tc(a,b){a.H&&ya(a.H,function(c,d){S(b,d,c)});a.l&&ya({},function(c,d){S(b,d,c)})}
function Xc(a,b,c){c=Math.min(a.i.length,c);const d=a.l?p(a.l.Ka,a.l,a):null;a:{var e=a.i;let k=-1;for(;;){const q=["count="+c];k==-1?c>0?(k=e[0].g,q.push("ofs="+k)):k=0:q.push("ofs="+k);let m=!0;for(let r=0;r<c;r++){var f=e[r].g;const A=e[r].map;f-=k;if(f<0)k=Math.max(0,e[r].g-100),m=!1;else try{f="req"+f+"_"||"";try{var g=A instanceof Map?A:Object.entries(A);for(const [D,E]of g){let M=E;n(E)&&(M=$a(E));q.push(f+D+"="+encodeURIComponent(M))}}catch(D){throw q.push(f+"type="+encodeURIComponent("_badmap")),
D;}}catch(D){d&&d(A)}}if(m){g=q.join("&");break a}}g=void 0}a=a.i.splice(0,c);b.G=a;return g}function $b(a){if(!a.g&&!a.v){a.Y=1;var b=a.Da;u||ta();v||(u(),v=!0);oa.add(b,a);a.A=0}}function Vb(a){if(a.g||a.v||a.A>=3)return!1;a.Y++;a.v=nb(p(a.Da,a),Wc(a,a.A));a.A++;return!0}h.Da=function(){this.v=null;Zc(this);if(this.aa&&!(this.O||this.g==null||this.S<=0)){var a=4*this.S;this.j.info("BP detection timer enabled: "+a);this.B=nb(p(this.Wa,this),a)}};
h.Wa=function(){this.B&&(this.B=null,this.j.info("BP detection timeout reached."),this.j.info("Buffering proxy detected and switch to long-polling!"),this.F=!1,this.O=!0,J(10),Ub(this),Zc(this))};function Ob(a){a.B!=null&&(l.clearTimeout(a.B),a.B=null)}
function Zc(a){a.g=new N(a,a.j,"rpc",a.Y);a.u===null&&(a.g.J=a.o);a.g.P=0;var b=O(a.na);S(b,"RID","rpc");S(b,"SID",a.L);S(b,"AID",a.U);S(b,"CI",a.F?"0":"1");!a.F&&a.ia&&S(b,"TO",a.ia);S(b,"TYPE","xmlhttp");Tc(a,b);a.u&&a.o&&Jc(b,a.u,a.o);a.M&&(a.g.H=a.M);var c=a.g;a=a.ba;c.M=1;c.A=Cb(O(b));c.u=null;c.R=!0;Db(c,a)}h.Va=function(){this.C!=null&&(this.C=null,Ub(this),Vb(this),J(19))};function Tb(a){a.C!=null&&(l.clearTimeout(a.C),a.C=null)}
function Pb(a,b){var c=null;if(a.g==b){Tb(a);Ob(a);a.g=null;var d=2}else if(Sb(a.h,b))c=b.G,Zb(a.h,b),d=1;else return;if(a.I!=0)if(b.o)if(d==1){c=b.u?b.u.length:0;b=Date.now()-b.F;var e=a.D;d=ib();F(d,new mb(d,c,b,e));ac(a)}else $b(a);else if(e=b.m,e==3||e==0&&b.X>0||!(d==1&&Vc(a,b)||d==2&&Vb(a)))switch(c&&c.length>0&&(b=a.h,b.i=b.i.concat(c)),e){case 1:R(a,5);break;case 4:R(a,10);break;case 3:R(a,6);break;default:R(a,2)}}
function Wc(a,b){let c=a.Qa+Math.floor(Math.random()*a.Za);a.isActive()||(c*=2);return c*b}function R(a,b){a.j.info("Error code "+b);if(b==2){var c=p(a.bb,a),d=a.Ua;const e=!d;d=new T(d||"//www.google.com/images/cleardot.gif");l.location&&l.location.protocol=="http"||jc(d,"https");Cb(d);e?Ac(d.toString(),c):Bc(d.toString(),c)}else J(2);a.I=0;a.l&&a.l.pa(b);Uc(a);Sc(a)}h.bb=function(a){a?(this.j.info("Successfully pinged google.com"),J(2)):(this.j.info("Failed to ping google.com"),J(1))};
function Uc(a){a.I=0;a.ja=[];if(a.l){const b=fc(a.h);if(b.length!=0||a.i.length!=0)ka(a.ja,b),ka(a.ja,a.i),a.h.i.length=0,ja(a.i),a.i.length=0;a.l.oa()}}function Yb(a,b,c){var d=c instanceof T?O(c):new T(c);if(d.g!="")b&&(d.g=b+"."+d.g),kc(d,d.u);else{var e=l.location;d=e.protocol;b=b?b+"."+e.hostname:e.hostname;e=+e.port;const f=new T(null);d&&jc(f,d);b&&(f.g=b);e&&kc(f,e);c&&(f.h=c);d=f}c=a.G;b=a.wa;c&&b&&S(d,c,b);S(d,"VER",a.ka);Tc(a,d);return d}
function Gb(a,b,c){if(b&&!a.K)throw Error("Can't create secondary domain capable XhrIo object.");b=a.Aa&&!a.ma?new X(new Dc({ab:c})):new X(a.ma);b.Fa(a.K);return b}h.isActive=function(){return!!this.l&&this.l.isActive(this)};function $c(){}h=$c.prototype;h.ra=function(){};h.qa=function(){};h.pa=function(){};h.oa=function(){};h.isActive=function(){return!0};h.Ka=function(){};function ad(){}ad.prototype.g=function(a,b){return new Y(a,b)};
function Y(a,b){C.call(this);this.g=new Rc(b);this.l=a;this.h=b&&b.messageUrlParams||null;a=b&&b.messageHeaders||null;b&&b.clientProtocolHeaderRequired&&(a?a["X-Client-Protocol"]="webchannel":a={"X-Client-Protocol":"webchannel"});this.g.o=a;a=b&&b.initMessageHeaders||null;b&&b.messageContentType&&(a?a["X-WebChannel-Content-Type"]=b.messageContentType:a={"X-WebChannel-Content-Type":b.messageContentType});b&&b.sa&&(a?a["X-WebChannel-Client-Profile"]=b.sa:a={"X-WebChannel-Client-Profile":b.sa});this.g.T=
a;(a=b&&b.Qb)&&!y(a)&&(this.g.u=a);this.A=b&&b.supportsCrossDomainXhr||!1;this.v=b&&b.sendRawJson||!1;(b=b&&b.httpSessionIdParam)&&!y(b)&&(this.g.G=b,a=this.h,a!==null&&b in a&&(a=this.h,b in a&&delete a[b]));this.j=new Z(this)}t(Y,C);Y.prototype.m=function(){this.g.l=this.j;this.A&&(this.g.K=!0);this.g.connect(this.l,this.h||void 0)};Y.prototype.close=function(){bc(this.g)};
Y.prototype.o=function(a){var b=this.g;if(typeof a==="string"){var c={};c.__data__=a;a=c}else this.v&&(c={},c.__data__=$a(a),a=c);b.i.push(new cc(b.Ya++,a));b.I==3&&ac(b)};Y.prototype.N=function(){this.g.l=null;delete this.j;bc(this.g);delete this.g;Y.Z.N.call(this)};
function bd(a){fb.call(this);a.__headers__&&(this.headers=a.__headers__,this.statusCode=a.__status__,delete a.__headers__,delete a.__status__);var b=a.__sm__;if(b){a:{for(const c in b){a=c;break a}a=void 0}if(this.i=a)a=this.i,b=b!==null&&a in b?b[a]:void 0;this.data=b}else this.data=a}t(bd,fb);function cd(){gb.call(this);this.status=1}t(cd,gb);function Z(a){this.g=a}t(Z,$c);Z.prototype.ra=function(){F(this.g,"a")};Z.prototype.qa=function(a){F(this.g,new bd(a))};
Z.prototype.pa=function(a){F(this.g,new cd(a))};Z.prototype.oa=function(){F(this.g,"b")};ad.prototype.createWebChannel=ad.prototype.g;Y.prototype.send=Y.prototype.o;Y.prototype.open=Y.prototype.m;Y.prototype.close=Y.prototype.close;module.exports.createWebChannelTransport=function(){return new ad};module.exports.getStatEventTarget=function(){return ib()};module.exports.Event=I;module.exports.Stat={jb:0,mb:1,nb:2,Hb:3,Mb:4,Jb:5,Kb:6,Ib:7,Gb:8,Lb:9,PROXY:10,NOPROXY:11,Eb:12,Ab:13,Bb:14,zb:15,Cb:16,Db:17,fb:18,eb:19,gb:20};tb.NO_ERROR=0;tb.TIMEOUT=8;tb.HTTP_ERROR=6;
module.exports.ErrorCode=tb;ub.COMPLETE="complete";module.exports.EventType=ub;eb.EventType=H;H.OPEN="a";H.CLOSE="b";H.ERROR="c";H.MESSAGE="d";C.prototype.listen=C.prototype.J;module.exports.WebChannel=eb;module.exports.FetchXmlHttpFactory=Dc;X.prototype.listenOnce=X.prototype.K;X.prototype.getLastError=X.prototype.Ha;X.prototype.getLastErrorCode=X.prototype.ya;X.prototype.getStatus=X.prototype.ca;X.prototype.getResponseJson=X.prototype.La;X.prototype.getResponseText=X.prototype.la;
X.prototype.send=X.prototype.ea;X.prototype.setWithCredentials=X.prototype.Fa;module.exports.XhrIo=X;}).apply( typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self  : typeof window !== 'undefined' ? window  : {});
